### PR TITLE
update VPA and VPA-e2e vendor to K8s v1.26

### PR DESCRIPTION
**Pull request by kushagra98**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR updates VPA and VPA e2e dependencies for VPA and VPA-e2e tests to K8s v1.26.
1. Updated VPA vendor to 1.26, fixed files with outdated things.
2. Updated VPA-e2e vendor to 1.26, fixed files with outdated things. (https://github.com/kubernetes/kubernetes/commit/dfdf88d4faafa6fd39988832ea0ef6d668f490e9)
3. Added script to update VPA vendor (equivalent to  https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/update-kubernetes-deps-in-e2e.sh)

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kushagra98** [comment]
/hold
Running VPA-e2e with the updated vendor.

**Comment by kushagra98** [comment]
OOM tests completes in ~ 18 min. Increased the time limit to 20min.

**Comment by kushagra98** [comment]
/hold cancel
I've run full-vpa tests with these changes (both VPA and tests) and they passed.

**Review by jbartosik — CHANGES_REQUESTED** [review]
I think this looks good.

But can you make it so that vendor changes are in their own commit. It will be much easier forme to be sure that I actually looked at all other changes.

**Comment by kushagra98** [comment]
This PR doesn't seems to be clean. Created a new one #5536 with minimal commits.

**Pull request closed without merging**
