### PR TITLE
CAS azure e2e: add namespace to all resources in CAPZ template

### PR DESCRIPTION
**Pull request by nojnhuh**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:

Adds `metadata.namespace` to a couple of lingering resources in the CAPZ template used for cluster-autoscaler e2e tests where it wasn't already defined.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
