### PR TITLE
AWS: Fix nvidia gpu resource name, re-enable ScaleToZero

### PR DESCRIPTION
**Pull request by discordianfish**
These are two somewhat separate changes, so let me know if I should split this PR:

1) Rename gpu resource name, the same as #407 but for AWS
2) Set scaleToZero = true. It looks like this was changed (by accident?) in #462

I've tested the changes manually and scaling to and from 0 works on my cluster with the nvidia k8s device plugin.

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
Thanks for contributing! @sethpollack @mumoshu can you PTAL?

**Comment by sethpollack** [comment]
lgtm

@negz was there a reason `scaleToZeroSupported` was defaulted to false?

**Comment by negz** [comment]
https://github.com/kubernetes/autoscaler/pull/462/files#diff-34ecd32e36ab8898fff1637bb1b39c2cL367

@sethpollack Nope - my bad. I see now that it was enabled and I disabled it. My apologies - completely accidental on my part.

**Comment by sethpollack** [comment]
@negz thanks

**Comment by bhack** [comment]
Is this available in any released image?

**Comment by alexnederlof** [comment]
@discordianfish would it be possible for you to also PR This on the 1.1.2 release for a 1.1.3 release? Everyone using Kops is still stuck on Kubernetes v1.9, which is bound to autoscaler 1.1.x. Shipping it to the 1.1.x branch would help a lot of people. I'm keen to help, but I've never done anything in Go, and couldn't figure out how to do it myself (just cherry picking didn't work 😉 )

**Comment by alexnederlof** [comment]
Or perhaps @aleksandra-malinowska

**Comment by kaazoo** [comment]
I tried cluster-autoscaler 1.2.2 on a 1.9.9 cluster (created by kops 1.9.1). Allthough it's not not officially supported, scaling up my GPU ASG from 0 seems to work.

**Pull request merged**
