### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by delirius325**
Fixed a simple typo in the README 😄

### CODE REVIEW

**Comment by mwielgus** [comment]
please sign cla

**Comment by delirius325** [comment]
It's been signed for over 3 hours, for some reason I haven't received the email confirming that it was though. Although I tried validating my email (again) and the request gave me an error saying I cannot use the link twice. I'll just wait a day or two.

**Comment by mwielgus** [comment]
Apparently the CLA is not yet considered as signed. Please try again.

**Comment by mwielgus** [comment]
CLA still not signed, PR fix is super minor, closing.

**Pull request closed without merging**
