### PR TITLE
issues/933 Consider making UnremovableNodeRecheckTimeout configurable

### PR DESCRIPTION
**Pull request by nicdoye**
Hi this is my first PR against the main(ish) parts of k8s, and I am unsure even how to run tests.

I'm hoping to add the feature requested in https://github.com/kubernetes/autoscaler/issues/933

### CODE REVIEW

**Comment by nicdoye** [comment]
Apologies for the large number of changes!

**Comment by aleksandra-malinowska** [comment]
> Apologies for the large number of changes!

No worries. Can you please squash the commits before we merge this?

Looks good to me. @MaciekPytel WDYT?

**Comment by nicdoye** [comment]
Done. Thanks for the protip!

**Pull request merged**
