### PR TITLE
digitalocean: support reading access token from file

### PR DESCRIPTION
**Pull request by timoreimann**
This makes it possible to securely store the access token in a file and load it into the cloud provider from there.

Document DigitalOcean's cloud config format while we are here.

### CODE REVIEW

**Review by MorrisLaw — APPROVED** [review]
looks good and thanks for updating the tests too :100:

**Comment by MorrisLaw** [comment]
@timoreimann update the conflict please

**Comment by timoreimann** [comment]
@MorrisLaw conflict should be resolved now.

**Pull request merged**
