### PR TITLE
Replace `BuildTestContainer` with use of builder

### PR DESCRIPTION
**Pull request by kwiesmueller**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Resolves a code TODO by replacing uses of `BuildTestContainer` with use of the builder directly.

#### Which issue(s) this PR fixes:

Fixes code TODO

#### Special notes for your reviewer:

I was resolving the TODO and generally think it might have helped clean things up, but would like to get some feedback if we all agree this change makes sense.
I can see it both ways that having this helper made sense. If so we should just remove the TODO instead.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @jbartosik

### CODE REVIEW

**Comment by jbartosik** [comment]
/retest

[Test failure](https://github.com/kubernetes/autoscaler/actions/runs/5394097024/jobs/9794784139?pr=5896) seems unrelated to the PR:

```
W0627 20:22:16.992770   40599 clusterstate.go:444] AcceptableRanges have not been populated yet. Skip checking
--- FAIL: TestBinpackingLimiter (0.00s)
    common.go:404: 
        	Error Trace:	/home/runner/work/autoscaler/autoscaler/go/src/k8s.io/autoscaler/cluster-autoscaler/core/test/common.go:404
        	            				/home/runner/work/autoscaler/autoscaler/go/src/k8s.io/autoscaler/cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go:173
        	            				/home/runner/work/autoscaler/autoscaler/go/src/k8s.io/autoscaler/cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go:855
        	Error:      	did not find expansionOptionToChoose %+v
        	Test:       	TestBinpackingLimiter
        	Messages:   	&{GroupName:ng1 SizeChange:1}
    orchestrator_test.go:858: 
        	Error Trace:	/home/runner/work/autoscaler/autoscaler/go/src/k8s.io/autoscaler/cluster-autoscaler/core/scaleup/orchestrator/orchestrator_test.go:858
        	Error:      	Should be true
        	Test:       	TestBinpackingLimiter
```

**Review by jbartosik — APPROVED** [review]
Looks good to me

One idea I have is that we're calling `resource.MustParse` each time we call `WithMemRequest` and similar functions (in existing code too). What do you think about changing the builder to take a string input instead?

(this is a strict improvement so if you think it's better to merge as-is let's do that)

**Comment by kwiesmueller** [comment]
If we always use a string for the quantity it makes sense to simplify, agreed.
Would do that in a follow-up.

**Comment by kwiesmueller** [comment]
Retest didn't trigger, trying again.

/retest
/test

**Review by jbartosik — APPROVED** [review]
/lgtm
/approve

**Comment by jbartosik** [comment]
> If we always use a string for the quantity it makes sense to simplify, agreed.

It seems so to me.

**Pull request merged**
