### PR TITLE
Stop applying the beta.kubernetes.io/os and arch

### PR DESCRIPTION
**Pull request by pacoxu**
/kind cleanup

See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

```release-note
Stop applying the beta.kubernetes.io/os and arch
```

### CODE REVIEW

**Comment by pacoxu** [comment]
BTW, https://github.com/kubernetes/autoscaler/blob/9d54f7b782fe9e1197ff20ed9e71e3af81ca1ae9/cluster-autoscaler/utils/labels/labels.go#L121 there are some other deprecated labels support in autoscaler. Those labels are deprecated since v1.17 according to https://kubernetes.io/docs/reference/labels-annotations-taints/.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by mwielgus** [comment]
Editing release notes in the commit to make sure it gets to release notes.

**Pull request merged**
