### PR TITLE
chore: update cdi.go

### PR DESCRIPTION
**Pull request by eltociear**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
charcter -> character
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
@eltociear, IMO we can't change the vendor directory, these dependencies are mostly coming from the k/k repo and are updated from there, this package has not been updated there yet https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/util/cdi/cdi.go#L119

Once upstream is updated, then we can upgrade the VPA vendor directory.

**Comment by Shubham82** [comment]
cc @kwiesmueller @voelzmo
PTAL!

**Review by kwiesmueller — CHANGES_REQUESTED** [review]
This test is in a vendor directory. I don't think we should be manually updating those :thinking: 
/hold

**Comment by adrianmoisey** [comment]
Out of curiosity, what is the process to get a vendor directory updated?
Is it this script: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/update-kubernetes-deps.sh

**Comment by Shubham82** [comment]
> Out of curiosity, what is the process to get a vendor directory updated?
Is it this script: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/update-kubernetes-deps.sh

IMO the script you mentioned above is updating the [VPA vendor directory](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/vendor)
The script for updating the VPA [e2e vendor directory](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/e2e) is as follows: 
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/update-kubernetes-deps-in-e2e.sh

**Comment by Shubham82** [comment]
> Out of curiosity, what is the process to get a vendor directory updated?

The purpose is to update/sync VPA dependencies corresponding to upstream repositories`.

**Comment by Shubham82** [comment]
IMO, we can close this PR, once upstream is updated then we can update the e2e vendor directory by running those scripts.
@kwiesmueller WDYT?

**Comment by Shubham82** [comment]
As mentioned in the comments above, closing this PR.
/close

**Pull request closed without merging**
