### PR TITLE
Add m5ad, r5ad and t3a instance families

### PR DESCRIPTION
**Pull request by Jeffwan**
Add m5ad, r5ad and t3a instance families.  Address #1936 

Will take some time later to find a way to dynamically load latest instance in runtime. This is not elegant that every time we need to add new instance types

### CODE REVIEW

**Comment by sc250024** [comment]
When is this getting released? Currently none of the latest CA releases support the new `t3a` instances types.

**Comment by Jeffwan** [comment]
@sc250024 This is included in 1.15 branch. Do you need t3a instance in older branches? I can cherry-pick back to other branches as well

**Comment by sc250024** [comment]
@Jeffwan Thanks for your reply, my comment above sounds a bit bitchy, sorry for that 😅

Anyway, if you could cherry pick the changes into the 1.13 and 1.14 branches, that would be very much desired. Case in point, the latest version of EKS on AWS only supports up to 1.13 at the latest, with 1.14 coming soon.

Thank you sir!

**Comment by Jeffwan** [comment]
Sure. I will cherry-pick the change back to 1.12-1.14. BTW, this won't release immediately, release team has it's schedule.

**Pull request merged**
