### PR TITLE
Packet autoscaler cloudprovider updates

### PR DESCRIPTION
**Pull request by cprivitere**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR updates the packet autoscaler in the following ways:
- use https://api.equinix.com/metal/v1 instead of packet endpoint
- remove old plans and add new plans
- update plan pricing
- update test to use current plan names
- provide a source template file for the cloud-init used in example deployment
- update RBAC in the example deployment to current requirements
- add resource request for container to example deployment
- use a tagged version instead of latest in example deployment
- use control-plane instead of master for taint toleration in example deployment
- Update embedded cloud init in example deployment so that is functional
- Bump installed k8s in the example to 1.28.1

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
We now use metros in the Equinix Metal (Packet) cloudprovider. Facilities support has been removed.
```

Code was tested manually by deploying a build of the branch and testing that nodes could scale from zero.

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by Shubham82** [comment]
@cprivitere please address the failed test which is required to be passed for the PR to merge

**Comment by displague** [comment]
Fixes #5855
Fixes #4287

**Pull request merged**
