### PR TITLE
Add jaypipes to aws cloud provider OWNERS

### PR DESCRIPTION
**Pull request by Jeffwan**
We need more AWS contributors to review/approve PR. 

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

### CODE REVIEW

**Comment by MaciekPytel** [comment]
I think you could self-approve this, but just in case:
/approve
Great to have you @jaypipes.

**Comment by jaypipes** [comment]
/lgtm

weird doing this for a PR involving myself... :)

**Pull request merged**
