### PR TITLE
Azure: skip non azure nodes

### PR DESCRIPTION
**Pull request by sergelogvinov**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Skip non azure nodes (providerID) to support on-premise kubernetes nodes.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

If kubernetes cluster has non azure node, node-autoscaller wouldn't start.

Azure Cloud is highly compatible with hybrid cloud environments,
This feature facilitates the seamless integration of on-premise infrastructure with Azure Cloud.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Bryce-Soghigian — APPROVED** [review]

**Review by Bryce-Soghigian — COMMENTED** [review]
How does this work for kubemark and other non azure nodes? I guess we just skip?

**Comment by sergelogvinov** [comment]
> How does this work for kubemark and other non azure nodes? I guess we just skip?

Yep, otherwise it will stack on booting process (creating node groups).
It's the same as you use node auto discovery labels. All unlabeled nodes or `kubernetes.azure.com/managed=false` should be skipped.

**Comment by feiskyer** [comment]
looks reasonable for hybrid cluster. 
/lgtm
/approve

**Pull request merged**
