### PR TITLE
azure labels to skip in nodegroupset

### PR DESCRIPTION
**Pull request by gandhipr**
#### What type of PR is this?
feature - skip a few azure specific labels in nodegroupset

#### What this PR does / why we need it:
This PR add a few azure specific labels that needs to be skipped when checking for nodegroup similarity.
This change doesn't include moving azure specific lables under /azure directory - that chore will be covered in another change

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Skips Azure-specific node labels that might mistakenly categorize nodegroups as different when, in reality, they are similar.

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x13n** [comment]
Change itself LGTM, though WDYT about moving this code to `cluster-autoscaler/cloudprovider/azure/processors`? You wouldn't require global CA approval that way.

/assign

**Review by rakechill — APPROVED** [review]

**Review by tallaxes — CHANGES_REQUESTED** [review]
The changes themselves look good (may be a good idea to normalize capitalization of constants), but the code currently does not build, likely as a result of the package move; additional post-move work needed.

**Review by tallaxes — APPROVED** [review]
If we are keeping these outside of provider-specific space temporarily (for change sequencing reasons), and plan to move it the near future - let's add a comment to this effect in the description.

**Comment by jackfrancis** [comment]
/lgtm

@MaciekPytel @gjtempleton @x13n would it make sense to schedule a follow-up item to move all of the cloud-provider-specific stuff in `cluster-autoscaler/processors/nodegroupset/` into the provider-specific code surface area so that this maintenance can be performed without having to loop in core cluster-autoscaler approvers?

**Comment by x13n** [comment]
Yeah, that makes a lot of sense to me. There's no point having cloudprovider-specific processors in core CA dirs.

**Comment by jackfrancis** [comment]
> Yeah, that makes a lot of sense to me. There's no point having cloudprovider-specific processors in core CA dirs.

Cool, once this gets and approval and merge I'll do that.

**Pull request merged**
