### PR TITLE
YAML linting Azure examples

### PR DESCRIPTION
**Pull request by achinthagunasekara**
YAML linting Azure examples

### CODE REVIEW

**Comment by bskiba** [comment]
The formatting seems a bit inconsistent to me, but deferring to @feiskyer for decision

**Comment by feiskyer** [comment]
>The formatting seems a bit inconsistent to me, but deferring to @feiskyer for decision

Yep. @achinthagunasekara Could you make the formatting consistent for all files?

**Comment by mwielgus** [comment]
This PR is about linting Azure cloud provider, not VPA, please remove unnecessary commits.

**Comment by achinthagunasekara** [comment]
@mwielgus I've removed unrelated commits

**Comment by achinthagunasekara** [comment]
@feiskyer Could you please point me at the lines you were referring to? I'll correct it :)

**Pull request merged**
