### PR TITLE
Cluster Autoscaler 1.2.5

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by feiskyer** [comment]
I'm preparing a cherry pick for all branches, would send out this night. missed this patch release..

**Comment by losipiuk** [comment]
> I'm preparing a cherry pick for all branches, would send out this night. missed this patch release..

No wories. I will wait unitl your changes are in before releasing.

**Comment by feiskyer** [comment]
@losipiuk thanks, cherry pick merged now.

**Pull request merged**
