### PR TITLE
chore: backport latest VMs pool and HasInstance() implementations and resolve inconsistencies in config and unit tests, for 1.29

### PR DESCRIPTION
**Pull request by comtalyst**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
These differences have effectively disabled cherry-pick automation in these areas. Upcoming changes (e.g., more VMs pool implementation, cloud-provider-azure integration rework, more fixes that need to be done in all versions) will be agonizing experiences, not to mention the past ones.
This PR will amend some of those differences, which is mostly VMs pool and HasInstance() implementations, as well as known inconsistencies in config and unit tests. The latter has known to bother us in various circumstances. 
They cannot be cherry-picked in normal means easily due to conflict with Azure defork operations, which have to resolve these conflicts at some point anyway.

#### Which issue(s) this PR fixes:

- https://github.com/Azure/AKS/issues/4286
- https://github.com/kubernetes/autoscaler/issues/4456

#### Special notes for your reviewer:

Original `HasInstance()` implementation PR: https://github.com/kubernetes/autoscaler/pull/6956
Differences visualization I used as a reference, with some labels: https://github.com/comtalyst/autoscaler/pull/5/files

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by tallaxes — APPROVED** [review]

**Comment by nojnhuh** [comment]
This job no longer exists for this branch as of https://github.com/kubernetes/test-infra/pull/33361

/override pull-cluster-autoscaler-e2e-azure

**Comment by nojnhuh** [comment]
> This job no longer exists for this branch as of [kubernetes/test-infra#33361](https://github.com/kubernetes/test-infra/pull/33361)
> 
> /override pull-cluster-autoscaler-e2e-azure

I suppose this command isn't registered for the repo? https://prow.k8s.io/command-help?repo=kubernetes%2Fautoscaler

I'll try making a fix in test-infra to add this back just as a stub so as not to block any PRs for the time being.

**Pull request merged**
