### PR TITLE
Missing support for AWS inf2 instance types

### PR DESCRIPTION
**Pull request by mbdebian**
Cherry pick from master adding support for the AWS Inferentia 2 instance types targetting branch 1.24

What type of PR is this?
/kind feature

What this PR does / why we need it:
Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/autoscaler/issues/5626

Special notes for your reviewer:
Does this PR introduce a user-facing change?
NONE
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by ff-apple** [comment]
@feiskyer @Jeffwan can you please take a look? Thank you

**Comment by ff-apple** [comment]
@gjtempleton Thank you!

**Comment by mbdebian** [comment]
Thank you so much!

**Comment by gjtempleton** [comment]
@ff-apple Yep, I'm [currently scheduled](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/README.md#patch-releases) to cut the next set of patch releases next week.

**Pull request merged**
