### PR TITLE
cloudprovider/digitalocean: fix unit tests

### LINKED ISSUE #2252: Unit tests failing after PR #2245
Unit tests for cluster-autoscaler are failing after #2245:
```
cloudprovider/digitalocean/godo/util/droplet.go:8:2: cannot find package "github.com/digitalocean/godo" in any of:
	/usr/local/google/home/jtuznik/go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/digitalocean/godo/vendor/github.com/digitalocean/godo (vendor tree)
	/usr/local/google/home/jtuznik/go/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/digitalocean/godo
	/usr/lib/google-golang/src/github.com/digitalocean/godo (from $GOROOT)
	/usr/local/google/home/jtuznik/go/src/github.com/digitalocean/godo (from $GOPATH)
```

This was not caught by Travis due to #2251.

### PR DESCRIPTION
**Pull request by fatih**
The `godo/util` package is not used and wasn't changed during vendoring
of the godo package. Seems like Travis didn't picked up this in the
initial PR. Let's remove the `util/` folder as it's not needed and also
add a documentation to list the changes we need to make in the `godo`
package.

fixes #2252

### CODE REVIEW

**Comment by fatih** [comment]
Not sure why this is marked with `invalid-commit-message`. Is there a way to see what is causing this?

**Comment by fatih** [comment]
cc @towca

**Comment by towca** [comment]
The label is from the automatic github features in commit messages (this was communicated in the k8s-ci-robot message but I guess you found it already).

LGTM, but we should hold until the PR fixing Travis is merged first.
/hold

**Comment by fatih** [comment]
@towca gotcha. I removed the `fixes` line from the commit and everything seems to be ok.

**Comment by towca** [comment]
The test passed after the Travis fix.
/hold cancel
/cc @MaciekPytel to approve

**Pull request merged**
