### PR TITLE
Cherry pick label vmss

### PR DESCRIPTION
**Pull request by hichemaichour**
Cherry picking:
1. [enable min/max on Azure VMSS autodiscovery](https://github.com/kubernetes/autoscaler/pull/2121)
2. [Fix azure autodiscovery when max tags aren't specified](https://github.com/kubernetes/autoscaler/pull/2714)

/area provider/azure

### CODE REVIEW

**Comment by marwanad** [comment]
hey @hichemaichour, thanks for the contribution.

Given the size of the changes and that it touches multiple cloud providers and also the nature of it being a feature), I don't think we will be cherry-picking this to earlier releases.

**Comment by hichemaichour** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

Signed

**Comment by hichemaichour** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

Signed

**Comment by hichemaichour** [comment]
@marwanad , I understand

I was just looking forward to this feature, and with [this issue](https://github.com/kubernetes/autoscaler/issues/2628) (#2628) present for 1.17, I was hoping that the feature is introduced as well in 1.16

**Comment by marwanad** [comment]
@hichemaichour yup, sorry about that. 

I think you can ignore the CSI node log errors, but regardless 1.17 is meant to be run on K8s 1.17 only.

/close

**Pull request closed without merging**
