### PR TITLE
Add Shubham82 to the reviewers

### PR DESCRIPTION
**Pull request by Shubham82**
Requirements:
As per: https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer

- member for at least 3 months - **Yes, I have been an active member of the Kubernetes community for more than two years. ([Member Request](https://github.com/kubernetes/org/issues/3604))**
- Primary reviewer for at least 5 PRs to the codebase - **Yes, Reviewd [264](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Ashubham82) PR so far(Open: [9](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Ashubham82+is%3Aopen) and closed: [255](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Ashubham82+is%3Aclosed), merged: [226](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+assignee%3Ashubham82+is%3Amerged+))**
- Reviewed or merged at least 20 substantial PRs to the codebase - **Yes, in addition to the above authored [72](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ashubham82) PR so far**
- Knowledgeable about the codebase - **Yes**
- Sponsored by a subproject approver
  - With no objections from other approvers
  - Done through PR to update the OWNERS file
- May either self-nominate, be nominated by an approver in this subproject, or be nominated by a robot

/assign @gjtempleton

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @gjtempleton
Gentle Reminder!

**Comment by raywainman** [comment]
/lgtm

Thanks for your help :)

**Comment by Shubham82** [comment]
> /lgtm
> 
> Thanks for your help :)
> 
> Edit: Thought this was for vpa repo so my LGTM isn't worth much over here but LGTM nonetheless, appreciate all your contributions

Thanks @raywainman

**Comment by gjtempleton** [comment]
Thanks for this
/lgtm
/approve

**Comment by Shubham82** [comment]
Thanks @gjtempleton

**Pull request merged**
