### PR TITLE
Remove unnecessary build-args

### PR DESCRIPTION
**Pull request by youngbo89**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Clearer Readability by removing unused build-args

### CODE REVIEW

**Comment by adrianmoisey** [comment]
It seems these were removed from the Dockerfile in https://github.com/kubernetes/autoscaler/commit/9a754db1c2de2a516bbf03f36993831fe42ff2f9

Not a developer, so my +1 is meaningless, but this looks good to me

**Comment by voelzmo** [comment]
Good catch! This is indeed a leftover from the refactoring done to the build process in #6338.
/lgtm

**Pull request merged**
