### PR TITLE
Backport #6528 [CA] Fix expectedToRegister to respect instances with nil status into CA1.29

### PR DESCRIPTION
**Pull request by Shubham82**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR is cherry-picked, which backports #6528 into CA 1.28
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @feiskyer, @x13n
PTAL!

**Comment by agamez-harmonicinc** [comment]
Is this fix available for all 1.29 versions? I've faced this problem is CA 1.29.3 a couple of days ago.

**Comment by Shubham82** [comment]
Hi @agamez-harmonicinc No, this fix is available in the CA v1.29.4 version for v1.29
Please take a look at this:
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.29.4

**Comment by Shubham82** [comment]
> Thanks a lot @Shubham82 , appreciate the quick response

You're Welcome!

**Pull request merged**
