### PR TITLE
Move all VPA docs into ./docs

### PR DESCRIPTION
**Pull request by adrianmoisey**
/kind documentation

This PR is a replacement for https://github.com/kubernetes/autoscaler/pull/7532 and the discussion that happened after it.

[sig-docs](https://kubernetes.slack.com/archives/C1J0BPD2M/p1732610575933279) discussion
[sig-autoscaling](https://kubernetes.slack.com/archives/C09R1LV8S/p1732603753865239) discussion

The tl;dr is that this PR is decoupling the docs from the code layout, with the hopes that it allows us to more easily write documentation. Having something that is more easily navigable may help us find the right place to put the documentation.

Note: there are a few bits and pieces that I'm not happy with right now, like the features page. My plan is to get this merged first, and follow up with more PRs to tidy up.

After this PR has been merged, my hope is that some more documentation is written (based on new features, or to clarify common support issues that we get).

Then sometime in the future, we can decide if it makes sense to go with a standalone website, or move to k/website.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
ok, now that i'm looking at the correct PR, this looks much better lol.

i think this makes sense to me and i'm happy to see the readme updated.

copied from my comment on the other pr

> also, i was thinking about how we might want to document the cluster-autoscaler stuff and i think it will be challenging to solve this problem due to the providers. i think it's possible we could migrate the core CA docs, but we would want to have links for the provider specific pieces since those docs are owned by the various providers.

**Comment by omerap12** [comment]
Amazing!

**Comment by voelzmo** [comment]
/approve

great work, thanks!

**Pull request merged**
