### PR TITLE
Add support for cronjobs in VPA

### LINKED ISSUE #1790: VPA for CronJob
Would be great to have the VPA update CronJob resources.

### PR DESCRIPTION
**Pull request by bskiba**
Fixes #1790

### CODE REVIEW

**Comment by bskiba** [comment]
@schylek

**Comment by schylek** [comment]
In general /lgtm. Do you think Cron Jobs are worth adding e2e test?

**Comment by bskiba** [comment]
I was thinking about adding e2e. Currently we only have almost all tests with VPA on Deployment, the only ones where we exercise different controllers is updater (Evicts pods in ...). I came to a conclusion that it makes little sense to evict pods from a CronJob.
However it would be nice to have a "VPA provides recommendations" scenario for all the known controllers.

**Comment by bskiba** [comment]
Yes, once this releases, if you set VPA on CronJob and updateMode: Initial, each new launched Job will get request based on recommendations calculated from previous jobs usage.

Note, this will not work well with short lived jobs (<1minute).

**Comment by johanneswuerbach** [comment]
@bskiba is there any timeline when this is going to be released?

**Pull request merged**
