### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by imageschool**
must be a typo, the default is set as 0.11.0 in kubernetes:vpa-release-0.11

#### Which component this PR applies to?
vertical-pod-autoscaler

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
fixing documentation typo on default vpa version

#### Which issue(s) this PR fixes:
typo from 0.9.2 to 0.11.0

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jbartosik** [comment]
Please sign CLA otherwise we won't be able to accept the contribution

**Comment by imageschool** [comment]
@jbar

> Please sign CLA otherwise we won't be able to accept the contribution

Signed it just now!

**Review by jbartosik — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
