### PR TITLE
Migrate pod_nanny to fetch only nodes metadata.

### PR DESCRIPTION
**Pull request by mborsz**
This pod requires only number of nodes so we can fetch only nodes
metadata to reduce resource consumption and latency.
Tests on 5000-node cluster show that this change reduces 'GET /api/v1/nodes' latency from ~5s to ~100ms.

### CODE REVIEW

**Comment by mborsz** [comment]
I ran verify locally and had to do small fixes.

The problem with travis seems to be unrelated to the change, according to google it's rather related to the fact we are still using unsupported go 1.8: https://github.com/apache/incubator-openwhisk-cli/issues/376

**Comment by wojtek-t** [comment]
That means, that to be able to merge this PR, we should probably first upgrade the Go version. That should hopefully be pretty simple.

**Comment by mborsz** [comment]
Created #1392, once it's merged I will rebase this PR.

**Comment by MaciekPytel** [comment]
Ping me once @wojtek-t lgtms this and I'll merge it.

**Comment by mborsz** [comment]
Travis is happy now,

wojtek-t PTAL?

**Pull request merged**
