### PR TITLE
fix ca deploy spec

### PR DESCRIPTION
**Pull request by silenceshell**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

The deploy spec in README is incorret.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @silenceshell 
Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by mwielgus** [comment]
Please sign the CLA, otherwise good to go.

**Comment by Shubham82** [comment]
Hi @silenceshell 
Please sign the CLA, it is required to merge this PR.

**Pull request merged**
