### PR TITLE
Refactor logging statements

### LINKED ISSUE #6905: vpa: Follow Kubernetes logging guideline
**Which component are you using?**:

vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Currently, the logging in the VPA components does not follow the best practices and guidelines which are followed in the K8s ecosystem. VPA, as a core K8s component, should follow [sig-instrumentation's Logging guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md).

For example, let's take https://github.com/kubernetes/autoscaler/blob/bd8153b59d9d0da84a9d4e9b6b34e08f89b03f26/vertical-pod-autoscaler/pkg/updater/logic/updater.go#L220. The issues with this log are:
- It does not start with a capital letter. From [sig-instrumentation's Logging guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md): "Start from a capital letter."
- It is not a structured log. See [Structured Logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging).

**Describe the solution you'd like.**:
Follow [sig-instrumentation's Logging guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md) in the VPA's codebase.

**Describe any alternative solutions you've considered.**:
N/A

**Additional context.**:
N/A

### PR DESCRIPTION
**Pull request by omerap12**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #6905

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by Shubham82** [comment]
@omerap12, curious to know that, does the all VPA components files follow the guidelines as mentioned in issue #6905, If yes we can mention issue fixes in the PR description (that closes the issue once this PR merge) otherwise we can mention it as a part of #6905 as you did in others PRs (related PR).

**Comment by Shubham82** [comment]
> @omerap12, curious to know that, does all VPA components files follow the guidelines as mentioned in issue #6905, If yes we can mention issue fixes in the PR description (that closes the issue once this PR merge) otherwise we can mention it as a part of #6905 as you did in others PRs (related PR).

Other than the above concern changes look good to me.
/lgtm

**Comment by omerap12** [comment]
> @omerap12, curious to know that, does all VPA components files follow the guidelines as mentioned in issue #6905, If yes we can mention issue fixes in the PR description (that closes the issue once this PR merge) otherwise we can mention it as a part of #6905 as you did in others PRs (related PR).

Yes, this is the final PR that will resolve the issue, so it’s all good.
image

**Comment by Shubham82** [comment]
Great!
Thanks @omerap12 for the information!

**Comment by Shubham82** [comment]
cc @kwiesmueller @raywainman
Need your approval to merge this PR, PTAL!

Thanks

**Review by kwiesmueller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
