### PR TITLE
Fixing YAML formatting issues for AWS examples

### PR DESCRIPTION
**Pull request by achinthagunasekara**
## Description

Fixing YAML formatting issues for AWS examples

## Testing 

agunasekara@MEL-M-AGUNASEKARA01:examples (dev-agunasekara-yamllint)$ find . -name '*.yaml' | xargs yamllint
agunasekara@MEL-M-AGUNASEKARA01:examples (dev-agunasekara-yamllint)$

### CODE REVIEW

**Comment by achinthagunasekara** [comment]
I signed it

**Comment by mwielgus** [comment]
Please resolve conflicts.

**Comment by achinthagunasekara** [comment]
@mwielgus conflicts were resolved 👍

**Pull request merged**
