### PR TITLE
VPA: separate module for e2e tests

### PR DESCRIPTION
**Pull request by wozniakjan**
Effort to simplify go modules tracking even more than https://github.com/kubernetes/autoscaler/pull/2530 by removing the requirement for replace directives with filesystem absolute paths and separate go module for the e2e tests.

It is generally not recommended to depend on `k8s.io/kubernetes` https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505725449, and opens doors to issues for people who may want to depend on VPA - https://github.com/kubernetes/kube-state-metrics/pull/949#discussion_r344429628

It looks like the e2e tests are the only large obstacle in removing the dependency on `k8s.io/kuberentes`. So I would like to propose separate go module for the e2e tests to simplify depending on VPA and only make life hard for those who decide to depend on VPA e2e package. Input from maintainers is greatly appreciated.

<details><summary>checking imports - grep output</summary>
<p>

```
$ grep k8s.io/autoscaler/vertical-pod-autoscaler --include=*.go -nre '[[:blank:]]"k8s.io/kubernetes' | grep -v "$vendor/k8s.io/kubernetes"
./pkg/utils/metrics/metrics.go:28:	_ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client-go metrics registration
./e2e/v1/updater.go:33:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/updater.go:34:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1/updater.go:35:	framework_job "k8s.io/kubernetes/test/e2e/framework/job"
./e2e/v1/updater.go:36:	framework_rs "k8s.io/kubernetes/test/e2e/framework/replicaset"
./e2e/v1/updater.go:37:	framework_ss "k8s.io/kubernetes/test/e2e/framework/statefulset"
./e2e/v1/updater.go:38:	testutils "k8s.io/kubernetes/test/utils"
./e2e/v1/autoscaling_utils.go:34:	api "k8s.io/kubernetes/pkg/apis/core"
./e2e/v1/autoscaling_utils.go:35:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/autoscaling_utils.go:36:	"k8s.io/kubernetes/test/e2e/framework/replicaset"
./e2e/v1/autoscaling_utils.go:37:	e2eservice "k8s.io/kubernetes/test/e2e/framework/service"
./e2e/v1/autoscaling_utils.go:38:	testutils "k8s.io/kubernetes/test/utils"
./e2e/v1/autoscaling_utils.go:42:	imageutils "k8s.io/kubernetes/test/utils/image"
./e2e/v1/e2e_test.go:33:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/e2e_test.go:34:	"k8s.io/kubernetes/test/e2e/framework/config"
./e2e/v1/e2e_test.go:35:	"k8s.io/kubernetes/test/e2e/framework/testfiles"
./e2e/v1/e2e_test.go:36:	"k8s.io/kubernetes/test/e2e/framework/viperconfig"
./e2e/v1/e2e_test.go:37:	"k8s.io/kubernetes/test/e2e/generated"
./e2e/v1/e2e_test.go:38:	"k8s.io/kubernetes/test/utils/image"
./e2e/v1/e2e_test.go:41:	_ "k8s.io/kubernetes/test/e2e/apimachinery"
./e2e/v1/e2e_test.go:42:	_ "k8s.io/kubernetes/test/e2e/apps"
./e2e/v1/e2e_test.go:43:	_ "k8s.io/kubernetes/test/e2e/auth"
./e2e/v1/e2e_test.go:44:	_ "k8s.io/kubernetes/test/e2e/autoscaling"
./e2e/v1/e2e_test.go:45:	_ "k8s.io/kubernetes/test/e2e/cloud"
./e2e/v1/e2e_test.go:46:	_ "k8s.io/kubernetes/test/e2e/common"
./e2e/v1/e2e_test.go:47:	_ "k8s.io/kubernetes/test/e2e/instrumentation"
./e2e/v1/e2e_test.go:48:	_ "k8s.io/kubernetes/test/e2e/kubectl"
./e2e/v1/e2e_test.go:49:	_ "k8s.io/kubernetes/test/e2e/lifecycle"
./e2e/v1/e2e_test.go:50:	_ "k8s.io/kubernetes/test/e2e/lifecycle/bootstrap"
./e2e/v1/e2e_test.go:51:	_ "k8s.io/kubernetes/test/e2e/network"
./e2e/v1/e2e_test.go:52:	_ "k8s.io/kubernetes/test/e2e/node"
./e2e/v1/e2e_test.go:53:	_ "k8s.io/kubernetes/test/e2e/scalability"
./e2e/v1/e2e_test.go:54:	_ "k8s.io/kubernetes/test/e2e/scheduling"
./e2e/v1/e2e_test.go:55:	_ "k8s.io/kubernetes/test/e2e/servicecatalog"
./e2e/v1/e2e_test.go:56:	_ "k8s.io/kubernetes/test/e2e/storage"
./e2e/v1/e2e_test.go:57:	_ "k8s.io/kubernetes/test/e2e/storage/external"
./e2e/v1/e2e_test.go:58:	_ "k8s.io/kubernetes/test/e2e/ui"
./e2e/v1/e2e_test.go:59:	_ "k8s.io/kubernetes/test/e2e/windows"
./e2e/v1/recommender.go:32:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/recommender.go:33:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1/common.go:37:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/common.go:38:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1/actuation.go:30:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/actuation.go:31:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1/e2e.go:34:	commontest "k8s.io/kubernetes/test/e2e/common"
./e2e/v1/e2e.go:35:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/e2e.go:36:	e2elog "k8s.io/kubernetes/test/e2e/framework/log"
./e2e/v1/e2e.go:42:	_ "k8s.io/kubernetes/test/e2e/framework/providers/aws"
./e2e/v1/e2e.go:43:	_ "k8s.io/kubernetes/test/e2e/framework/providers/azure"
./e2e/v1/e2e.go:44:	_ "k8s.io/kubernetes/test/e2e/framework/providers/gce"
./e2e/v1/e2e.go:45:	_ "k8s.io/kubernetes/test/e2e/framework/providers/kubemark"
./e2e/v1/e2e.go:46:	_ "k8s.io/kubernetes/test/e2e/framework/providers/openstack"
./e2e/v1/e2e.go:47:	_ "k8s.io/kubernetes/test/e2e/framework/providers/vsphere"
./e2e/v1/admission_controller.go:27:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1/admission_controller.go:28:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1/full_vpa.go:29:	e2e_common "k8s.io/kubernetes/test/e2e/common"
./e2e/v1/full_vpa.go:30:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/updater.go:33:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/updater.go:34:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1beta2/updater.go:35:	framework_job "k8s.io/kubernetes/test/e2e/framework/job"
./e2e/v1beta2/updater.go:36:	framework_rs "k8s.io/kubernetes/test/e2e/framework/replicaset"
./e2e/v1beta2/updater.go:37:	framework_ss "k8s.io/kubernetes/test/e2e/framework/statefulset"
./e2e/v1beta2/updater.go:38:	testutils "k8s.io/kubernetes/test/utils"
./e2e/v1beta2/autoscaling_utils.go:34:	api "k8s.io/kubernetes/pkg/apis/core"
./e2e/v1beta2/autoscaling_utils.go:35:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/autoscaling_utils.go:36:	"k8s.io/kubernetes/test/e2e/framework/replicaset"
./e2e/v1beta2/autoscaling_utils.go:37:	e2eservice "k8s.io/kubernetes/test/e2e/framework/service"
./e2e/v1beta2/autoscaling_utils.go:38:	testutils "k8s.io/kubernetes/test/utils"
./e2e/v1beta2/autoscaling_utils.go:42:	imageutils "k8s.io/kubernetes/test/utils/image"
./e2e/v1beta2/e2e_test.go:33:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/e2e_test.go:34:	"k8s.io/kubernetes/test/e2e/framework/config"
./e2e/v1beta2/e2e_test.go:35:	"k8s.io/kubernetes/test/e2e/framework/testfiles"
./e2e/v1beta2/e2e_test.go:36:	"k8s.io/kubernetes/test/e2e/framework/viperconfig"
./e2e/v1beta2/e2e_test.go:37:	"k8s.io/kubernetes/test/e2e/generated"
./e2e/v1beta2/e2e_test.go:38:	"k8s.io/kubernetes/test/utils/image"
./e2e/v1beta2/e2e_test.go:41:	_ "k8s.io/kubernetes/test/e2e/apimachinery"
./e2e/v1beta2/e2e_test.go:42:	_ "k8s.io/kubernetes/test/e2e/apps"
./e2e/v1beta2/e2e_test.go:43:	_ "k8s.io/kubernetes/test/e2e/auth"
./e2e/v1beta2/e2e_test.go:44:	_ "k8s.io/kubernetes/test/e2e/autoscaling"
./e2e/v1beta2/e2e_test.go:45:	_ "k8s.io/kubernetes/test/e2e/cloud"
./e2e/v1beta2/e2e_test.go:46:	_ "k8s.io/kubernetes/test/e2e/common"
./e2e/v1beta2/e2e_test.go:47:	_ "k8s.io/kubernetes/test/e2e/instrumentation"
./e2e/v1beta2/e2e_test.go:48:	_ "k8s.io/kubernetes/test/e2e/kubectl"
./e2e/v1beta2/e2e_test.go:49:	_ "k8s.io/kubernetes/test/e2e/lifecycle"
./e2e/v1beta2/e2e_test.go:50:	_ "k8s.io/kubernetes/test/e2e/lifecycle/bootstrap"
./e2e/v1beta2/e2e_test.go:51:	_ "k8s.io/kubernetes/test/e2e/network"
./e2e/v1beta2/e2e_test.go:52:	_ "k8s.io/kubernetes/test/e2e/node"
./e2e/v1beta2/e2e_test.go:53:	_ "k8s.io/kubernetes/test/e2e/scalability"
./e2e/v1beta2/e2e_test.go:54:	_ "k8s.io/kubernetes/test/e2e/scheduling"
./e2e/v1beta2/e2e_test.go:55:	_ "k8s.io/kubernetes/test/e2e/servicecatalog"
./e2e/v1beta2/e2e_test.go:56:	_ "k8s.io/kubernetes/test/e2e/storage"
./e2e/v1beta2/e2e_test.go:57:	_ "k8s.io/kubernetes/test/e2e/storage/external"
./e2e/v1beta2/e2e_test.go:58:	_ "k8s.io/kubernetes/test/e2e/ui"
./e2e/v1beta2/e2e_test.go:59:	_ "k8s.io/kubernetes/test/e2e/windows"
./e2e/v1beta2/recommender.go:32:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/recommender.go:33:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1beta2/common.go:37:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/common.go:38:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1beta2/actuation.go:30:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/actuation.go:31:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1beta2/e2e.go:34:	commontest "k8s.io/kubernetes/test/e2e/common"
./e2e/v1beta2/e2e.go:35:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/e2e.go:36:	e2elog "k8s.io/kubernetes/test/e2e/framework/log"
./e2e/v1beta2/e2e.go:42:	_ "k8s.io/kubernetes/test/e2e/framework/providers/aws"
./e2e/v1beta2/e2e.go:43:	_ "k8s.io/kubernetes/test/e2e/framework/providers/azure"
./e2e/v1beta2/e2e.go:44:	_ "k8s.io/kubernetes/test/e2e/framework/providers/gce"
./e2e/v1beta2/e2e.go:45:	_ "k8s.io/kubernetes/test/e2e/framework/providers/kubemark"
./e2e/v1beta2/e2e.go:46:	_ "k8s.io/kubernetes/test/e2e/framework/providers/openstack"
./e2e/v1beta2/e2e.go:47:	_ "k8s.io/kubernetes/test/e2e/framework/providers/vsphere"
./e2e/v1beta2/admission_controller.go:27:	"k8s.io/kubernetes/test/e2e/framework"
./e2e/v1beta2/admission_controller.go:28:	framework_deployment "k8s.io/kubernetes/test/e2e/framework/deployment"
./e2e/v1beta2/full_vpa.go:29:	e2e_common "k8s.io/kubernetes/test/e2e/common"
./e2e/v1beta2/full_vpa.go:30:	"k8s.io/kubernetes/test/e2e/framework"
./vendor/k8s.io/kubelet/config/v1beta1/types.go:655:	// "k8s.io/kubernetes/pkg/features/kube_features.go".
./vendor/k8s.io/cloud-provider/service/helpers/helper.go:28:This file is duplicated from "k8s.io/kubernetes/pkg/api/v1/service/util.go"
./vendor/k8s.io/cli-runtime/pkg/printers/sourcechecker.go:29:		"k8s.io/kubernetes/pkg/apis/"
```

</p>
</details>

Closes: #2507

### CODE REVIEW

**Comment by wozniakjan** [comment]
cc: @tariq1890, @bskiba

**Comment by bskiba** [comment]
I'm in favor of this change. Thank you for taking time to this for us.

To make it easier for me to review this, can you split the change into 3 commits:
- Vendor directory changes
- go.mod and go.sum changes
- Any changes to the code itself (there's probably not many, but at least the import in utils/metrics changed, right?)

One additional thing that needs changing is the Makefiles, we need to remove the godeps from building. However, I can do it in a followup PR. This one is huge as it is :)
(Example: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/Makefile#L15)

**Comment by bskiba** [comment]
One more thing, I'd rather stick with go 1.12 for now if that's ok.

**Comment by wozniakjan** [comment]
Thanks for a quick feedback. I split out to multiple commits for easier review and added the k8s deps update script - https://github.com/kubernetes/autoscaler/pull/2531/commits/56a1c7a048e7f81d0605d24484acddedbbf59453. With other dependencies, it should be fine using standard `go get -u` command.

> One additional thing that needs changing is the Makefiles, we need to remove the godeps from building. However, I can do it in a followup PR. This one is huge as it is :)

I agree that a followup PR makes sense here if it isn't causing any problems in the interim

**Comment by bskiba** [comment]
This is so good, thank you!
/lgtm
/approve

**Pull request merged**
