### PR TITLE
Decrease the number of GCE Read Requests when node deletion.

### PR DESCRIPTION
**Pull request by jayantjain93**
This change should substantially decrease the number of GCE Read Requests when Node Deletion takes place. As Read Requests take place for each node, for large node cluster this is impact-ful.

### CODE REVIEW

**Comment by jayantjain93** [comment]
Verify CLA

**Comment by jayantjain93** [comment]
Verify CLA

**Comment by jayantjain93** [comment]
@vivekbagade

**Comment by MaciekPytel** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
