### PR TITLE
Update recommended IAM policy

### LINKED ISSUE #6129: README for AWS still mentions autoscaling:DescribeTags
In the release notes for v1.25.0, it says "DescribeAutoScalingGroups [now supports](https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-ec2-auto-scaling-groups-using-tags/) directly including tag filers, which results in less API calls to AWS. Users of the AWS Cloudprovider may want to update their IAM roles to remove the DescribeTags action as this is no longer used".

However, the [README](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#full-cluster-autoscaler-features-policy-recommended) still includes `autoscaling:DescribeTags`.

Is this an oversight? Or is DescribeTags still needed?

### PR DESCRIPTION
**Pull request by mikutas**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

Remove unnecessary permission from README

https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.25.0

#### Which issue(s) this PR fixes:

Fixes #6129

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Mentioned under the  AWS of [Cluster Autoscaler 1.25.0 Chngelog](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.25.0)
> DescribeAutoScalingGroups [now supports](https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-ec2-auto-scaling-groups-using-tags/) directly including tag filers, which results in less API calls to AWS. Users of the AWS Cloudprovider may want to update their IAM roles to remove the DescribeTags action as this is no longer used

/lgtm
Thanks!

**Comment by Shubham82** [comment]
Hi, @drmorr0 @gjtempleton
could you please approve this PR, so that it will be merged

Thanks!

**Comment by gjtempleton** [comment]
Thanks for this
/approve

**Pull request merged**
