### PR TITLE
Rename packet to equinix metal

### PR DESCRIPTION
**Pull request by cprivite**
#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

This PR aims to rename non-code related instances of "Packet" to "Equinix Metal" in order to respect the rename of Packet to Equinix Metal.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cprivite** [comment]
/assign @detiber
/assign @towca 
Pinging @detiber and @towca for approval.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
