### PR TITLE
Fix nil pointer panic in eviction admission

### PR DESCRIPTION
**Pull request by itonyli**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
See https://github.com/kubernetes/autoscaler/issues/6808

#### Which issue(s) this PR fixes:

Fixes #
6808
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by itonyli** [comment]
@voelzmo I closed the previous PR and resubmitted a new one. This PR no longer has a license issue. Could you please help me review it

**Comment by itonyli** [comment]
> Thoughts on adding a quick test [here](https://github.com/kubernetes/autoscaler/blob/76d914b38c62a95029aa2fb01aa78ccd65ef2b48/vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission_test.go#L30) to prevent future regression?
> 
> Thanks!

That's an excellent suggestion! I have already added a unit test to prevent any future regression. Thanks for bringing this up!

**Comment by voelzmo** [comment]
/lgtm

Thanks!

**Review by kwiesmueller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
