### PR TITLE
Add support for json logging format

### PR DESCRIPTION
**Pull request by madufresneelastic**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Add support for structured logging with `--logging-format` that is already supported by many kubernetes components.

#### Which issue(s) this PR fixes:

Fixes #
#5898

#### Does this PR introduce a user-facing change?

```release-note
Add structured logging support via `--logging-format json`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[Other doc]: https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/
```

### CODE REVIEW

**Comment by mwielgus** [comment]
Can you add some documetation/FAQ entry as well?

**Comment by madufresneelastic** [comment]
> Can you add some documetation/FAQ entry as well?

I added an FAQ entry, is this enough or there should be additional documentation somewhere else?

**Comment by mwielgus** [comment]
Please squash the commits to 1 (currently there is 11) and we are good to go.

**Comment by madufresneelastic** [comment]
@mwielgus as discussed, commits are squashed. I just pushed another one (still squashed). I had missed that imports were not sorted properly, this is now fixed.

**Comment by grosser** [comment]
I picked this single commit to get json logging since it's not yet released and it broke `--leader-elect-lease-duration` not sure why

```
5bcb526e0 Kubernetes Prow Robot 3 months ago  (tag: cluster-autoscaler-1.28.0)
2b980eddd Marc-Andre Dufresne 3 months ago add json logging support
go build -o cluster-autoscaler-arm64 --ldflags "-s"
./cluster-autoscaler-arm64 --leader-elect-lease-duration 1s
unknown flag: --leader-elect-lease-duration
```
works before, breaks after 😞

**Pull request merged**
