### PR TITLE
fix(charts): Renaming chart to avoid tag name conflict

### PR DESCRIPTION
**Pull request by sc250024**
# Description

Quick fix after it was discovered that the build triggered on `master` after https://github.com/kubernetes/autoscaler/pull/3341 was merged failed because of the conflicting tags.

Essentially, this renames the folder `charts/cluster-autoscaler` to `charts/cluster-autoscaler-chart` so that, when a Helm chart change is released, it has the separate tag `cluster-autoscaler-chart-1.X.X` to keep releases separate.

# IMPORTANT

**_Please make sure that the `gh-pages` branch exists before merging this!_**. Here are the commands for someone with write access:

```shell
$ git checkout --orphan gh-pages
$ git rm -rf .
$ git add index.html
$ git commit -m "Initial commit"
$ git push origin gh-pages
```

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Autoscaler Helm Charts</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>

  <body>
    <h1>Autoscaler Helm Charts</h1>
    <p>Use the following commands to install the Autoscaler Helm repository:</p>
    <pre>helm repo add autoscaler https://kubernetes.github.io/autoscaler
helm repo update</pre>
    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>
```

</details>

# Testing

To make sure this worked, I merged this PR's branch on my fork https://github.com/sc250024/autoscaler into the `master` branch.

Here are the results:

- Release created by the chart releasing tool: https://github.com/sc250024/autoscaler/releases/tag/cluster-autoscaler-chart-1.0.0
- Helm repository hosted page on the `gh-pages` branch: https://sc250024.github.io/autoscaler/
- Helm chart `index.yaml` created by the release action: https://github.com/sc250024/autoscaler/commit/2b936eec5266470dbb37f91324b9c39d739efb30
- Successful workflow of the GitHub Action: https://github.com/sc250024/autoscaler/runs/932897486

# Testing - Helm repo

To continue from above, the Helm repo on my fork works successfully as follows:

```shell
$ helm repo add autoscaler https://sc250024.github.io/autoscaler
"autoscaler" has been added to your repositories

$ helm repo update

Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "autoscaler" chart repository
...
Update Complete. ⎈ Happy Helming!⎈

$ helm search repo autoscaler

NAME                                    CHART VERSION   APP VERSION DESCRIPTION
autoscaler/cluster-autoscaler-chart     1.0.0           1.18.1      Scales Kubernetes worker nodes within autoscali...

$ helm template autoscaler/cluster-autoscaler-chart

<see yaml below>
```

<details>
<summary>rendered.yaml</summary>

```yaml
---
# Source: cluster-autoscaler-chart/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-chart-1.0.0"
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "RELEASE-NAME"
      app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
  
  maxUnavailable: 1
---
# Source: cluster-autoscaler-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-chart-1.0.0"
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
---
# Source: cluster-autoscaler-chart/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-chart-1.0.0"
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - endpoints
    verbs:
      - create
      - patch
  - apiGroups:
    - ""
    resources:
    - pods/eviction
    verbs:
    - create
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    resourceNames:
      - cluster-autoscaler
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
    - watch
    - list
    - get
    - update
  - apiGroups:
    - ""
    resources:
      - pods
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - watch
      - list
      - get
  - apiGroups:
    - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - watch
      - list
      - get
  - apiGroups:
    - batch
    - extensions
    resources:
    - jobs
    verbs:
    - get
    - list
    - patch
    - watch
  - apiGroups:
      - extensions
    resources:
      - replicasets
      - daemonsets
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - watch
      - list
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    - csinodes
    verbs:
    - watch
    - list
    - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
  - apiGroups:
    - coordination.k8s.io
    resourceNames:
    - cluster-autoscaler
    resources:
    - leases
    verbs:
    - get
    - update
---
# Source: cluster-autoscaler-chart/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-chart-1.0.0"
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-aws-cluster-autoscaler-chart
    namespace: default
---
# Source: cluster-autoscaler-chart/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-chart-1.0.0"
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-autoscaler-status
    verbs:
      - delete
      - get
      - update
---
# Source: cluster-autoscaler-chart/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-chart-1.0.0"
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-aws-cluster-autoscaler-chart
    namespace: default
---
# Source: cluster-autoscaler-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-chart-1.0.0"
  name: RELEASE-NAME-aws-cluster-autoscaler-chart
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      name: http
  selector:
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/name: "aws-cluster-autoscaler-chart"
  type: "ClusterIP"

```

</details>

### CODE REVIEW

**Comment by gjtempleton** [comment]
/hold
Stick the hold on until the gh-pages branch exists
/lgtm

**Comment by sc250024** [comment]
@gjtempleton Your `lgtm` was undone by this commit: https://github.com/sc250024/autoscaler/blob/fix-ChartNameConflict/.github/workflows/pr.yaml#L14-L15

I made the file change detection more general, that's all. Sorry for the chaos!

**Comment by gjtempleton** [comment]
No worries! Still
/lgtm

**Comment by sc250024** [comment]
@MaciekPytel Did you create the `gh-pages` branch? If not, could you do that please before this is merged?

**Comment by gjtempleton** [comment]
`gh-pages` branch now exists thanks to Maciek - we've left the `index.html` blank for now though.

/unhold

**Comment by gjtempleton** [comment]
Still failing due to the action trying to push to a protected branch.

The `kubernetes/dashboard` repo resolves this by following a slightly different workflow: https://github.com/kubernetes/dashboard/pull/5311

However we'll also need to create an OWNERS file in the gh-pages branch if we want to follow this workflow to allow approval of the PRs raised by the bot.

This would result in the following process for any changes:

```
User raises PR to update the chart
PR gains required approvals and is merged
Github actions fire off and generate new index.yaml on branch, raises PR against gh-pages
Bot raised PR to gh-pages gains required approvals and is merged
```

**Comment by gjtempleton** [comment]
CC @sc250024 Any opinion on the above? It's a bit unwieldy but feels like the best solution to me given that it 

a) matches the workflow of another repo in the kubernetes org and 
b) doesn't mean removing branch protection

**Comment by damemi** [comment]
@gjtempleton I have another question about your proposed flow in https://github.com/kubernetes/autoscaler/pull/3393#issuecomment-668081392, opening a PR still requires a new branch so won't you hit the same branch protection problem trying to do that? I was assuming that all branches in the k8s org need branch protection, so as it was pointed out in https://github.com/helm/chart-releaser-action/issues/33#issuecomment-671102802 using the PR flow still might not work that way. Have you hit that too or does it work?

**Comment by gjtempleton** [comment]
I _believe_ the protection only hits once the branch has been initially created after a push, so after the first commit is pushed up then further commits can't be pushed up to the new branch. Then it becomes an issue (amongst others) of ensuring the created branch is always cleaned up post merging.

This seems to be the case in the `kubernetes/dashboard` repo's workflow: https://github.com/kubernetes/dashboard/runs/872876193?check_suite_focus=true

**Comment by damemi** [comment]
Would it be possible to make the action generate a "tagged" branch to open the PR with a variable name somehow? So you don't have to always push to the same branch, it could push to `pr-branch-1.19`, `pr-branch-1.20`, etc. Not the best but another thought

**Comment by llamahunter** [comment]
I think this change should be reverted, and you should not restart your version numbering scheme just because the chart changed repos.  Use 9.0.0+ so that there isn't a tag collision.

**Comment by sc250024** [comment]
> I think this change should be reverted, and you should not restart your version numbering scheme just because the chart changed repos. Use 9.0.0+ so that there isn't a tag collision.

@llamahunter I did the change to avoid a problem _at the time_. In retrospect, it wasn't the right decision to make, but it made sense given the restrictions.

This comment (https://github.com/kubernetes/autoscaler/issues/3318#issuecomment-684850684) shows that the problem with the `chart-release` action has now been fixed.

**Pull request merged**
