### PR TITLE
Do not run as root by default in Docker

### LINKED ISSUE #1972: Do not run as root by default in Docker
IMHO it is accepted as best practice to not run [processes in containers as root](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b). I'm not sure if this was discussed before or if root permissions are in fact needed for the scalers to work, but it would be nice if we could change this.

### PR DESCRIPTION
**Pull request by der-eismann**
Fixes #1972
Not sure if you prefer `nobody` or something else, just let me know.

### CODE REVIEW

**Comment by bskiba** [comment]
/lgtm 
/assign @MaciekPytel 
Maciek, please approve if this looks good to you.

**Comment by losipiuk** [comment]
@der-eismann we will be migrating to distroless (https://github.com/GoogleContainerTools/distroless) soon. Given that I am not sure if this change is really beneficial. WDYT?

**Comment by mwielgus** [comment]
No activity, closing. Please reopen once you decide to merge it.

**Pull request closed without merging**
