### PR TITLE
added cce backup

### PR DESCRIPTION
**Pull request by wangshiqi308**
#### Which component this PR applies to?
cluster-autoscaler

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
1. Added CCE version CA to servicestage folder.
2. Added CCE related Huaweicloud SDK
#### Which issue(s) this PR fixes:

N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mwielgus** [comment]
@kevin-wangzefeng @RainbowMango Friendly ping, this PR requires your review to be merged.

**Comment by RainbowMango** [comment]
@mwielgus Thanks.  I and @wangshiqi308 talked about this PR before, he said he will re-consider this PR.

@wangshiqi308 Do you think this is still needed? If not, we can close it. You can re-open it at any time if you want it again.

**Comment by mwielgus** [comment]
Closing due to inactivity.

**Pull request closed without merging**
