### PR TITLE
[CA-1.17] CAPI backports for autoscaling workload clusters

### PR DESCRIPTION
**Pull request by benmoss**
Backports the recent work @detiber did to enable running the autoscaler against a different cluster than the one it is running in.

Brought in some other commits that seemed important and made the backporting process easier too.

cc @elmiko

### CODE REVIEW

**Comment by benmoss** [comment]
```
$ git -C /tmp/ca-update-vendor.Idfl/kubernetes/ rev-parse HEAD
79569e22b50897990a483a35c33a2b0e43b80138

$ diff -q vendor/k8s.io/client-go/discovery/cached/memory/ /tmp/ca-update-vendor.Idfl/kubernetes/vendor/k8s.io/client-go/discovery/cached/memory/
Only in /tmp/ca-update-vendor.Idfl/kubernetes/vendor/k8s.io/client-go/discovery/cached/memory/: memcache_test.go

$ diff -q vendor/k8s.io/client-go/restmapper /tmp/ca-update-vendor.Idfl/kubernetes/staging/src/k8s.io/client-go/restmapper
Only in /tmp/ca-update-vendor.Idfl/kubernetes/staging/src/k8s.io/client-go/restmapper: category_expansion_test.go
Only in /tmp/ca-update-vendor.Idfl/kubernetes/staging/src/k8s.io/client-go/restmapper: discovery_test.go
Only in /tmp/ca-update-vendor.Idfl/kubernetes/staging/src/k8s.io/client-go/restmapper: shortcut_test.go

$ diff -q vendor/k8s.io/client-go/scale/fake/ /tmp/ca-update-vendor.Idfl/kubernetes/staging/src/k8s.io/client-go/scale/fake/
```

what a fun process 😸

**Comment by elmiko** [comment]
if i'm reading the owners file properly, seems like we might need to get one of @piosz @aleksandra-malinowska or @losipiuk to approve this
/lgtm

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
