### PR TITLE
Integrate Civo as a cloud provider

### PR DESCRIPTION
**Pull request by vishalanarase**
Hello Kubernetes Community,

#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

We are the Civo Kubernetes Team: @vishalanarase, @birdiesanders, and @RealHarshThakur. We worked during the past month to implement a Node Autoscaler for Civo Kubernetes software as a cloud provider, and we're sending it here for broader community use.

It has the basic support you would expect, like increasing and decreasing node groups.

We're here if you have any questions!

### CODE REVIEW

**Comment by mwielgus** [comment]
Please sign the CLA. Without the CLA we won't review the PR.

**Comment by vishalanarase** [comment]
@mwielgus Can you please take a look now?

**Comment by vishalanarase** [comment]
@mwielgus can you please take a look?

**Comment by vishalanarase** [comment]
@mwielgus @feiskyer @aleksandra-malinowska Can you please review?

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
