### PR TITLE
Stop treating masters differently in scale down

### PR DESCRIPTION
**Pull request by x13n**
#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind bug
/kind cleanup

#### What this PR does / why we need it:

This filtering was used for two purposes:
- Excluding masters from destination candidates
- Excluding masters from calculating cluster resources

Excluding from destination candidates isn't useful: if pods can schedule
there, they will, so removing them from CA simulation doesn't change
anything.
Excluding from calculating cluster resources actually matches scale up
behavior, where master nodes are treated the same way as regular nodes.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5131. Only the last commit should be reviewed as a part of this PR. It will be on hold until the previous one is merged.

/hold

#### Does this PR introduce a user-facing change?

```release-note
Nodes hosting kube-apiserver are no longer treated differently in scale-down logic. The special handling was removed after it was discovered scale down resource limiting was inconsistent with scale-up and haven't actually worked correctly since CA 1.18.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @MaciekPytel
/assign @yaroslava-serdiuk

### CODE REVIEW

**Comment by yaroslava-serdiuk** [comment]
> Excluding from calculating cluster resources actually matches scale up
behavior, where master nodes are treated the same way as regular nodes.

CA don't want to scale down a master node, why do we want to include a master node in scale down candidates?

**Comment by x13n** [comment]
The thing is, master nodes were always included in scale down candidates: the filtering happened for destination candidates, which made little sense.

**Comment by MaciekPytel** [comment]
I agree filtering masters from candidate nodes makes no sense, but I think the fact that they're only filtered out from candidate list is a bug. As far as I can tell it was introduced in #2890 (specifically [here](https://github.com/kubernetes/autoscaler/pull/2890/files#diff-a8bcd21686c03aba976761ae055fd3b70e6e2bf5ee77d15f66946f3b0f1d7c30L781) - before that change the loop selecting node to delete would skip master nodes).

With above in mind - I fully agree with not filtering masters from destinations and I also agree resource limits should be treated consistently across scale-up and scale-down. The question is whether we should start filtering out the masters from candidate lists like we did before #2890? The fact that it has been broken since 1.18 and no-one noticed, suggests that we may be fine getting rid of this logic.

I'd consider updating the release note though to give slightly more context on this issue - it wouldn't be immediately obvious to me what you mean by cluster resources there and I'm probably somewhat more familiar with CA than the target audience of the release notes. Maybe something along the lines of `Nodes hosting kube-apiserver are no longer treated differently in scale-down logic. The special handling was removed after it was discovered it haven't worked correctly since CA 1.18.`? This doesn't require much context and anyone interested in details can just follow the link to this PR.

**Comment by x13n** [comment]
The logic to filter out masters was introduced long before that, in https://github.com/kubernetes/autoscaler/pull/331. It was meant to exclude masters from calculating resource limits. Before creating this PR I chatted with @aleksandra-malinowska who authored https://github.com/kubernetes/autoscaler/pull/331 all these years ago and we concluded it is safe to remove the filtering as it is not consistent between scaling up and down. I agree the release note could be improved though - updated.

/hold cancel

**Pull request merged**
