### PR TITLE
Update CA godeps to Kubernetes v1.15.0-alpha.0

### PR DESCRIPTION
**Pull request by feiskyer**
Update CA godeps to Kubernetes v1.15.0-alpha.0, and also change some Go libraries to their new versions.

Refer https://github.com/kubernetes/autoscaler/pull/1446#issuecomment-465564053.

/assign @losipiuk

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
/lgtm
/approve

Thanks! Really appreciate the contribution here, updating Godeps is a pain. 

I've branched `cluster-autoscaler-release-1.14` before merging this, as we should probably update Godeps there to Kubernetes 1.14 branch closer to the release (tracked in #1710).

**Comment by mwielgus** [comment]
Just out of curiosity. Why do we need it 1.15 deps right now?

**Comment by aleksandra-malinowska** [comment]
It's just sync to master, as far as I understand. We haven't done it in a while, so cloud providers' SDKs are quite stale.

**Comment by feiskyer** [comment]
Yep, sync to master. Before this, kubernetes v1.12 is used in master branch, which is really old.

**Comment by losipiuk** [comment]
Thanks a lot @feiskyer !

**Pull request merged**
