### PR TITLE
Add DeepCopy generation for runtime.Objects within ClusterAPI provider

### PR DESCRIPTION
**Pull request by JoelSpeed**
When we introduced the ClusterAPI provided, we have a manually crafted deepcopy gen taken from some similar types and then cut down to fit the minimal types that we have in the ClusterAPI provider.

This PR add a generation script that can be run either as `./hack/update-generated-deepcopies.sh` or via `make generate` to update the generated deepcopy files.

Now if we make any changes to those types, we can keep the deepcopy code up to date

### CODE REVIEW

**Comment by detiber** [comment]
@joelsmith what is your priority for these changes? One of the things I'm toying with as I'm working on fixing the outstanding issues with https://github.com/kubernetes/autoscaler/pull/3203 is to remove the use of the built-in types in favor of just using unstructured access to make it easier to conditionally consume fields that are available in newer api types but not older api types (spec.clusterName for example).

**Comment by JoelSpeed** [comment]
Not the highest priority tbh, was just some tech debt that I was aware of that we had been meaning to fix

> to make it easier to conditionally consume fields that are available in newer api types but not older api types

How does being unstructured make it easier to do this? If we need to handle newer fields, we can add those to the internal types with an `omitempty` and then check if they are set no? With unstructured you'd have to first check if the field was there, and then check if it has a value? Is there some nuance I've missed?

As far as I was aware, we had no plan to make that a public API so we can chop and change it as much as we need right?

**Comment by detiber** [comment]
> How does being unstructured make it easier to do this? If we need to handle newer fields, we can add those to the internal types with an omitempty and then check if they are set no? With unstructured you'd have to first check if the field was there, and then check if it has a value? Is there some nuance I've missed?

Yes, but it's probably a bit more nuanced than that, since we would also potentially have to add in some level of defaulting and conversion to the process of converting unstructured to the internal types.

> As far as I was aware, we had no plan to make that a public API so we can chop and change it as much as we need right?

Yes, that is always an option, but I also believe that having internal types that do not necessarily reflect the external types we are interacting with adds a bit of obfuscation, in particular when we are dealing with changes between supported versions of Cluster API. I think the logic becomes quite a bit more clear related to the why and the how we are handling the support for multiple versions when it is handled at the point of use rather than trying to abstract it away behind internal types and conversions.

I also think there is another benefit related to moving towards unstructured directly in that we can unify a lot of the implementation that is currently separate but identical.

I still need to wrap up a few bits, which I should be able to wrap it up in the next couple of days, but I think seeing an example would help clarify what I'm thinking a bit more.

**Comment by JoelSpeed** [comment]
> I still need to wrap up a few bits, which I should be able to wrap it up in the next couple of days, but I think seeing an example would help clarify what I'm thinking a bit more.

Sounds good, happy to hold this for now while we decide on this, if you could ping me when you have an example, I'd be interested to see it

**Comment by JoelSpeed** [comment]
This won't be needed once #3312 is merged, so closing

**Pull request closed without merging**
