### PR TITLE
Re-sort on root level, add `hostNetwork` parameter

### PR DESCRIPTION
**Pull request by m99coder**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds the ability to configure the `hostNetwork` setting.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Some context about `hostNetwork` is taken from here: https://alesnosek.com/blog/2017/02/14/accessing-kubernetes-pods-from-outside-of-the-cluster/

#### Does this PR introduce a user-facing change?

```release-note
Adds `hostNetwork` parameter
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gjtempleton** [comment]
Thanks for the PR, the `README.md` is generated by helm-docs from the `README.md.gotmpl`, which is one of our [pre-commit hooks](https://github.com/kubernetes/autoscaler/tree/master/charts#pre-commit-hooks), if you're wanting to make changes to the README other than those in the values file, you'll need to make changes there. That's what's causing the PR to fail checks currently.

Happy to review once that's fixed up.

**Comment by m99coder** [comment]
@gjtempleton Tried to make the “Lint and Test Charts / Helm Docs” action pass, but failed. I don’t understand why `git diff --quiet charts/*/README.md` yields a change when the changeset doesn’t include any of them. I just committed changes to `README.md.gotmpl` now as you proposed.

**Comment by gjtempleton** [comment]
It needs to have the changes to both the `.gotmpl` and `.md` files committed. The pre-commit hook should ensure this happens and will fail commits touching the `.gotmpl`, or other files whose values it consumes but not adding changes to the `README.md`: https://github.com/kubernetes/autoscaler/blob/b516e808c65b5f5ec9357daea745859c31fd25b9/.pre-commit-config.yaml#L11-L15

**Comment by m99coder** [comment]
😢 Failed again

**Comment by gjtempleton** [comment]
If you install helm-docs with [these instructions](https://github.com/norwoodj/helm-docs#installation) and run `helm-docs` in the `charts` directory, you'll see that it's still generating changes, hence the CI pipeline failing.

**Comment by m99coder** [comment]
@gjtempleton Running `helm-docs` and committing this result worked like a charm. Thanks for the hint.

**Comment by gjtempleton** [comment]
/assign @gjtempleton
Thanks for that. 
Just one last request, can you squash your changes down to one or two commits to make the commit history a bit easier to parse? Thanks!

**Comment by gjtempleton** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
