### PR TITLE
Merge pull request #5890 from Bryce-Soghigian/bsoghigian/respecting-bulk-delete

### PR DESCRIPTION
**Pull request by Bryce-Soghigian**
…ulk-delete

fix: setting maxEmptyBulkDelete, and maxScaleDownParallelism to be the same value

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
/retitle Merge pull request #5890 from Bryce-Soghigian/bsoghigian/respecting-bulk-delete

**Comment by Shubham82** [comment]
Thanks @Bryce-Soghigian
/lgtm

**Review by feiskyer — COMMENTED** [review]
LGTM. thanks for cherry-picking.

**Pull request merged**
