### PR TITLE
Define clusterapi in cloudprovider layer

### PR DESCRIPTION
**Pull request by jichenjc**
fixs: #3814

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by mwielgus** [comment]
Something seems to be missing
```
cloudprovider/builder/builder_all.go:53:2: undefined: clusterapi.ProviderName
cloudprovider/builder/builder_all.go:86:7: undefined: clusterapi.ProviderName
```

**Comment by jichenjc** [comment]
my bad, search the variable in narrow folder, hopefully the update should fix it

**Review by elmiko — APPROVED** [review]
thanks for the pr @jichenjc !
/lgtm

**Pull request merged**
