### PR TITLE
fix fmt errorf and typo

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
fix some typo and error print
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks @googs1025
/lgtm

**Comment by googs1025** [comment]
@krzysied @jbartosik /PTAL thanks a lot!

**Comment by googs1025** [comment]
@kwiesmueller Can you help me review this PR? thanks a lot

**Pull request merged**
