### PR TITLE
update cluster-autoscaler chart to 1.21.0

### PR DESCRIPTION
**Pull request by mweibel**

### CODE REVIEW

**Comment by gjtempleton** [comment]
Hey, thanks for the PR!

Can you please make the chart version bump a minor version bump rather than a patch version bump? It matches what we've done with [past PRs to bump the default image](https://github.com/kubernetes/autoscaler/pull/3880) and flags it as a larger change to users who are potentially using the default image tag.

**Comment by mweibel** [comment]
sure, done :)

**Comment by gjtempleton** [comment]
Brilliant, thanks again!
/lgtm
/approve

**Pull request merged**
