### PR TITLE
Fixes for update-vendor.sh on OSX and zsh

### PR DESCRIPTION
**Pull request by avorima**
The update-vendor.sh script needed some fixes to work with zsh on OSX.

Various binaries are expected to be GNU utils, which are not installed by default on OSX. I've added suggestions to install ported binaries using homebrew if they are not found in PATH.

Skip `shopt -s lastpipe` when `$BASH` is not defined.

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by towca** [comment]
#3702 should fix the flaky test for good, but for this PR a retest should be enough.

/ok-to-test

**Comment by avorima** [comment]
Thank you @towca 

/retest

**Comment by towca** [comment]
I don't think you can restart Travis this way. Could you do a `git commit --amend --no-edit`? I think this'll trigger another build.

**Pull request merged**
