### PR TITLE
Add huaweicloud to list of supported cloud providers

### PR DESCRIPTION
**Pull request by ysy2020**
Huawei Cloud Container Engine (CCE) provides highly scalable, high-performance, enterprise-class Kubernetes clusters and supports Docker containers. With CCE, you can easily deploy, manage, and scale containerized applications on HUAWEI CLOUD.

This PR adds Huawei Cloud Provider to support cluster autoscaler for Huawei CCE.

### CODE REVIEW

**Comment by ysy2020** [comment]
@MaciekPytel @Jeffwan 

I've fixed the errors you mentioned about in #3099 and #3339 . Please let me know if there's anything else that I need to do. Thank you!

**Comment by MaciekPytel** [comment]
I'm ok to merge it once it passes travis-ci test.

**Comment by ysy2020** [comment]
Do I need to do anything to pass this test?

**Comment by MaciekPytel** [comment]
It should trigger for this PR automatically. Not sure why it haven't triggered just yet, I'm going to close & reopen which should trigger it again.
In the meantime - here is an example run that failed on unrelated PR due to issues in huawei provider: https://travis-ci.org/github/kubernetes/autoscaler/jobs/710194248. In general you need to make sure that both hack/verify-all.sh and unittests pass.

**Comment by MaciekPytel** [comment]
https://travis-ci.org/github/kubernetes/autoscaler/builds/710429681 is the build for this PR.

**Comment by ysy2020** [comment]
@MaciekPytel 

I saw that travis-ci test automatically disappeared even though I changed nothing. Does it mean I have passed the tests?

**Comment by ysy2020** [comment]
@MaciekPytel 

Can I know if I'm doing something wrong that causes "cla/linuxfoundation" not pass?

**Comment by ysy2020** [comment]
@MaciekPytel 

Is there anything else that I need to do?

**Comment by ysy2020** [comment]
@MaciekPytel  Any comments? Please let me know if there's anything that I need to do. Thank you!

**Comment by ysy2020** [comment]
@MaciekPytel @Jeffwan @feiskyer 

Any comments?

**Pull request merged**
