### PR TITLE
Support scaling down a particular node with graceful termination

### LINKED ISSUE #5109: Support explicitly tagging a node for safe eviction and removal
**Which component are you using?**:
cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Periodically, we encounter nodes in our Kubernetes clusters that have become non-functional for some reason specific to the cloud provider.   Our typical solution to that problem is to replace the node, usually by marking it unusable and allowing the cluster-autoscaler to replace it.

Today, the easiest way to do this is to mark the node with a NoExecute taint.   That will drive the node to empty via taint-based eviction.

But that 'eviction' is harsh.  It does not respect PodDisruptionBudgets or safely evict the pods as the auto-scaler itself would if it identified a node as a candidate for down-scale, independently.

**Describe the solution you'd like.**:

The autoscaler should recognize a new label:

cluster-autoscaler.kubernetes.io/scale-down-requested-with-eviction=(gracefulEvictionTimeoutSeconds)

The auto-scaler should 
1. Immediately include the node, when detected into the scale-down candidate set, storing the deadline by which the eviction should take place.  EvictionDeadline=<now>+<gracefulEvictionTimeoutSeconds>.
2. Begin a graceful eviction attempt of all the pods on the node
3. If the pods have not been fully evicted by the eviction deadline, force delete all the pods on the node.
4. Remove the node.

**Describe any alternative solutions you've considered.**:

**Additional context.**:

### PR DESCRIPTION
**Pull request by liuxintong**
#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR introduces a new feature to support scaling down a particular node. As described in #5109, some nodes could become non-functional for some reason specific to the cloud provider. With this change, users can tag a node explicitly by running `kubectl annotate node <nodename> cluster-autoscaler.kubernetes.io/scale-down-requested=true`. Cluster-Autoscaler will perform all required safe checks, evict hosted pods and delete the node.

This PR also introduces the feature to scale up the cluster if the current node group size is smaller than the configured min size. This feature is disabled by default, and users need to pass in the bool flag `scale-up-to-meet-node-group-min-size-enabled` to enable it.

The first feature is slightly depend on the second feature. For example, the min size of a node group is 3, and it has exactly 3 nodes at this moment. If we tag a node to scale down, it wouldn't work because the node group is already at the min size, and the cluster could only be scaled up if it has unschedulable pods to help. Therefore, we need this change to take the `scale-down-requested` annotation into account and scale up the node group a bit if it's needed.

#### Which issue(s) this PR fixes:

Fixes #5109

#### Special notes for your reviewer:

Besides unit tests, this PR has been fully validated in an Azure K8s cluster. I will share more details about my experiments in a separate comment of this PR.

#### Does this PR introduce a user-facing change?

```release-note
Support scaling down a particular node if it has `cluster-autoscaler.kubernetes.io/scale-down-requested=true` annotation.
Support scaling up the cluster if the current node group size is smaller than the configured min size (disabled by default).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [FAQ How can I request Clsuter Autoscaler to scale down a particular node?]: https://github.com/liuxintong/autoscaler/blob/7fe865bc03b2e9feab9254227744da97049716fb/cluster-autoscaler/FAQ.md#how-can-i-request-clsuter-autoscaler-to-scale-down-a-particular-node
- [FAQ My cluster is below minimum / above maximum number of nodes, but CA did not fix that! Why?]: https://github.com/liuxintong/autoscaler/blob/7fe865bc03b2e9feab9254227744da97049716fb/cluster-autoscaler/FAQ.md#my-cluster-is-below-minimum--above-maximum-number-of-nodes-but-ca-did-not-fix-that-why
- [FAQ What are the parameters to CA?]: https://github.com/liuxintong/autoscaler/blob/7fe865bc03b2e9feab9254227744da97049716fb/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca
```

### CODE REVIEW

**Comment by liuxintong** [comment]
All changes in this PR have been verified in the following AKS cluster `xint-t0910-aks`. This cluster has 1 node group `agentpool`, and the underlying group name in the cloud provider side is `aks-agentpool-22992539-vmss00001o`.

```
(base) ➜  ~ kubectl get nodes -o wide
NAME                                STATUS   ROLES   AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-agentpool-22992539-vmss00001o   Ready    agent   138m   v1.24.3   10.224.0.5    <none>        Ubuntu 18.04.6 LTS   5.4.0-1089-azure   containerd://1.6.4+azure-4
aks-agentpool-22992539-vmss00001t   Ready    agent   71m    v1.24.3   10.224.0.6    <none>        Ubuntu 18.04.6 LTS   5.4.0-1089-azure   containerd://1.6.4+azure-4
aks-agentpool-22992539-vmss00001w   Ready    agent   48m    v1.24.3   10.224.0.9    <none>        Ubuntu 18.04.6 LTS   5.4.0-1089-azure   containerd://1.6.4+azure-4
```

The autoscaler in AKS side was turned off intentionally, and a test `cluster-autoscaler` container image was generated with `Dockerfile.amd64`, uploaded to Azure Container Registry `xintcr` and deployed to `kube-system` namespace via the following command.

```
(base) ➜  cluster-autoscaler git:(0912-ca-exp) ✗ make container-arch-amd64 && docker push xintcr.azurecr.io/cluster-autoscaler-amd64:dev0911 && kubectl apply -f cloudprovider/azure/examples/cluster-autoscaler-vmss-control-plane-xint.yaml
```

By the way, here was the main container image spec define in `cluster-autoscaler-vmss-control-plane-xint.yaml`. The node group min size was 3, and the max size was 10. The new feature `--scale-up-to-meet-node-group-min-size-enabled` was enabled.

```
      containers:
        - image: xintcr.azurecr.io/cluster-autoscaler-amd64:dev0911
          imagePullPolicy: Always
          name: cluster-autoscaler
          command:
            - ./cluster-autoscaler
            - --v=5
            - --logtostderr=true
            - --cloud-provider=azure
            - --skip-nodes-with-local-storage=false
            - --nodes=3:10:aks-agentpool-22992539-vmss
            - --scale-up-to-meet-node-group-min-size-enabled
```

Once the `cluster-autoscaler` test instance was running in the cluster, the node `aks-agentpool-22992539-vmss00001o` was annotated with `scale-down-requested` via `kubectl`.

```
(base) ➜  ~ kubectl annotate node aks-agentpool-22992539-vmss00001o cluster-autoscaler.kubernetes.io/scale-down-requested=true
```

The next step was checking the container logs periodically. In the first round, the node group was scaled up from 3 to 4, although it has no unschedulable pods. This is by design, because we need a new surging node to scale down the tagged node.

```
I0912 19:52:17.182221       1 static_autoscaler.go:445] No unschedulable pods

I0912 19:52:17.182290       1 scale_up.go:669] ScaleUpToMeetNodeGroupMinSize: increased desired min size as node aks-agentpool-22992539-vmss00001o has scale-down-requested annotation
I0912 19:52:17.182390       1 scale_up.go:679] ScaleUpToMeetNodeGroupMinSize: NodeGroup aks-agentpool-22992539-vmss: TargetSize 3, DesiredMinSize 4, MinSize 3, MaxSize 10
I0912 19:52:17.182395       1 scale_up.go:698] ScaleUpToMeetNodeGroupMinSize: final scale-up plan: [{aks-agentpool-22992539-vmss 3->4 (max: 10)}]

```

In the second round, the node with `scale-down-requested` annotation was included in the scale down candidates. However, the scale down didn't perform, because `scaleDownInCooldown` is `true`, which means the cluster could only be scaled down after the period of `scale-down-delay-after-add` (the default value is 10 minutes).

```
I0912 19:52:29.070169       1 scale_up.go:669] ScaleUpToMeetNodeGroupMinSize: increased desired min size as node aks-agentpool-22992539-vmss00001o has scale-down-requested annotation
I0912 19:52:29.070289       1 scale_up.go:679] ScaleUpToMeetNodeGroupMinSize: NodeGroup aks-agentpool-22992539-vmss: TargetSize 4, DesiredMinSize 4, MinSize 3, MaxSize 10
I0912 19:52:29.070294       1 scale_up.go:694] ScaleUpToMeetNodeGroupMinSize: scale up not needed

I0912 19:52:29.070312       1 static_autoscaler.go:515] Calculating unneeded nodes
I0912 19:52:29.070368       1 pre_filtering_processor.go:64] GetScaleDownCandidates: adding aks-agentpool-22992539-vmss00001o as it has scale-down-requested annotation

I0912 19:52:29.070487       1 legacy.go:379] Node aks-agentpool-22992539-vmss00001o is requested to be scaled down
I0912 19:52:29.070682       1 legacy.go:452] Finding additional 3 candidates for scale down.
I0912 19:52:29.070696       1 cluster.go:160] aks-agentpool-22992539-vmss00001o for removal
I0912 19:52:29.070764       1 cluster.go:247] Looking for place for kube-system/konnectivity-agent-59c5567b84-5bw8v
I0912 19:52:29.070829       1 cluster.go:266] Pod kube-system/konnectivity-agent-59c5567b84-5bw8v can be moved to aks-agentpool-22992539-vmss00001t
I0912 19:52:29.070850       1 cluster.go:247] Looking for place for kube-system/coredns-6856d58c9d-9cs68
I0912 19:52:29.070909       1 cluster.go:266] Pod kube-system/coredns-6856d58c9d-9cs68 can be moved to aks-agentpool-22992539-vmss00001w
I0912 19:52:29.070926       1 cluster.go:247] Looking for place for kube-system/metrics-server-69559866b8-cjjlx
I0912 19:52:29.070981       1 cluster.go:266] Pod kube-system/metrics-server-69559866b8-cjjlx can be moved to aks-agentpool-22992539-vmss00001t
I0912 19:52:29.070996       1 cluster.go:182] node aks-agentpool-22992539-vmss00001o may be removed

I0912 19:52:29.071583       1 legacy.go:517] aks-agentpool-22992539-vmss00001o is unneeded since 2022-09-12 19:52:29.014669634 +0000 UTC m=+1126.492898830 duration 0s
I0912 19:52:29.071600       1 legacy.go:517] aks-agentpool-22992539-vmss00001t is unneeded since 2022-09-12 19:52:29.014669634 +0000 UTC m=+1126.492898830 duration 0s
I0912 19:52:29.071609       1 legacy.go:517] aks-agentpool-22992539-vmss00001w is unneeded since 2022-09-12 19:52:29.014669634 +0000 UTC m=+1126.492898830 duration 0s
I0912 19:52:29.071629       1 static_autoscaler.go:558] Scale down status: lastScaleUpTime=2022-09-12 19:52:17.181240736 +0000 UTC m=+1114.659469832 lastScaleDownDeleteTime=2022-09-12 19:44:15.051545164 +0000 UTC m=+632.529774260 lastScaleDownFailTime=2022-09-12 18:34:02.514967734 +0000 UTC m=-3580.006803070 scaleDownForbidden=false scaleDownInCooldown=true

```

In the next round after the scale down cooldown period, the node `aks-agentpool-22992539-vmss00001o` was being removed as expected. The cluster had more than 1 candidate, but the node with `scale-down-requested` has higher priority to be scaled down.

```
I0912 20:02:21.629980       1 legacy.go:517] aks-agentpool-22992539-vmss00001x is unneeded since 2022-09-12 19:59:40.871272841 +0000 UTC m=+1558.349501937 duration 2m40.75584183s
I0912 20:02:21.629990       1 legacy.go:517] aks-agentpool-22992539-vmss00001o is unneeded since 2022-09-12 19:52:29.014669634 +0000 UTC m=+1126.492898830 duration 9m52.612444937s
I0912 20:02:21.630000       1 legacy.go:517] aks-agentpool-22992539-vmss00001t is unneeded since 2022-09-12 19:59:40.871272841 +0000 UTC m=+1558.349501937 duration 2m40.75584183s
I0912 20:02:21.630015       1 legacy.go:517] aks-agentpool-22992539-vmss00001w is unneeded since 2022-09-12 19:59:40.871272841 +0000 UTC m=+1558.349501937 duration 2m40.75584183s
I0912 20:02:21.630036       1 static_autoscaler.go:558] Scale down status: lastScaleUpTime=2022-09-12 19:52:17.181240736 +0000 UTC m=+1114.659469832 lastScaleDownDeleteTime=2022-09-12 19:44:15.051545164 +0000 UTC m=+632.529774260 lastScaleDownFailTime=2022-09-12 18:34:02.514967734 +0000 UTC m=-3580.006803070 scaleDownForbidden=false scaleDownInCooldown=false
I0912 20:02:21.630067       1 static_autoscaler.go:567] Starting scale down

I0912 20:02:21.630121       1 legacy.go:635] aks-agentpool-22992539-vmss00001x was unneeded for 2m40.75584183s
I0912 20:02:21.630171       1 legacy.go:635] aks-agentpool-22992539-vmss00001o was unneeded for 9m52.612444937s
I0912 20:02:21.630224       1 legacy.go:669] Including aks-agentpool-22992539-vmss00001o - node has scale-down-requested annotation
I0912 20:02:21.630230       1 legacy.go:635] aks-agentpool-22992539-vmss00001t was unneeded for 2m40.75584183s
I0912 20:02:21.630283       1 legacy.go:635] aks-agentpool-22992539-vmss00001w was unneeded for 2m40.75584183s

I0912 20:02:21.630363       1 cluster.go:160] aks-agentpool-22992539-vmss00001o for removal
I0912 20:02:21.630407       1 cluster.go:247] Looking for place for kube-system/konnectivity-agent-59c5567b84-5bw8v
I0912 20:02:21.630456       1 cluster.go:251] Pod kube-system/konnectivity-agent-59c5567b84-5bw8v can be moved to aks-agentpool-22992539-vmss00001t
I0912 20:02:21.630478       1 cluster.go:247] Looking for place for kube-system/coredns-6856d58c9d-9cs68
I0912 20:02:21.630509       1 cluster.go:251] Pod kube-system/coredns-6856d58c9d-9cs68 can be moved to aks-agentpool-22992539-vmss00001w
I0912 20:02:21.630536       1 cluster.go:182] node aks-agentpool-22992539-vmss00001o may be removed
I0912 20:02:21.698354       1 delete.go:103] Successfully added ToBeDeletedTaint on node aks-agentpool-22992539-vmss00001o

I0912 20:02:21.698467       1 actuator.go:194] Scale-down: removing node aks-agentpool-22992539-vmss00001o, utilization: {0.11139896373056994 0.02460904152806767 0 cpu 0.11139896373056994}, pods to reschedule: konnectivity-agent-59c5567b84-5bw8v,coredns-6856d58c9d-9cs68

I0912 20:02:32.143914       1 drain.go:151] All pods removed from aks-agentpool-22992539-vmss00001o
I0912 20:02:32.144060       1 azure_scale_set.go:351] Deleting vmss instances [azure:///subscriptions/3b96dd57-b968-4e2b-8ad7-43bf473caf64/resourceGroups/mc_xint-t0910_xint-t0910-aks_westus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-22992539-vmss/virtualMachines/60]
I0912 20:02:32.144185       1 azure_scale_set.go:401] Calling virtualMachineScaleSetsClient.DeleteInstancesAsync(&[60])
I0912 20:02:32.265154       1 azure_scale_set.go:184] Calling virtualMachineScaleSetsClient.WaitForDeleteInstancesResult(&[60]) for aks-agentpool-22992539-vmss
```

In addition, after deploying the test container image, all pods in `kube-system` namespace had been running successfully without any restarts.

```
(base) ➜  ~ kubectl get pods -o wide -n kube-system
NAME                                  READY   STATUS    RESTARTS   AGE     IP            NODE                                NOMINATED NODE   READINESS GATES
azure-ip-masq-agent-4c28k             1/1     Running   0          9h      10.224.0.6    aks-agentpool-22992539-vmss00001t   <none>           <none>
azure-ip-masq-agent-j5ts6             1/1     Running   0          8h      10.224.0.9    aks-agentpool-22992539-vmss00001w   <none>           <none>
azure-ip-masq-agent-kk849             1/1     Running   0          7h54m   10.224.0.7    aks-agentpool-22992539-vmss00001y   <none>           <none>
cloud-node-manager-4jdk5              1/1     Running   0          7h54m   10.224.0.7    aks-agentpool-22992539-vmss00001y   <none>           <none>
cloud-node-manager-94kbz              1/1     Running   0          9h      10.224.0.6    aks-agentpool-22992539-vmss00001t   <none>           <none>
cloud-node-manager-gr6q6              1/1     Running   0          8h      10.224.0.9    aks-agentpool-22992539-vmss00001w   <none>           <none>
cluster-autoscaler-85dfdff7c7-gz52v   1/1     Running   0          8h      10.244.68.4   aks-agentpool-22992539-vmss00001w   <none>           <none>
coredns-6856d58c9d-6d9nq              1/1     Running   0          9h      10.244.65.3   aks-agentpool-22992539-vmss00001t   <none>           <none>
coredns-6856d58c9d-qkws6              1/1     Running   0          7h41m   10.244.70.3   aks-agentpool-22992539-vmss00001y   <none>           <none>
coredns-autoscaler-559d556687-vqpch   1/1     Running   0          8h      10.244.68.5   aks-agentpool-22992539-vmss00001w   <none>           <none>
csi-azuredisk-node-jd8kw              3/3     Running   0          7h54m   10.224.0.7    aks-agentpool-22992539-vmss00001y   <none>           <none>
csi-azuredisk-node-nmkkk              3/3     Running   0          8h      10.224.0.9    aks-agentpool-22992539-vmss00001w   <none>           <none>
csi-azuredisk-node-zglfl              3/3     Running   0          9h      10.224.0.6    aks-agentpool-22992539-vmss00001t   <none>           <none>
csi-azurefile-node-9hn6s              3/3     Running   0          7h54m   10.224.0.7    aks-agentpool-22992539-vmss00001y   <none>           <none>
csi-azurefile-node-n6ngs              3/3     Running   0          8h      10.224.0.9    aks-agentpool-22992539-vmss00001w   <none>           <none>
csi-azurefile-node-n8x82              3/3     Running   0          9h      10.224.0.6    aks-agentpool-22992539-vmss00001t   <none>           <none>
konnectivity-agent-59c5567b84-9zs6h   1/1     Running   0          8h      10.244.65.6   aks-agentpool-22992539-vmss00001t   <none>           <none>
konnectivity-agent-59c5567b84-h6lqz   1/1     Running   0          7h41m   10.244.68.7   aks-agentpool-22992539-vmss00001w   <none>           <none>
kube-proxy-65mt6                      1/1     Running   0          9h      10.224.0.6    aks-agentpool-22992539-vmss00001t   <none>           <none>
kube-proxy-crg77                      1/1     Running   0          8h      10.224.0.9    aks-agentpool-22992539-vmss00001w   <none>           <none>
kube-proxy-gj9dh                      1/1     Running   0          7h54m   10.224.0.7    aks-agentpool-22992539-vmss00001y   <none>           <none>
metrics-server-69559866b8-df4sr       2/2     Running   0          7h34m   10.244.68.8   aks-agentpool-22992539-vmss00001w   <none>           <none>
metrics-server-69559866b8-ghlxg       2/2     Running   0          7h34m   10.244.70.4   aks-agentpool-22992539-vmss00001y   <none>           <none>
```

**Comment by liuxintong** [comment]
@feiskyer / @x13n - Could you help review this PR? Thanks.

**Comment by liuxintong** [comment]
@x13n - I see you are doing some refactoring, please let me know if you have any concern about this feature before I rebase my PR.

**Comment by x13n** [comment]
Hi @liuxintong , thanks for sending the change! I'll try to do a proper review next week. I'm indeed moving quite a lot of scale down logic around, so it will be better to wait until then with merging this PR. One high level comment I have for now is that maybe it makes sense to split this into 2 PRs? Optional enforcement of min size is a feature in itself and doesn't interfere with my changes, so maybe it could be done first.

**Comment by liuxintong** [comment]
Thanks @x13n! Splitting into 2 pull requests also make sense to me. I'll make it in a new PR. Please let me know once your scale down optimization is done, so that I can implement the new feature based on your changes.

**Comment by MarcPow** [comment]
@x13n is the conflicting refactor now complete?

**Comment by x13n** [comment]
Yes it is! The work here shouldn't be blocked on anything now.

**Comment by liuxintong** [comment]
In addition to unit tests, this PR has been verified in an Azure Kubernetes cluster. The following example shows how CA scales down a node that hosts the cluster-autoscaler pod.

@x13n / @MarcPow / @feiskyer, this PR is ready for review, please help take a look, thanks!

```
(base) ➜  ~ kubectl get node
NAME                                STATUS   ROLES   AGE     VERSION
aks-agentpool-17091672-vmss00002q   Ready    agent   66m     v1.24.3
aks-agentpool-17091672-vmss00002u   Ready    agent   9m16s   v1.24.3
aks-agentpool-17091672-vmss00002v   Ready    agent   88s     v1.24.3

(base) ➜  ~ kubectl get pod -l app=cluster-autoscaler -n kube-system -o wide
NAME                                  READY   STATUS    RESTARTS   AGE     IP            NODE                                NOMINATED NODE   READINESS GATES
cluster-autoscaler-75c6cfc6bd-6z28d   1/1     Running   0          4m58s   10.244.92.2   aks-agentpool-17091672-vmss00002u   <none>           <none>

(base) ➜  ~ kubectl annotate node aks-agentpool-17091672-vmss00002u cluster-autoscaler.kubernetes.io/scale-down-requested=5
node/aks-agentpool-17091672-vmss00002u annotated

(base) ➜  ~ kubectl logs -n kube-system cluster-autoscaler-75c6cfc6bd-6z28d -f > tmpf.log

I1206 08:13:34.678485       1 static_autoscaler.go:524] Calculating unneeded nodes
I1206 08:13:34.678864       1 eligibility.go:140] Node aks-agentpool-17091672-vmss00002u is removable (cpu utilization 0.155699), because it has scale-down-requested annotation

I1206 08:13:34.679567       1 nodes.go:84] aks-agentpool-17091672-vmss00002v is unneeded since 2022-12-06 08:12:24.397596394 +0000 UTC m=+594.022400670 duration 1m10.279817063s
I1206 08:13:34.679578       1 nodes.go:84] aks-agentpool-17091672-vmss00002q is unneeded since 2022-12-06 08:13:24.649375971 +0000 UTC m=+654.274180147 duration 10.028037586s
I1206 08:13:34.679584       1 nodes.go:84] aks-agentpool-17091672-vmss00002u is unneeded since 2022-12-06 08:08:03.447287777 +0000 UTC m=+333.072092053 duration 5m31.23012568s

I1206 08:13:34.679775       1 static_autoscaler.go:581] Starting scale down
I1206 08:13:34.775157       1 delete.go:103] Successfully added ToBeDeletedTaint on node aks-agentpool-17091672-vmss00002u
I1206 08:13:34.775266       1 actuator.go:212] Scale-down: removing node aks-agentpool-17091672-vmss00002u, utilization: {0.15569948186528498 0.056600795514555644 0 cpu 0.15569948186528498}, pods to reschedule: coredns-59b6bf8b4f-26xrt,coredns-autoscaler-5655d66f64-zcmpn,metrics-server-5f8d84558d-qmrh2,konnectivity-agent-598b769b5c-jfljw,cluster-autoscaler-75c6cfc6bd-6z28d

I1206 08:13:34.775843       1 scale_up.go:485] ScaleUpToNodeGroupMinSize: node aks-agentpool-17091672-vmss00002u in node group aks-agentpool-17091672-vmss has scale-down-requested annotation
I1206 08:13:34.775856       1 scale_up.go:490] ScaleUpToNodeGroupMinSize: NodeGroup aks-agentpool-17091672-vmss, TargetSize 3, MinSize 2, MaxSize 10, ScaleDownRequested 1
I1206 08:13:34.775863       1 scale_up.go:535] ScaleUpToNodeGroupMinSize: scale up not needed

I1206 08:13:39.776594       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/coredns-autoscaler-5655d66f64-zcmpn from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776626       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/metrics-server-5f8d84558d-qmrh2 from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776640       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/cluster-autoscaler-75c6cfc6bd-6z28d from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776695       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/konnectivity-agent-598b769b5c-jfljw from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776627       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/coredns-59b6bf8b4f-26xrt from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776595       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/csi-azuredisk-node-48xng from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776607       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/cloud-node-manager-rtwfq from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776840       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/csi-azurefile-node-njxtc from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776611       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/kube-proxy-dh2pg from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation
I1206 08:13:39.776617       1 drain.go:234] Overriding max graceful termination seconds of pod kube-system/azure-ip-masq-agent-6m6gc from 30 to 5, because node aks-agentpool-17091672-vmss00002u has scale-down-requested annotation

I1206 08:13:40.183285       1 main.go:349] Cleaned up, exiting...

(base) ➜  ~ kubectl get node
NAME                                STATUS     ROLES   AGE   VERSION
aks-agentpool-17091672-vmss00002q   Ready      agent   76m   v1.24.3
aks-agentpool-17091672-vmss00002u   NotReady   agent   19m   v1.24.3
aks-agentpool-17091672-vmss00002v   Ready      agent   11m   v1.24.3
aks-agentpool-17091672-vmss00002w   Ready      agent   33s   v1.24.3

(base) ➜  ~ kubectl get pod -l app=cluster-autoscaler -n kube-system -o wide
NAME                                  READY   STATUS    RESTARTS   AGE     IP            NODE                                NOMINATED NODE   READINESS GATES
cluster-autoscaler-75c6cfc6bd-7f2tc   1/1     Running   0          4m13s   10.244.93.5   aks-agentpool-17091672-vmss00002v   <none>           <none>

(base) ➜  ~ kubectl logs -n kube-system cluster-autoscaler-75c6cfc6bd-7f2tc > tmp.log

I1206 08:14:14.396478       1 delete.go:197] Releasing taint {Key:ToBeDeletedByClusterAutoscaler Value:1670314414 Effect:NoSchedule TimeAdded:<nil>} on node aks-agentpool-17091672-vmss00002u
I1206 08:14:14.489510       1 delete.go:228] Successfully released ToBeDeletedTaint on node aks-agentpool-17091672-vmss00002u

I1206 08:14:14.491200       1 static_autoscaler.go:524] Calculating unneeded nodes
I1206 08:14:14.491426       1 eligibility.go:140] Node aks-agentpool-17091672-vmss00002u is removable (cpu utilization 0.080311), because it has scale-down-requested annotation

I1206 08:14:14.491890       1 static_autoscaler.go:581] Starting scale down
I1206 08:14:14.491976       1 nodes.go:192] Node aks-agentpool-17091672-vmss00002u is removable, because it has scale-down-requested annotation
I1206 08:14:14.591497       1 delete.go:103] Successfully added ToBeDeletedTaint on node aks-agentpool-17091672-vmss00002u
I1206 08:14:14.591543       1 actuator.go:161] Scale-down: removing empty node "aks-agentpool-17091672-vmss00002u"

I1206 08:14:19.815745       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"e1c2d971-7210-40cc-9404-38387d3aa23f", APIVersion:"v1", ResourceVersion:"33886671", FieldPath:""}): type: 'Normal' reason: 'ScaleDownEmpty' Scale-down: empty node aks-agentpool-17091672-vmss00002u removed
```

**Review by x13n — COMMENTED** [review]
I started to review the code and you can see a bunch of my comments on some of the files, but I actually started to doubt this is something we should be adding to Cluster Autoscaler. This isn't really about autoscaling, it is about automatic node repairs. If I understand correctly, the use case here is to manually tag certain broken nodes for removal. This looks like something that could be already achieved by cordoning/draining node with `kubectl`, followed by VM removal via cloud provider API. The min size enforcement will then kick in, if necessary. WDYT?

**Comment by x13n** [comment]
Given my reasoning above and lack of activity here, I'm going to close this PR. Please reopen if you disagree.

/close

**Comment by liuxintong** [comment]
Reopening as I'm currently working on it.
/reopen

**Comment by liuxintong** [comment]
@x13n - I was going to reply to your previous comments, but I didn't get any time until today. Apologized for the delay.

> Hi @liuxintong ! Can you clarify what is the benefit of having this logic in autoscaler?

Technically, we can developer a new cluster controller to meet all the business needs. But it would have lots of duplicate logics, just like what we have here. Then we also need to resolve scale-down conflicts between the new controller and cluster-autoscaler. CA already has a mature implementation in this area, like scale-down simulation, node draining rules, cloud provider integration, etc. I'd like to leverage it to achieve the goal of scaling down a specific node.

Another motivation is that new node provisioning takes longer on Windows than on Linux, and we want to reduce the pod pending time to minimize the impact on services. When we need to scale down a node, we can scale up a new node at the same time. Then the pods can be moved from the old node to the new node as quickly as possible.

> IIUC the user will observe more or less the same behavior by annotating the pod as if they just did `kubectl drain`.

You are right if we only have a few clusters to operate. However, we mange thousands of clusters. This simple problem gets complicated when the scale is up.

For the 2 options you mentioned, I think the main differences are as follows:
* `kubectl annotate`/`kubectl taint`: it returns immediately, and we can guarantee success with the logic in CA.
* `kubectl drain`: we need to track the execution externally, and the node draining might be failed (no guarantee).

In addition, all related code logics are controlled by the new flag `--force-scale-down-enabled`, and the default value is `false`. If others don't need it, they won't feel any difference.

@MarcPow also shared more context in Issue #5109. Please let us know if you have any additional concerns. Thank you!

**Review by liuxintong — COMMENTED** [review]
@x13n - I was going to reply to your previous comments, but I didn't get any time until today. Apologized for the delay.

> Hi @liuxintong ! Can you clarify what is the benefit of having this logic in autoscaler?

Technically, we can developer a new cluster controller to meet all the business needs. But it would have lots of duplicate logics, just like what we have here. Then we also need to resolve scale-down conflicts between the new controller and cluster-autoscaler. CA already has a mature implementation in this area, like scale-down simulation, node draining rules, cloud provider integration, etc. I'd like to leverage it to achieve the goal of scaling down a specific node.

Another motivation is that new node provisioning takes longer on Windows than on Linux, and we want to reduce the pod pending time to minimize the impact on services. When we need to scale down a node, we can scale up a new node at the same time. Then the pods can be moved from the old node to the new node as quickly as possible.

> IIUC the user will observe more or less the same behavior by annotating the pod as if they just did `kubectl drain`.

You are right if we only have a few clusters to operate. However, we mange thousands of clusters. This simple problem gets complicated when the scale is up.

For the 2 options you mentioned, I think the main differences are as follows:
* `kubectl annotate`/`kubectl taint`: it returns immediately, and we can guarantee success with the logic in CA.
* `kubectl drain`: we need to track the execution externally, and the node draining might be failed (no guarantee).

In addition, all related code logics are controlled by the new flag `--force-scale-down-enabled`, and the default value is `false`. If others don't need it, they won't feel any difference.

@MarcPow also shared more context in Issue #5109. Please let us know if you have any additional concerns. Thank you!

**Comment by Bryce-Soghigian** [comment]
I still don't see the benefit over just kubectl drain

**Comment by x13n** [comment]
If the only difference between `kubectl drain` and `kubectl annotate` is
the need to wait for actuation, then perhaps
https://github.com/kubernetes/enhancements/issues/4212 is going to address
this use case better? I think once this KEP lands, Cluster Autoscaler
should start relying on it as well.

**Comment by sftim** [comment]
> If the only difference between `kubectl drain` and `kubectl annotate` is the need to wait for actuation, then perhaps [kubernetes/enhancements#4212](https://github.com/kubernetes/enhancements/issues/4212) is going to address this use case better?

That KEP provides a better authorization story; we can allow users (and controllers) to _request_ node drains, and we can allow a controller to trigger draining even without allowing it to write to a node; labelling nodes can break expectations around workload isolation.

@liuxintong if you're willing to contribute to defining that KEP, I think it provides a good way forward. The work you've done on this PR can help ensure that the cluster autoscaler is ready for the arrival of declarative node drains.

**Comment by x13n** [comment]
I'm closing this one due to inactivity. Looks like long term we can depend on declarative node maintenance for this use case.

/close

**Pull request closed without merging**
