### PR TITLE
[charts] Adopt Cluster Autoscaler chart

### PR DESCRIPTION
**Pull request by sc250024**
Adopts the [stable/cluster-autoscaler](https://hub.helm.sh/charts/stable/cluster-autoscaler) chart, making this repository the official home for the chart moving forward. Only minor changes have been made to the chart itself; most of it is original from the `stable` channel.

Solves https://github.com/kubernetes/autoscaler/issues/3318.

Helm chart deprecation PR: https://github.com/helm/charts/pull/23305

## Description

As mentioned, this PR adopts the `cluster-autoscaler` chart officially into this repository. The following changes were made.

- Helm 3
  - The version of the chart that will be maintained in this repo moving forward will be for Helm 3+ only. The `apiVersion` on this chart has been changed to `v2` reflect this change.
- Helm-docs for generation of README
  - The [helm-docs](https://github.com/norwoodj/helm-docs) project is an awesome time-saving utility that makes it so you write descriptions in the `values.yaml` file **once**, and those changes are automatically propagated to the `README.md` file, including auto-generation of the possible configuration options on the chart.
- GitHub Actions for testing
  - New GitHub actions have been added to this repository for chart testing and releasing. These are the official actions maintained by the Helm team.
- Removed Spotinst support from the chart
  - Running the command `docker pull spotinst/kubernetes-cluster-autoscaler:0.6.0` results in an error because the image no longer exists. It appears that Spot.io now has their own separate Helm chart here: https://github.com/spotinst/spotinst-kubernetes-helm-charts. Therefore, support for Spot.io in this chart is no longer needed.

### `gh-pages`

I will need someone who has write access to this repository to create a **_bare_** branch named `gh-pages` to serve as the Helm chart repository. The GitHub action that performs releasing will fail until this is done first.

Commands:

```shell
$ git checkout --orphan gh-pages
$ git rm -rf .
$ git add index.html
$ git commit -m "Initial commit"
$ git push origin gh-pages
```

The following `index.html` file can be used as a very simple installation guide for the Helm chart repository.

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Autoscaler Helm Charts</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>

  <body>
    <h1>Autoscaler Helm Charts</h1>
    <p>Use the following commands to install the Autoscaler Helm repository:</p>
    <pre>helm repo add autoscaler https://kubernetes.github.io/autoscaler
helm repo update</pre>
    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>
```

</details>

### Enable GitHub Actions

Since GitHub Actions is taking care of the linting / testing / releasing portions of this project, they need to be enabled for this repository.

## Kudos

Let's thank @yurrriq, @mgoodness on this PR since they maintained the original chart here for so long: https://github.com/helm/charts/tree/master/stable/cluster-autoscaler. Their feedback would be appreciated here as well.

## Motivation and Context

Since the `stable` channel of the Helm chart repository [helm/charts](https://github.com/helm/charts) [will eventually be deprecated](https://github.com/helm/charts#deprecation-timeline), moving the chart into this repository, and setting up a simple GitHub pages URL as a Helm repo makes more sense. Other repositories in the [kubernetes](https://github.com/kubernetes) GitHub organization are doing the same.

## How Has This Been Tested?

- Pre-commit hooks added, so that basic `helm lint`-ing occurs before commits
- Uses Helm GitHub actions to perform linting on server-side.
- Uses Helm GitHub actions to perform installation using Kind.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks for getting this started! I'd be happen to maintain the same level of commitment to reviewing PRs here.

**Comment by sc250024** [comment]
> Thanks for getting this started! I'd be happy to maintain the same level of commitment to reviewing PRs here.

Much appreciated! You and @mgoodness are still maintainers on this chart for a reason, so very happy to hear that it will continue that way.

**Comment by gjtempleton** [comment]
Great to hear! As that's the case, I think it's worth adding an OWNERS file to the `charts/cluster-autoscaler` directory as otherwise the bot will require approval from members of the one at the root of the repo.

**Comment by MaciekPytel** [comment]
+1 to everything @gjtempleton wrote in comment above.

**Comment by detiber** [comment]
> Great to hear! As that's the case, I think it's worth adding an OWNERS file to the charts/cluster-autoscaler directory as otherwise the bot will require approval from members of the one at the root of the repo for every PR to the chart.

Would it make sense to switch this up a bit and make a charts directory (for each component that would have a chart) under each component directory instead of having a top level charts directory? That would allow for inheriting the per-directory OWNERS files that already exist?

I'm not sure if that is something that is supported by the helm tooling and would just need some configuration changes.

**Comment by MaciekPytel** [comment]
My expectation is that component owners are actually not the ones maintaining helm charts, so I'm not sure how useful inheriting OWNERS would be. Keeping all charts in a separate directory gives us a chance to have a top-level charts OWNERS, which I think is more inline with how it will end up working. So, personally, I like the current structure (but I can be convinced I'm wrong on this :) ).

**Comment by sc250024** [comment]
> Would it make sense to switch this up a bit and make a charts directory (for each component that would have a chart) under each component directory instead of having a top level charts directory? That would allow for inheriting the per-directory OWNERS files that already exist?

I thought about that too, but I leaned more towards what @MaciekPytel said. Aside from a bump of the `appVersion` when a new version of `cluster-autoscaler` is released, most of it is already taken care of.

Also, the GitHub actions which performs the chart release works on the assumption that all charts are within one directory, which is also what the https://github.com/helm/charts repo does.

**Comment by sc250024** [comment]
I will add an `OWNERS` file as @gjtempleton suggested. By the way, does anyone have a clue as to why the TravisCI builds are failing?

**Comment by sc250024** [comment]
@MaciekPytel ^^^^ I guess we're not worthy 😃

**Comment by MaciekPytel** [comment]
/approve
Looks good to me, but I'll leave lgtm-ing to @gjtempleton.

**Comment by gjtempleton** [comment]
/lgtm
Sorry for the delay!

**Comment by sc250024** [comment]
@gjtempleton Did the GH Pages bit get done first? I saw that the release failed.

**Comment by gjtempleton** [comment]
@sc250024 No, I'd just noticed that, the actual failure however seems unrelated to that and related instead to this issue, so it's failing before it gets to the stage requiring the gh-pages branch:

helm/chart-releaser/issues/65

For the creation of the gh-pages branch it'll need to be someone with write access to the repo, I don't have that, @MaciekPytel can you handle that part for us please?

**Comment by sc250024** [comment]
@gjtempleton I can open another PR that fixes the conflicting name. The chart releaser tool attempted to use `cluster-autoscaler-1.0.0`, which already exists.

The issue https://github.com/helm/chart-releaser/issues/65 needs to be addressed to handle tags / releases idempotently, but as a workaround, we could just rename the chart from `cluster-autoscaler` to `cluster-autoscaler-chart` to make things very clear when it is tagged?

**Comment by gjtempleton** [comment]
That seems like a reasonable workaround to me, allows for a different release cadence between the CA itself and the charts.

**Comment by sc250024** [comment]
> That seems like a reasonable workaround to me, allows for a different release cadence between the CA itself and the charts.

Ok, two seconds ...

**Comment by sc250024** [comment]
@gjtempleton @MaciekPytel PR that fixes this is here => https://github.com/kubernetes/autoscaler/pull/3393

**Comment by scottrigby** [comment]
👏  https://github.com/helm/charts/issues/21103

**Pull request merged**
