### PR TITLE
fix: don't clean `CriticalAddonsOnly` taint from template nodes

### LINKED ISSUE #4097: [cluster-autoscaler] CriticalAddonsOnly taint ignored
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

1.20.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

1.20.5

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"54684493f8139456e5d2f963b23cb5003c4d8055", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:59Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

Azure w/ VMSS scaling configured via auto-discovery

**What did you expect to happen?**:

When I apply taint `CriticalAddonsOnly=true:NoSchedule` to a node group, it should be respected.

**What happened instead?**:

This particular taint is not respected during scaling calculations.

**How to reproduce it (as minimally and precisely as possible)**:

Create a node group with this taint and one without, scale a deployment without a matching toleration, notice that the tainted node group will get scaled occasionally.

**Anything else we need to know?**:

This appears to be a result of this taint filtering logic; https://github.com/kubernetes/autoscaler/blob/d33cc1bc400f6d5cccaa0ca95696fa0e1780df29/cluster-autoscaler/utils/taints/taints.go#L70

I believe this is the problem in this old issue that went unresolved: https://github.com/kubernetes/autoscaler/issues/2434

After searching the repository, I could not find any references to this value in the core logic. While I may be missing something, I am not sure what the intended purpose of this filter is.  The only thing I can find is a reference to a "rescheduler". I think it may be related to this KEP but I'm not sure if its still relevant: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/rescheduling.md

It is hindering my use case in the Azure/AKS b/c that is the _only_ taint that can be added to the default system node pool. Frequently the scaling is _very_ delayed as the autoscaler will scale this node pool incorrectly and repeatedly. My hacky workaround is to just have the autoscaler ignore this node pool, but I am afraid this unexpected behavior will continue to surprise people. Moreover, I'd like to be able to not ignore this pool in the future.

(1) Can it be removed?
(2) If not, can a warning and explanation be added to the FAQ?

### PR DESCRIPTION
**Pull request by vadasambar**
- this taint leads to unexpected behavior
- users expect CA to consider the taint when autoscaling

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #4097 

#### Does this PR introduce a user-facing change?

```release-note
Removed: `CriticalAddonsOnly` taint will not be cleaned from template nodes anymore. This is a *backwards incompatible* change. Check https://github.com/kubernetes/autoscaler/issues/4097 for more information. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by vadasambar** [comment]
@MaciekPytel waiting for your review.

**Comment by vadasambar** [comment]
> @MaciekPytel waiting for your review.

@MaciekPytel waiting for your review.

**Review by pierluigilenoci — APPROVED** [review]

**Pull request merged**
