### PR TITLE
Support Baiducloud Cloud Provider for cluster-autoscaler

### PR DESCRIPTION
**Pull request by hello2mao**
**What this PR does / why we need it:**
BaiduCloud Container Engine is a high-performance and scalable container application management service using Kubernetes.
As the gold member of Kubernetes community, we create this PR to support Baiducloud Cloud Provider for cluster-autoscaler.

### CODE REVIEW

**Comment by hello2mao** [comment]
cc @mwielgus

**Comment by mwielgus** [comment]
@hello2mao I assume that you will be the main contact point for Baidu-related issues/prs.

**Comment by hello2mao** [comment]
@mwielgus Yes, @tizhou86 and I will be the maintainers for Baidu-related issues.

**Comment by hello2mao** [comment]
> Cool, can you add your contact details (github, mail or slack handle) to the Readme file so that people reporting problems/asking questions have an easier job?

OK, I will add some information later.

**Pull request merged**
