### PR TITLE
[CA-1.19] Backport #3416

### PR DESCRIPTION
**Pull request by benmoss**
Trying to do work on the 1.19 branch, and running into the same problem that #3416 fixes on master.

> Replacing the module path in go.mod did not solve
the issue preventing hack/update-vendor.sh from
running properly, so it will have to be deleted.

@detiber @elmiko @tghartland

### CODE REVIEW

**Comment by tghartland** [comment]
I can't approve the PR myself, but yes this should be backported. Apologies again for breaking update-vendor in the first place.

/lgtm

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by benmoss** [comment]
ugh @feiskyer isn't an owner on 1.19 😸

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
