### PR TITLE
Doc: fix the Allocation Strategies link in AWS CA README

### PR DESCRIPTION
**Pull request by chingyi-lin**
- Fix the link to ASG allocation strategies in AWS CA README.

### CODE REVIEW

**Comment by chingyi-lin** [comment]
Signed the CLA. Thanks!

**Comment by losipiuk** [comment]
@chingyi-lin Please sign cla

**Comment by chingyi-lin** [comment]
> @chingyi-lin Please sign cla

I signed again. Is it there?

**Pull request merged**
