### PR TITLE
Add Jeffwan as approver for aws cloud provider

### PR DESCRIPTION
**Pull request by losipiuk**
cc: @Jeffwan

### CODE REVIEW

**Comment by MaciekPytel** [comment]
If @Jeffwan is up for it, I'm +1.
/hold
So @Jeffwan has a chance to react :)

/lgtm
/approve

cc: @mwielgus

**Comment by mwielgus** [comment]
I don't see any reason why @Jeffwan would reject approve rights, let's not make it too formal. Lifting the hold.

**Comment by Jeffwan** [comment]
Thanks a lot guys! I will put more efforts to help grow community. @losipiuk @MaciekPytel @mwieczorek

**Pull request merged**
