### PR TITLE
improve error messages

### PR DESCRIPTION
**Pull request by lubedacht**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

I think we should provide more information in our error messages to have more visibility.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by Shubham82** [comment]
@lubedacht, you have to sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check EasyCLA

/easycla

**Comment by lubedacht** [comment]
Hi @Shubham82,
Thank you for your message, I am aware of the process. I have a personal account where I have already signed the CLA but this is a company account and here I seem to have to include my manager in the signing process.

If this isn't resolved in the next days I will reopen the PR with my other account.

**Comment by Shubham82** [comment]
Hi @lubedacht
Is there any update on your CLA things?

**Comment by lubedacht** [comment]
@Shubham82 doesn't look like it. I will close this PR now

**Pull request closed without merging**
