### PR TITLE
Metrics for Hetzner API calls

### PR DESCRIPTION
**Pull request by maksim-paskal**
Provide metrics for Hetzner API calls; helps identifying slowness, throttling causes, and errors bursts.

Signed-off-by: Maksim Paskal <paskal.maksim@gmail.com>

### CODE REVIEW

**Comment by maksim-paskal** [comment]
@LKaemmerling please take a look!

**Review by LKaemmerling — APPROVED** [review]

**Comment by LKaemmerling** [comment]
Hey @maksim-paskal,

this looks fine from my side :)

**Comment by maksim-paskal** [comment]
rebased

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
