### PR TITLE
cleanup(vpa): remove go vendoring for e2e

### LINKED ISSUE #7570: VPA: Remove the vendor dir
**Which component are you using?**:
/area vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Remove the vendor dir for dev-productivity purposes. Right now, on updating dependencies the GitHub web app crashes. The vendor dir also causes delays while cloning the rep and while resolving conflicts (you get unnecessary conflicts under the vendor dir).

**Describe the solution you'd like.**:

Remove the vendor dir for the VPA. The cluster-autoscaler no longer has a vendor dir. It seems to be removed with https://github.com/kubernetes/autoscaler/pull/6973.

**Describe any alternative solutions you've considered.**:
N/A

**Additional context.**:

See https://github.com/kubernetes/autoscaler/pull/7551#issuecomment-2519495512

### PR DESCRIPTION
**Pull request by davidspek**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

This PR removes the `e2e/vendor` directory for the VPA. Vendoring the dependencies into the repo not only increases the size, but also makes reviewing PRs that include dependency changes more difficult. Sometimes to the point of breaking the GitHub UI like in https://github.com/kubernetes/autoscaler/pull/7551 and likely this PR.

#### Which issue(s) this PR fixes:

Fixes #7570

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by davidspek** [comment]
/assign gjtempleton

since this changes a file in the hack/ directory and you recently approved a PR with a similar change.

**Comment by davidspek** [comment]
/assign raywainman

For the VPA part of the changes

**Comment by raywainman** [comment]
Thanks so much for the cleanup.

/lgtm

/approve

**Comment by gjtempleton** [comment]
Thanks for this!
/approve

**Pull request merged**
