### PR TITLE
Cluster-Autoscaler - Update hardcoded AWS instance list

### PR DESCRIPTION
**Pull request by gjtempleton**
Bring AWS fallback hardcoded list of instances up to date to 30/08/21

* Brings in new [m6i](https://aws.amazon.com/ec2/instance-types/m6i/) and [x2gd](https://aws.amazon.com/ec2/instance-types/x2/) instance family data as well as other assorted new sizes in existing families

### CODE REVIEW

**Comment by der-eismann** [comment]
Sorry, I just saw your PR after opening #4300. Since the header of the file explicitly says
> This file was generated by go generate; DO NOT EDIT

shouldn't you generate it?

**Comment by gjtempleton** [comment]
The diff for this was [generated](https://github.com/kubernetes/autoscaler/blob/7a123ea388b3822922c506fa394a5caa66bb054c/cluster-autoscaler/Makefile#L80) via running `make generate` in the `cluster-autoscaler` directory of the repo.

**Comment by der-eismann** [comment]
Ah, I thought this info is pulled from the AWS SDK, didn't read the `go generate` code.

**Comment by mbyio** [comment]
Anything I can do to help move this along? We didn't realize that the instance types were hard-coded and added new node groups that cluster autoscaler doesn't support yet. 😓

**Comment by gjtempleton** [comment]
You should still be able to use the default behaviour of generating an up-to-date list on the CA starting if this is a blocker to you (though we're aware there are reasons people can't use this behaviour.)

/assign @jaypipes

**Comment by mbyio** [comment]
@gjtempleton yes you're right, thank you. Actually I was monitoring it and saw the errors, came back a half hour later and it had restarted on its own and started working as expected.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by sturman** [comment]
@mwielgus is this going to be merged in `cluster-autoscaler-release-1.21` branch and released soon? Can I help to get this changes available in CA 1.21 next release?

**Comment by gjtempleton** [comment]
Hi @sturman That's my fault. I've just raised a series of PRs to update the hardcoded fallback list in all of the current supported release branches. Assuming they get merged, they should be released once a new set of patch releases is cut.

**Comment by Robert-Stam** [comment]
Is there an ETA when there will be an updated CA (1.21.x/1.22.x) with this PR?

**Comment by gjtempleton** [comment]
There's not currently a timeline for cutting a new set of releases, no. 

I've just added discussing it as an agenda item for the next SIG meeting.

**Pull request merged**
