### PR TITLE
Add c5a EC2 instance type for AWS

### PR DESCRIPTION
**Pull request by hajowieland**
Just added newly created AWS **c5a** EC2 instances type on EC2 catalog.

See the AWS announcement (04 JUN 2020): https://aws.amazon.com/blogs/aws/new-amazon-ec2-c5a-instances-powered-by-2nd-gen-amd-epyc-processors/

### CODE REVIEW

**Comment by hajowieland** [comment]
@Jeffwan 
Why is the build always stalling in Travis?
Is there anything wrong with my PR ?

**Comment by gjtempleton** [comment]
@hajowieland Can you try closing and re-opening the PR to re-trigger the Travis build, the latest ones should now be successful.

**Comment by hajowieland** [comment]
Closed + Reopened as requested by @gjtempleton

**Comment by trondhindenes** [comment]
it would be awesome to get at least a pre-release image of this build. We're using c5a instances and just noticed that cluster-autoscaler doesnt understand them.

side note: wouldn't it be much better if cluster-autoscaler used the relevant ec2 apis to build a dynamic list of available instance types instead of having it statically typed? (https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-types.html)

**Comment by gjtempleton** [comment]
@trondhindenes Which version of the CA are you running?

There was a bug captured in #3109 that is now fixed in master and is in the process of being cherry-picked back for new patch releases to use the dynamic generation functionality.

**Comment by Jeffwan** [comment]
/approve

Sorry for late.  Dynamic generation has been supported. If user find bugs, please help improve that

**Comment by TagadaPoe** [comment]
I could not find this update in any tag of the "cluster-autoscaler", will this be available soon ?

Listed tags for this commit: _vertical-pod-autoscaler/v0.9.0  vertical-pod-autoscaler-0.9.0 cluster-autoscaler-chart-1.1.1 cluster-autoscaler-chart-1.1.0 cluster-autoscaler-chart-1.0.5 cluster-autoscaler-chart-1.0.4 cluster-autoscaler-chart-1.0.3 cluster-autoscaler-chart-1.0.2 cluster-autoscaler-chart-1.0.1_

**Pull request merged**
