### PR TITLE
Exoscale cloud provider overhaul

### PR DESCRIPTION
**Pull request by falzm**
This change refactors the `exoscale` cloud provider to support both
plain Instance Pools and SKS Nodepools scaling.

### CODE REVIEW

**Comment by falzm** [comment]
@aleksandra-malinowska @feiskyer do I need to do something to have this PR reviewed?

**Comment by falzm** [comment]
@aleksandra-malinowska @feiskyer can I have eyes on this PR please? 🙏

**Comment by falzm** [comment]
@aleksandra-malinowska @feiskyer can I have eyes on this PR please? 🙏

**Comment by PhilippeChepy** [comment]
@mwielgus, @maciekpytel, @bskiba, @gjtempleton, why this PR isn't reviewed ? It's very useful and looks like to be well done work!

**Comment by gjtempleton** [comment]
Hey @PhilippeChepy, the @k8s-ci-robot comments document the process for PRs, including this stanza:

```
This pull-request has been approved by: falzm
To complete the pull request process, please assign feiskyer after the PR has been reviewed.
You can assign the PR to them by writing /assign @feiskyer in a comment when ready.
```

For my part I generally only monitor PRs I've been assigned to at this point, I know others follow the same workflow. 

I have to say that as this appears to be a wholesale change to a CloudProvider where I have no experience, I wouldn't be comfortable reviewing it, and we should be looking to find owners for the Exoscale Cloud Provider, to enable you to take ownership of the code for this CloudProvider implementation, and only need wider approval for changes which touch code outside of this.

@falzm I'm guessing from your comments in the original PR #3470 that you worked with @pierre-emmanuelJ at the time of implementation? Are both of you willing to take on ownership for this implementation (i.e. the contents of the `cloudprovider/exoscale` directory)?

**Comment by PhilippeChepy** [comment]
Hi @gjtempleton, thank you for your answer. Please, can you can set ownership of this provider code to:
- @pierre-emmanuelJ 
- @7fELF
- @PhilippeChepy

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by gjtempleton** [comment]
@falzm It looks like the commit's no longer linking to your Github user, can you update the commit to link it so the CLA check passes?

**Comment by falzm** [comment]
> @falzm It looks like the commit's no longer linking to your Github user, can you update the commit to link it so the CLA check passes?

@PhilippeChepy @7fELF one of you should probably sign off the CLA on behalf of Exoscale at this point, since I'm no longer part of the company.

**Comment by llambiel** [comment]
@PhilippeChepy @7fELF may I ask you to proceed as suggested by @falzm 

I'll have a look at the CLA

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
