### PR TITLE
Update k8s vendoring and remove hard-copied godo library

### PR DESCRIPTION
**Pull request by jaypipes**
* Updates vendored k8s to latest master from upstream
* Replaces the hard-copied github.com/digitalocean/godo library with one handles by Go modules

### CODE REVIEW

**Comment by jaypipes** [comment]
@losipiuk Hey, this is just prep for the changes that Micah introduced to the hack/update-vendor.sh script. I am submitting this as a separate PR because it dramatically reduces the patch size of the eventual PR and we were able to clean up the godo dep copying separately (by re-using the existing go.mod-extra technique)

**Comment by losipiuk** [comment]
Looks good. I will merge as soon as we finish cutting off release for 1.17

**Comment by jaypipes** [comment]
Closing this out. Easier to pull new from master and re-do the work versus trying to fix conflicts (which are all just go.sum checksums and impossible to really conflict-check.

**Pull request closed without merging**
