### PR TITLE
[VPA] Configurable upper and lower bounds for memory and cpu recommendations

### LINKED ISSUE #6420: [VPA] Does not respond to OOM for workloads with non-uniform resource utilization
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: v1.0.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.25.11
Kustomize Version: v4.5.7
Server Version: v1.25.16-eks-8cb36c9
</pre></details>

**What environment is this in?**:

EKS 1.25

**What did you expect to happen?**:

Expected that VPA would respond to OOM by adjusting the memory recommendation according to the [documented formula](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-1.0.0/vertical-pod-autoscaler/README.md#custom-memory-bump-up-after-oomkill):
```
recommendation = memory-usage-in-oomkill-event + max(oom-min-bump-up-bytes, memory-usage-in-oomkill-event * oom-bump-up-ratio)
```

**What happened instead?**:

Containers OOM continuously; VPA's recommendation is never adjusted.

**How to reproduce it (as minimally and precisely as possible)**:

The problem was originally observed with the `datadog-agent` Daemonset. Its resource needs can vary by node depending on how many pods are running there and the amount of metrics emitted. Sometimes the gap is quite signifant, like by a factor of 6. The issue is reproducible with a stress test.

Create a Deployment whose pods allocate a random amount of memory such that ~10% of them should OOM:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-stress
spec:
  replicas: 10
  selector:
    matchLabels:
      app: vpa-stress
  template:
    metadata:
      labels:
        app: vpa-stress
    spec:
      containers:
        - name: vpa-stress
          image: docker.io/elizabethla/vpa-stress:latest
          resources:
            limits:
              cpu: '1'
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 200Mi
```
Most `vpa-stress` pods will allocate between 100-160Mi of memory. The remaining 10% will allocate 650Mi of memory, causing OOM. If no OOM occurs after a couple of minutes, replace some pods to roll the dice again.

Turn up verbosity on the VPA updater:
```
containers:
  - name: updater
    args:
      - --v=4
```

Create a VPA for the Deployment:
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-stress
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
          - memory
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpa-stress
  updatePolicy:
    minReplicas: 1
    updateMode: Auto
```

Expect logs like this from the VPA updater:
```
I1228 16:14:47.820536       1 update_priority_calculator.go:114] quick OOM detected in pod vpa-stress-dev/vpa-stress-56b94449d8-w7r2h, container vpa-stress
I1228 16:14:47.820550       1 update_priority_calculator.go:140] not updating pod vpa-stress-dev/vpa-stress-56b94449d8-w7r2h because resource would not change
```

**Anything else we need to know?**:

VPA responds to OOM as expected when resource utilization across pods is uniform. As far as I can tell, the issue arises from the fact that only a small percentage of pods actually experience OOM. The target memory percentile of 90% is not affected by relatively infrequent OOM samples. This means that VPA never recommends a memory increase.

In applying VPA to a Daemonset such as the `datadog-agent` that may have non-uniform memory usage, I do not expect to reduce resource waste (all pods are subject to the same recommendation), but rather to reduce toil around manually adjusting the Daemonset's memory requests and limits as its requirements change with the workloads running on the cluster.

### PR DESCRIPTION
**Pull request by emla9**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Via flags on the recommender, make memory target percentile and upper/lower bounds for memory and CPU configurable. This allows the target percentile for memory and CPU to be set higher than 0.95 in order to accommodate workloads with significant outlier pods, such as some daemonsets. 

#### Which issue(s) this PR fixes:
Fixes #6420

#### Does this PR introduce a user-facing change?
```release-note
Added flags to specify targetMemoryPercentile, lowerBoundMemoryPercentile, upperBoundMemoryPercentile, lowerBoundCPUPercentile, and upperBoundCPUPercentile via command line arguments.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [Usage]: https://github.com/kubernetes/autoscaler/blob/f4c1ca1e38b19df784c360eea4390adbc790d2d9/vertical-pod-autoscaler/FAQ.md#what-are-the-parameters-to-vpa-recommender
```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @emla9
you have to sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check EasyCLA

/easycla

**Review by dbenque — COMMENTED** [review]
LGTM

**Comment by emla9** [comment]
Thanks for the review!

@voelzmo, I retested this with `vpa-stress` on one of our clusters: setting `--target-memory-percentile=1` and `--recommendation-upper-bound-memory-percentile=1` does fix the issue. 

My understanding was that each container instance's max per day gets added to the aggregate histogram and then the 90th percentile of that is used to calculate the target recommendation, which is different from adding only the max per day across all container instances in the workload.

**Comment by voelzmo** [comment]
Ah, thanks, I think I understand how setting the `target-memory-percentile` to 1 will help solving this issue – the high memory measurements caused by the OOMKill events will always be discarded when [selecting samples according to a percentile lower than 1](https://github.com/kubernetes/autoscaler/blob/3fd892a37b50a885eaceaa9619a1a3e153548dc9/vertical-pod-autoscaler/pkg/recommender/util/histogram.go#L159-L179).

Thanks!

**Comment by voelzmo** [comment]
@kwiesmueller This is good to go from my side, could you please `/approve`?

**Comment by prashantkalkar** [comment]
When will this be available? Unless this is release, overriding the `target-cpu-percentile` seems to be of now use (can't set it to higher than 0.95 if required).

**Pull request merged**
