### PR TITLE
Include helm chart version in cluster-autoscaler version matrix

### LINKED ISSUE #6539: Include helm chart version in cluster-autoscaler version matrix
First of all, thank you for preparing the Kubernetes vs CA version matrix. It really makes upgrading clusters faster and easier.

What would make the experience even better is if the version matrix could include helm chart versions as well,  similarly to how [ingress-nginx](https://github.com/kubernetes/ingress-nginx?tab=readme-ov-file#supported-versions-table) manages.

Currently, you have to go through multiple files/releases to find the supported version, which is a bit clunky, considering chart versioning doesn't mirror Kubernetes version like CA does.

### PR DESCRIPTION
**Pull request by mewa**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

This PR documents minimum required Helm chart versions to be used with specific cluster-autoscaler versions. It also adds a script that scans existing chart tags and updates README according to findings.

#### Which issue(s) this PR fixes:

Fixes #6539

### CODE REVIEW

**Comment by Shubham82** [comment]
@mewa, you have to sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by gjtempleton** [comment]
Hey, thanks for this.

Can you rebase, plus stick the script under the `hack` subdirectory of the cluster-autoscaler directory where we have other release related scripts please?

**Comment by mewa** [comment]
Sure @gjtempleton, I moved the script and rebased the changes.

**Comment by Shubham82** [comment]
@mewa
could you please resolve the failed test case?

**Comment by mewa** [comment]
@Shubham82 done.

**Pull request merged**
