### PR TITLE
Azure: Remove AKS vmType

### LINKED ISSUE #6190: Azure: "AKS" vmType no longer works
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.27.2

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"8b6cfe2c7c54ae110e0c2dbcc52b468bc08bf5f6", GitTreeState:"clean", BuildDate:"2023-07-28T22:18:46Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Azure AKS

**What did you expect to happen?**:

I expect to be able to install the cluster-autoscaler runtime w/ a vmType configuration of "AKS" on an AKS cluster

**What happened instead?**:

Configured node pools are not identified for proper scaling

**How to reproduce it (as minimally and precisely as possible)**:

```
$ helm install cluster-autoscaler cluster-autoscaler --repo https://kubernetes.github.io/autoscaler --set cloudProvider=azure --set autoscalingGroups[0].name=<name of pool>,autoscalingGroups[0].maxSize=100,autoscalingGroups[0].minSize=1 --set azureClientID=$TEST_AZURE_SP_ID --set azureClientSecret=$TEST_AZURE_SP_PW --set azureSubscriptionID=$TEST_AZURE_SUB_ID --set azureTenantID=$TEST_AZURE_TENANT_ID --set azureResourceGroup=<name of resource group> --set azureNodeResourceGroup=<name of node resource group> --set azureVMType=AKS --set azureClusterName=<name of AKS cluster>
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind deprecation
/kind documentation
/kind cleanup

#### What this PR does / why we need it:

This PR removes the obsolete, non-working implementation for manual AKS cluster integration as expressed via the `"aks"` `vmType` configuration.

Node autoscaling has long been a first class GA feature of AKS. See:

- https://docs.microsoft.com/azure/aks/autoscaler

Running the Azure cluster-autoscaler provider manually on your cluster is not a supported feature. To aid future maintainability of the project, we're removing these non-working code paths and updating documentation.

#### Which issue(s) this PR fixes:

Fixes #6190

#### Does this PR introduce a user-facing change?

```release-note
Azure: Remove AKS vmType
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
Validated "vmss" vmType on AKS cluster:

```
$ git status
On branch azure-aks-vmtype-deprecate
Your branch is up to date with 'origin/azure-aks-vmtype-deprecate'.

nothing to commit, working tree clean
$ TAG=$(git rev-parse --short HEAD) make build
rm -f cluster-autoscaler-amd64
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cluster-autoscaler-amd64 --ldflags "-s"
$ REGISTRY=docker.io/jackfrancis TAG=$(git rev-parse --short HEAD) make make-image
docker build --pull \
		-t docker.io/jackfrancis/cluster-autoscaler-amd64:5117ffbb1 \
		-f Dockerfile.amd64 .
[+] Building 4.7s (7/7) FINISHED                                                                                                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile.amd64                                                                                                                                                         0.0s
 => => transferring dockerfile: 866B                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                    0.0s
 => [internal] load metadata for gcr.io/distroless/static:nonroot-amd64                                                                                                                                            1.3s
 => [internal] load build context                                                                                                                                                                                  1.8s
 => => transferring context: 143.34MB                                                                                                                                                                              1.8s
 => [1/3] FROM gcr.io/distroless/static:nonroot-amd64@sha256:5f1b35fe0293eebf6e574ee21d43a0ad55beb99e7384427216f5f18eaa9d5077                                                                                      2.0s
 => => resolve gcr.io/distroless/static:nonroot-amd64@sha256:5f1b35fe0293eebf6e574ee21d43a0ad55beb99e7384427216f5f18eaa9d5077                                                                                      0.0s
 => => sha256:5f1b35fe0293eebf6e574ee21d43a0ad55beb99e7384427216f5f18eaa9d5077 1.65kB / 1.65kB                                                                                                                     0.0s
 => => sha256:694e6e1059dbd66c240aa4001290e5a56cea3024d9f11e4361e721b054cc2df1 1.28kB / 1.28kB                                                                                                                     0.0s
 => => sha256:07a64a71e01156f8f99039bc246149925c6d1480d3957de78510bbec6ec68f7a 103.74kB / 103.74kB                                                                                                                 0.3s
 => => sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58 21.20kB / 21.20kB                                                                                                                   0.3s
 => => sha256:b02a7525f878e61fc1ef8a7405a2cc17f866e8de222c1c98fd6681aff6e509db 716.49kB / 716.49kB                                                                                                                 0.4s
 => => extracting sha256:07a64a71e01156f8f99039bc246149925c6d1480d3957de78510bbec6ec68f7a                                                                                                                          0.0s
 => => sha256:e8c73c638ae9ec5ad70c49df7e484040d889cca6b4a9af056579c3d058ea93f0 198B / 198B                                                                                                                         0.5s
 => => sha256:fcb6f6d2c9986d9cd6a2ea3cc2936e5fc613e09f1af9042329011e43057f3265 317B / 317B                                                                                                                         0.4s
 => => extracting sha256:fe5ca62666f04366c8e7f605aa82997d71320183e99962fa76b3209fdfbb8b58                                                                                                                          0.0s
 => => extracting sha256:b02a7525f878e61fc1ef8a7405a2cc17f866e8de222c1c98fd6681aff6e509db                                                                                                                          1.1s
 => => sha256:1e3d9b7d145208fa8fa3ee1c9612d0adaac7255f1bbc9ddea7e461e0b317805c 113B / 113B                                                                                                                         0.5s
 => => sha256:4aa0ea1413d37a58615488592a0b827ea4b2e48fa5a77cf707d0e35f025e613f 385B / 385B                                                                                                                         0.6s
 => => sha256:7c881f9ab25e0d86562a123b5fb56aebf8aa0ddd7d48ef602faf8d1e7cf43d8c 355B / 355B                                                                                                                         0.7s
 => => sha256:5627a970d25e752d971a501ec7e35d0d6fdcd4a3ce9e958715a686853024794a 130.56kB / 130.56kB                                                                                                                 0.7s
 => => extracting sha256:fcb6f6d2c9986d9cd6a2ea3cc2936e5fc613e09f1af9042329011e43057f3265                                                                                                                          0.0s
 => => extracting sha256:e8c73c638ae9ec5ad70c49df7e484040d889cca6b4a9af056579c3d058ea93f0                                                                                                                          0.0s
 => => extracting sha256:1e3d9b7d145208fa8fa3ee1c9612d0adaac7255f1bbc9ddea7e461e0b317805c                                                                                                                          0.0s
 => => extracting sha256:4aa0ea1413d37a58615488592a0b827ea4b2e48fa5a77cf707d0e35f025e613f                                                                                                                          0.0s
 => => extracting sha256:7c881f9ab25e0d86562a123b5fb56aebf8aa0ddd7d48ef602faf8d1e7cf43d8c                                                                                                                          0.0s
 => => extracting sha256:5627a970d25e752d971a501ec7e35d0d6fdcd4a3ce9e958715a686853024794a                                                                                                                          0.0s
 => [2/3] COPY cluster-autoscaler-amd64 /cluster-autoscaler                                                                                                                                                        0.7s
 => exporting to image                                                                                                                                                                                             0.6s
 => => exporting layers                                                                                                                                                                                            0.6s
 => => writing image sha256:4e5f36b4a97a14cc80e76eb7f0e386527d1f73fcdad7a6ac315a0fed92d6782c                                                                                                                       0.0s
 => => naming to docker.io/jackfrancis/cluster-autoscaler-amd64:5117ffbb1                                                                                                                                          0.0s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
Image 5117ffbb1-amd64 completed
$ helm install cluster-autoscaler cluster-autoscaler --repo https://kubernetes.github.io/autoscaler --set cloudProvider=azure --set autoscalingGroups[0].name=aks-pool1-28343662-vmss,autoscalingGroups[0].maxSize=100,autoscalingGroups[0].minSize=0 --set azureClientID=$TEST_AZURE_SP_ID --set azureClientSecret=$TEST_AZURE_SP_PW --set azureSubscriptionID=$TEST_AZURE_SUB_ID --set azureTenantID=$TEST_AZURE_TENANT_ID --set azureResourceGroup=MC_capz-e2e-ntrn0h-aks_capz-e2e-ntrn0h-aks_eastus --set azureVMType=vmss --set image.repository=docker.io/jackfrancis/cluster-autoscaler-amd64 --set image.tag=$(git rev-parse --short HEAD)
NAME: cluster-autoscaler
LAST DEPLOYED: Tue Oct 10 16:27:56 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that cluster-autoscaler has started, run:

  kubectl --namespace=default get pods -l "app.kubernetes.io/name=azure-cluster-autoscaler,app.kubernetes.io/instance=cluster-autoscaler"
```

**Comment by jackfrancis** [comment]
@gjtempleton am I doing the right or wrong thing updating the helm chart (and bumping the version) in this PR? Or would we prefer to separate the helm changes from the underlying code changes?

**Comment by jackfrancis** [comment]
/hold

while I work on a possible fix

**Comment by jackfrancis** [comment]
Current plan is to move forward w/ this.

cc @prachirp @tallaxes 

I shared a PSA about this in SIG Autoscaling weekly meeting today. I'll wait a week or so to allow for public feedback, then I'll press for a final review and merge.

**Review by Bryce-Soghigian — APPROVED** [review]

**Review by tallaxes — APPROVED** [review]

**Comment by jackfrancis** [comment]
@gjtempleton is this PR ready to merge in terms of helm chart updates?

Chart changes + new minor version change are in this PR.

Thanks!

**Comment by Shubham82** [comment]
@gjtempleton could you please approve this PR, so that it will merge?
Thanks!

**Comment by gjtempleton** [comment]
Looks good to me from the chart side.

thanks!
/approve

**Pull request merged**
