### PR TITLE
[cherry-pick] Add ASG MixedInstancesPolicy Support 1.13

### PR DESCRIPTION
**Pull request by danigrmartinez**
Related to 1.14 release cherrypick PR https://github.com/kubernetes/autoscaler/pull/2013

This is a cherrypick of the two PR. Code and documentation from @drewhemm
#1886
#1983

### CODE REVIEW

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!

**Comment by losipiuk** [comment]
@danigrmartinez for this one tests are failing. Please fix :)
/lgtm cancel

**Comment by Jeffwan** [comment]
Looks like aws sdk doesn't have MixedInstancePolicy support at this moment. Let me double verify it.

**Comment by danigrmartinez** [comment]
@Jeffwan you are right. The versions of the AWS cli is not compatible with the new feature:

For 1.13
```
		{
			"ImportPath": "github.com/aws/aws-sdk-go/aws",
			"Comment": "v1.14.12",
			"Rev": "fde4ded7becdeae4d26bf1212916aabba79349b4"
		},
```

for 1.14:
```
		{
			"ImportPath": "github.com/aws/aws-sdk-go/aws",
			"Comment": "v1.16.26-2-g6f009370",
			"Rev": "6f009370adb66b6023fcea53c6aa8e93682b7151"
		},
```

In that case, I don't think we should include this on 1.13 or 1.12.

**Comment by danigrmartinez** [comment]
Closing this because aws sdk version is not compratible with MixedInstancePolicy support

**Comment by Jeffwan** [comment]
@danigrmartinez  I remember the aws sdk version comes from kubernetes/kubernetes. If that's the true, there's a dependency and we can not easily upgrade it. Let me double check

**Pull request closed without merging**
