### PR TITLE
Add OCI instance-pool based cloud provider 

### PR DESCRIPTION
**Pull request by jlamillan**
Hello Community,

This pull-request adds support for a node autoscaler for Oracle Cloud Infrastructure (OCI) that uses [Instance Pools](https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/creatinginstancepool.htm) 
combined with [Instance Configurations](https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/creatinginstanceconfig.htm). 

It's currently being used internally as well as by a couple of early access customers who are using it in combination with Rancher/RKE. We'd like to subset it here for broader community use.

It has the basic support you would expect - automatically adjusting the number of instances in the configured instance pool(s) based on Kubernetes resource, affinity, requirements, etc.

We're here if you have any questions!

### CODE REVIEW

**Comment by jlamillan** [comment]
FYI @ericrrath

**Comment by EladGabay** [comment]
Hey, any plans to merge this soon? :) @jlamillan

**Comment by mwielgus** [comment]
We don't accept any new dependencies for new cloud providers. Please put all required dependencies into you cloud provider directory.

**Comment by mwielgus** [comment]
Moreover, inside OWNERS, please comment out people who are not in K8S organization. So that we pass globally imposed validation and know who to contact for reviews.

**Comment by jlamillan** [comment]
> We don't accept any new dependencies for new cloud providers. Please put all required dependencies into you cloud provider directory.

All files and the OCI SDK are _already_ stored in `cluster-autoscaler/cloudprovider/oci/` directory. Was there something else you were referring to?

**Comment by jlamillan** [comment]
> Moreover, inside OWNERS, please comment out people who are not in K8S organization. So that we pass globally imposed validation and know who to contact for reviews.

commented out.

**Comment by EladGabay** [comment]
@jlamillan hey, is it possible to use "nodepool" instead of "instancepool"?
I mean, the same as in https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by EladGabay** [comment]
@jlamillan Congrats :)
Any plans to add nodepool option instead of instance-pool?
Thanks!

**Comment by jlamillan** [comment]
@EladGabay checkout OKE nodepool autoscaler here: 
https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm

**Comment by EladGabay** [comment]
@jlamillan thanks, I already use that version. I'm looking for its source code so I'll able to add some modification to my use case. Any chance to get it?

**Comment by jlamillan** [comment]
@EladGabay 

I believe that team has plans to release it at some point, but it is not available yet.

**Pull request merged**
