### PR TITLE
feat(tencentcloud): remove dependency on tke interface

### PR DESCRIPTION
**Pull request by alphajc**
#### What type of PR is this?

/kind feature

Enable the open source cluster-autoscaler to run normally without relying on the TKE distribution.

### CODE REVIEW

**Comment by alphajc** [comment]
Plz @mwielgus @BigDarkClown @feiskyer

**Comment by BigDarkClown** [comment]
@alphajc I don't have context on `tencentcloud` cloudprovider specific changes. Changes which are entirely in the cloudprovider scope should be handled by cloudprovider owners. I see that there are no owners set for this provider, that's why this PR requires CA wide owners approval. Could we add some owners to this provider dir?

**Comment by alphajc** [comment]
> @alphajc I don't have context on `tencentcloud` cloudprovider specific changes. Changes which are entirely in the cloudprovider scope should be handled by cloudprovider owners. I see that there are no owners set for this provider, that's why this PR requires CA wide owners approval. Could we add some owners to this provider dir?

yes, thx

**Comment by alphajc** [comment]
> @alphajc I don't have context on `tencentcloud` cloudprovider specific changes. Changes which are entirely in the cloudprovider scope should be handled by cloudprovider owners. I see that there are no owners set for this provider, that's why this PR requires CA wide owners approval. Could we add some owners to this provider dir?

@BigDarkClown of course, thx

**Comment by alphajc** [comment]
@BigDarkClown Please help and see if there are any other issues that need to be addressed

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
