### PR TITLE
rancher-cloudprovider: Improve node group discovery

### LINKED ISSUE #5140: Cannot deploy cluster-autoscaler with Rancher RKE2
**Which component are you using?**:
cluster-autoscaler / cluster-autoscaler-chart

**What version of the component are you using?**:

Component version:
[cluster-autoscaler1.23.1](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.23.1) / [cluster-autoscaler-chart-9.20.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-9.20.0)

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+rke2r2", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-28T19:13:01Z", GoVersion:"go1.17.9b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.23) exceeds the supported minor version skew of +/-1
</pre></details>

**What environment is this in?**:
Dev

**What did you expect to happen?**:
Cluster Autoscaler to deploy with Helm chart to my Rancher RKE2 cluster after the changes from [PR 4975](https://github.com/kubernetes/autoscaler/pull/4975).

**What happened instead?**:
This error in the cluster autoscaler pod logs:
```shell
F0829 00:36:25.149073 1 main.go:430] Failed to get nodes from apiserver: nodes is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "nodes" in API group "" at the cluster scope
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Rancher API key (in my case, not restrictions)
2. Create Opaque Secret with you Rancher cloud-config:
<details><pre>
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |
    # rancher server credentials
    url: https://rancher.domain.com
    token: [Redacted: token-*:*]
    # name and namespace of the clusters.provisioning.cattle.io resource on the
    # rancher server
    clusterName: my-cluster
    clusterNamespace: fleet-default
    # optional, will be auto-discovered if not specified
    #clusterAPIVersion: v1alpha4
</pre></details>
3. Use the below helm values:
<details><pre>
autoDiscovery:
  clusterName: my-cluster
  labels: []
  roles:
    - worker
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}
cloudProvider: rancher
extraVolumeSecrets:
  cluster-autoscaler-cloud-config:
    mountPath: /config
    name: cluster-autoscaler-cloud-config
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  cloud-config: /config/cloud-config
  cluster-name: my-cluster
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  tag: v1.23.1
</pre></details>

**Anything else we need to know?**:
On Rancher 2.6.7 with RKE2 1.23.x.
Tried to deploy to downstream and management clusters (both on RKE2 1.23.x)

I am wondering if something is wrong in reading my deployed cloud-config?

### PR DESCRIPTION
**Pull request by ctrox**
#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Previsouly the rancher provider tried to parse the node `spec.providerID` to extract the node group name. Instead, we now get the machines by the node name and then use a rancher specific label that should always be on the machine. This should work more reliably for all the different node drivers that rancher supports.

#### Which issue(s) this PR fixes:

Fixes #5140

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x13n** [comment]
/lgtm

Although for changes like this I think it would make more sense to uncomment entries in your OWNERS file, so that rancher-specific changes can be reviewed & approved by the people listed there.

**Comment by ctrox** [comment]
Agreed, but aren't OWNERS required to be members of the Kubernetes org? If so, I guess I'm looking for 2 sponsors ;)

**Comment by x13n** [comment]
Ah, good point. I guess after reviewing this PR I could qualify as one. You'd still need someone else, from another company.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
