### PR TITLE
Add EC2 instance type p5.48xlarge

### PR DESCRIPTION
**Pull request by ricardov1**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Enables the use of p5.48xlarge instances in node groups

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by ricardov1** [comment]
@x13n @MaciekPytel @mwielgus I see the release schedule for the cluster autoscaler shows a planned patch release for 11/15. Is this release still scheduled for tomorrow? If not, could I get an estimate on when this will be released? Thank you!

**Comment by x13n** [comment]
@ricardov1  Yes, I'm planning to start the patch releases this week (today/tomorrow). If you want this change to be included, can you create a PR to appropriate release branches? This one targeted `master`, so without cherrypicks it will end up in 1.29, not patch release.

**Comment by ricardov1** [comment]
@x13n awesome, thanks for clarifying! here is a PR against the `cluster-autoscaler-release-1.28` branch with the commit cherry-picked. https://github.com/kubernetes/autoscaler/pull/6283

let me know if this doesn't look right or if you need anything else before releasing the patch, it is important that this is included in the patch :)

**Comment by ricardov1** [comment]
@x13n the following PRs into the 1.25-1.28 cluster autoscaler release branches have been merged. will a new cluster autoscaler docker image be published as part of this patch release?

https://github.com/kubernetes/autoscaler/pull/6286
https://github.com/kubernetes/autoscaler/pull/6287
https://github.com/kubernetes/autoscaler/pull/6285
https://github.com/kubernetes/autoscaler/pull/6283

**Comment by x13n** [comment]
Yes, docker images will be published as a part of the release. Created https://github.com/kubernetes/autoscaler/issues/6293 to track the release. Note that I'm not planning to release 1.25 version since it is already outside of k8s support window: https://kubernetes.io/releases/

**Pull request merged**
