### PR TITLE
Add support for Azure Managed Service Identity (MSI)

### LINKED ISSUE #711: Document Azure MSI support
Azure's [Managed Service Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview) is supported as an alternative to utilizing a service principal for the authorization to the backend Azure cloud provider. This is a request to support MSI in the Azure autoscaler in addition to the current service principal.

If accepted, this task would be added to this list: https://github.com/kubernetes/autoscaler/issues/449

### PR DESCRIPTION
**Pull request by feiskyer**
This PR adds support for Azure Managed Service Identity (MSI). It also updates azure compute client to api version 2017-12-01, which is required to set ipforwarding for virtual machines. 

Fixes #711.

### CODE REVIEW

**Comment by feiskyer** [comment]
@mwielgus  thanks

**Comment by jcrowthe** [comment]
@feiskyer It looks like this PR didn't make it into v1.2.1 -- Was that intentional?

**Comment by feiskyer** [comment]
@jcrowthe  The cherry-pick #805 has been merged, but we missed the time. It will be included in next release.

**Pull request merged**
