### PR TITLE
Add the AppVersion to labels as app.kubernetes.io/version

### PR DESCRIPTION
**Pull request by jw-maynard**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
It adds the AppVersion of the Helm chart to the common labels as the recommended standard label `app.kubernetes.io/version`

#### Which issue(s) this PR fixes:

Fixes None

#### Does this PR introduce a user-facing change?

```release-note
Adds the app.kubernetes.io/version label to all resources with a value equal to the AppVersion of the chart.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
A similar PR opened previously but was not merged due to unsign easyCLA, Here is the following PR:#5874

**Comment by jw-maynard** [comment]
@gjtempleton @mwielgus any chance of getting this reviewed? Thanks

**Comment by gjtempleton** [comment]
Sorry for the delay on this, thanks for the PR!

/lgtm
/approve

**Comment by gjtempleton** [comment]
@Shubham82 can you please give this a final review and lgtm if it looks good as I've now contributed to the PR as well. Thanks.

**Pull request merged**
