### PR TITLE
Remove kawych, piosz and x13n from Addon Resizer OWNERS

### PR DESCRIPTION
**Pull request by kawych**

### CODE REVIEW

**Comment by piosz** [comment]
Please add a replacement.

**Comment by kawych** [comment]
I assume this falls into OWNERS from here: https://github.com/kubernetes/autoscaler/blob/master/OWNERS

Adding @aleksandra-malinowska as well (I saw some activity from her on this repo). @bskiba @aleksandra-malinowska please let me know if I should add more people.

**Comment by mwielgus** [comment]
un-lgtm

@aleksandra-malinowska sorry, i was under impression that @piosz discussed this change with you and you agreed.

**Comment by kawych** [comment]
Done, need lgtm to merge

**Pull request merged**
