### PR TITLE
add missing GPU counts for p2 instance types

### PR DESCRIPTION
**Pull request by rushtehrani**
Add the missing GPU counts for [p2 instances types](https://aws.amazon.com/ec2/instance-types/)

### CODE REVIEW

**Comment by rushtehrani** [comment]
Also see: https://github.com/kubernetes/autoscaler/pull/322#issuecomment-330006231, I can update this PR to address that.

**Comment by sethpollack** [comment]
@rushtehrani `ec2_instance_types.go` is generated by `ec2_instance_types/gen.go` which pulls the info from the AWS price list for each region https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-west-2/index.json

The price list is missing the `gpu` info for some of the instances which is why that info is missing here. 

It also includes the prefixes as per your comment, which we can technically filter out.

**Comment by rushtehrani** [comment]
Thanks, that make sense now.  Should've read the comment on top of `ec2_instance_types.go`. I'm assuming those GPUs are missing from that json, but I'll look into it.

**Comment by sethpollack** [comment]
Yeah, they are, I wish there was a better source for this info.

**Comment by rushtehrani** [comment]
I checked a couple of different regions, some have the prefix, some don't, but they were all missing `gpu` info for those instance types.

**Comment by innovia** [comment]
This PR wont work because the gen.go will overwrite the ec2 instance types file every time 

You need to make a map and iterate over the p2 family like i posted on my comment this way they will be generated when running a build

**Comment by rushtehrani** [comment]
Closing this, we can continue the discussion in the other PR.

**Pull request closed without merging**
