### PR TITLE
Cluster Autoscaler 1.13.2

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by feiskyer** [comment]
Seems this version is still not cut yet?

**Comment by losipiuk** [comment]
> Seems this version is still not cut yet?

Will send it out in couple of hours. Waiting for one internal review.

**Comment by losipiuk** [comment]
Released https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.13.2

**Pull request merged**
