### PR TITLE
Update VPA dependencies to k8s 1.16.2

### LINKED ISSUE #2447: VerticalPodAutoscaler not compatible with k8s 1.16.x libraries
We, in kube-state-metrics use the VPA and K8s client libaries as dependencies. We seem to be blocked on updating to K8s 1.16.x libraries as the VPA dependencies fail to compile when importing the latest K8s deps.

As seen on this thread: https://github.com/kubernetes/kube-state-metrics/pull/945#issuecomment-540711969

### PR DESCRIPTION
**Pull request by bskiba**
- Adds VPA update dependencies script, based on the one from Cluster Autoscaler, to make updates work with go modules.
- Updates dependencies to 1.16.2
- Updates the generated API code with a code generator for version 1.16.2
- Necessary changes to e2e tests after update
- Small change to admission controller (Webhook -> MutatingWebhook)

Fixes #2447

### CODE REVIEW

**Comment by tariq1890** [comment]
Any updates on this PR? Would love to see this merged :).

**Comment by bskiba** [comment]
@jbartosik Would you mind reviewing?

**Comment by bskiba** [comment]
Thanks!

**Pull request merged**
