### PR TITLE
Add revisionHistoryLimit override to cluster-autoscaler

### PR DESCRIPTION
**Pull request by olibenni**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Allows us to override revisionHistoryLimit.

#### Which issue(s) this PR fixes:
Nothing

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @olibenni 
Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by gjtempleton** [comment]
Hey, thanks for the PR.

You'll need to bump the chart version and regenerate the chart readme to get the tests to pass. The pre-commit hooks we have set up would pick both of these up: https://github.com/kubernetes/autoscaler/tree/master/charts#pre-commit-hooks

**Comment by Shubham82** [comment]
@olibenni, Please address the above comment of @gjtempleton so that the failed tests will pass.

**Comment by Shubham82** [comment]
@olibenni are you working on this PR,  if YES then please addressed the above comment so that PR will merge,

**Comment by olibenni** [comment]
Going to close this as I am currently not working on this

**Pull request closed without merging**
