### PR TITLE
updated IAM policy resource section with aws arn for autoscaling

### PR DESCRIPTION
**Pull request by amila-ku**
Updated the IAM policy to have resources specified as AWS arn based syntax for auto scaling groups.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@amila-ku Can you update your commit so that github can recognize your account? We can't merge any contributions if they don't come from a github user who agreed to CLA.

**Comment by amila-ku** [comment]
I signed the CNCF contributor agreement yesterday.

**Comment by amila-ku** [comment]
image
but it still does not seem to identify the user associated. I have verified email in github also

**Comment by MaciekPytel** [comment]
Maybe you have different email in your github account and in your commit?

**Comment by mwielgus** [comment]
cc: @mumoshu

**Comment by mumoshu** [comment]
@amila-ku Hi! Thanks for your contribution.

AFAIK, the AWS doc explicitly states that you should provide `*` to actions that doesn't support resource-level permissions.

> For actions that don't support resource-level permissions, you must use "*" as the resource.
> 
> "Resource": "*"

ref: http://docs.aws.amazon.com/autoscaling/latest/userguide/control-access-using-iam.html#policy-auto-scaling-resources

Just curious but wouldn't AWS reject e.g. DescribeAutoScalingGroups calls by restricting resources like this?

**Comment by amila-ku** [comment]
@mumoshu thanks for pointing that out, i have missed that part on 3 describe actions which does not support specifying resource types.

**Pull request closed without merging**
