### PR TITLE
Receive v1beta2 VPAs

### PR DESCRIPTION
**Pull request by jbartosik**

### CODE REVIEW

**Comment by bskiba** [comment]
The master branch does not support v1beta1 already, so I think we can just switch instead of supporting both.

**Comment by jbartosik** [comment]
/hold
It needs also to subscribe for updates on v1beta2 VPAs.

**Comment by jbartosik** [comment]
> The master branch does not support v1beta1 already, so I think we can just switch instead of supporting both.

Done.

**Pull request merged**
