### PR TITLE
add prom scrap annotations

### PR DESCRIPTION
**Pull request by ggaaooppeenngg**
add prometheus scrape annotations for metrics gathering

/assign @jeffwan

Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

### CODE REVIEW

**Comment by losipiuk** [comment]
Please improve commit message (capital letter, full words, ...) 
https://chris.beams.io/posts/git-commit/

**Comment by ggaaooppeenngg** [comment]
@losipiuk  done

**Comment by losipiuk** [comment]
scrape not scrap :)

Please make it "Add Prometheus scrape annotations to example manifests"

**Comment by ggaaooppeenngg** [comment]
Sorry, I've changed it.

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
