### PR TITLE
Add required IAM action 'autoscaling:DescribeLaunchConfigurations' to AWS readme

### PR DESCRIPTION
**Pull request by temal-**
Hi,

I rant into the following error when starting with an empty ASG on AWS:
```
Failed LaunchConfiguration info request for ASG_NAME: AccessDenied: User: arn:aws:sts::1234567890:assumed-role/ROLE_NAME/INSTANCE_ID is not authorized to perform: autoscaling:DescribeLaunchConfigurations
```

Reference: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/auto_scaling.go#L51-L55

The issue was resolved after adding the `autoscaling:DescribeLaunchConfigurations` action to the IAM policy.

### CODE REVIEW

**Comment by Jeffwan** [comment]
@temal- If you see the documentation, we have a section talking about scaling from 0, this has been covered. Adding to basic configuration is not a bad idea. Thanks for the contribution.

**Comment by temal-** [comment]
@Jeffwan Oh no, I haven't seen that. Thanks for pointing that out!
I'd say we revert that commit so the example policy stays as minimal as possible. Also, right now it seems a bit odd that this action is mention again in the scaling from 0 paragraph.

**Comment by 2rs2ts** [comment]
@Jeffwan why did adding DescribeLaunchConfigurations fix the problem for @temal- when that is not your documented solution?

**Comment by 2rs2ts** [comment]
Also we ran into this behavior when all our ASGs had 1 node and then we deployed CA, I don't know if this is exclusive to scaling from 0.

**Comment by Jeffwan** [comment]
> @Jeffwan why did adding DescribeLaunchConfigurations fix the problem for @temal- when that is not your documented solution?
> 
> Also we are not using `nodeSelector` from what I can tell, we use `--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/<environment>` when launching CA. So the documentation does not make clear what the node label in your documentation is supposed to be for our use case.

I assume the `nodeSelector` mention here is from `Scaling a node group to 0` section.  If your pod is using `nodeSelector`, since there's 0 node and CA can not find a template, it need to check LaunchConfiguration. We tag ASG and CA will fetch ASG tags and converts tags to labels. Then, the node group can pass predicates and be qualified for scale up. 

Could you share some CA logs and CA version you are using? If you already have nodes there, LC permission should not be necessary.

**Comment by 2rs2ts** [comment]
@Jeffwan 

```
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler  status code: 403, request id: b8e80eac-78cf-11e9-8917-137f47ffa809
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.764326       1 static_autoscaler.go:128] Starting main loop
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.874513       1 auto_scaling_groups.go:320] Regenerating instance to ASG map for ASGs: [kube-worker-qa-us-east-2a kube-worker-qa-us-east-2b kube-worker-qa-us-east-2c]
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.919384       1 aws_manager.go:152] Refreshed ASG list, next refresh after 2019-05-17 18:15:36.919377766 +0000 UTC m=+107.903513392
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.919480       1 static_autoscaler.go:177] 6 unregistered nodes present
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.919541       1 static_autoscaler.go:261] Filtering out schedulables
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.920211       1 static_autoscaler.go:271] No schedulable pods
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.920239       1 scale_up.go:262] Pod atmosphere/atmosphere-7f4bb65fc4-s496l is unschedulable
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.920245       1 scale_up.go:262] Pod atmosphere/atmosphere-7f4bb65fc4-drxzj is unschedulable
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.920250       1 scale_up.go:262] Pod atmosphere/atmosphere-bfcd7d7c8-ntd7r is unschedulable
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:26.920254       1 scale_up.go:262] Pod atmosphere/atmosphere-7f4bb65fc4-7d4vd is unschedulable
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler I0517 18:15:27.015642       1 auto_scaling.go:48] Failed LaunchConfiguration info request for qa_kube-worker_20190419170721963200000002: AccessDenied: User: arn:aws:sts::<account number>:assumed-role/cluster-autoscaler/kiam-kiam is not authorized to perform: autoscaling:DescribeLaunchConfigurations
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler  status code: 403, request id: befb1496-78cf-11e9-8c60-b7ca60e96d83
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler E0517 18:15:27.015668       1 utils.go:274] Unable to build proper template node for kube-worker-qa-us-east-2a: AccessDenied: User: arn:aws:sts::<account number>:assumed-role/cluster-autoscaler/kiam-kiam is not authorized to perform: autoscaling:DescribeLaunchConfigurations
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler  status code: 403, request id: befb1496-78cf-11e9-8c60-b7ca60e96d83
cluster-autoscaler-84fd566f8c-pnbgw cluster-autoscaler E0517 18:15:27.015685       1 static_autoscaler.go:312] Failed to scale up: failed to build node infos for node groups: AccessDenied: User: arn:aws:sts::<account number>:assumed-role/cluster-autoscaler/kiam-kiam is not authorized to perform: autoscaling:DescribeLaunchConfiguration
```

We are using 1.13.1 right now. And we don't specify nodeSelectors at all on our pod templates, for what it's worth.

We launch with `--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/qa`.

**Comment by Jeffwan** [comment]
@2rs2ts I think the problem here is you are using kiam. I am not familiar with it and as I remember it 
hijack request to EC2 manifest server. You probably need to double check your settings.

If you see codes here, it only run `DescribeLaunchConfigurations ` when there's no node available in that ASG.

https://github.com/kubernetes/autoscaler/blob/cb4e60f8d4ffb7f0836509e65ba6270738f1e15c/cluster-autoscaler/core/utils.go#L256-L258

**Comment by 2rs2ts** [comment]
@Jeffwan no the problem is not kiam, if it was then CA wouldn't work in general. We had to add `autoscaling:DescribeLaunchConfigurations` to the IAM policy to fix our problem.

**Comment by Jeffwan** [comment]
@2rs2ts I cleaned up all my envs and retried, seem it's go the call. You are right, this should be minimum policies. Thanks for confirmation. I will double check the code logic.

**Pull request merged**
