### PR TITLE
Cleanup ProvReq wrapper

### PR DESCRIPTION
**Pull request by yaroslava-serdiuk**
#### What type of PR is this?

/kind cleanup

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by towca** [comment]
/lgtm
/approve
/hold

The change itself LGTM, but I'm wondering about the motivation behind it. It seems like the wrapper was designed as a translation layer between different ProvReq API versions. Do you think this won't be needed after all? What happens when we introduce v1 ProvReq?

**Comment by yaroslava-serdiuk** [comment]
/unhold

API is unlikely to change much, but there are a lot of code duplication in current version of wrapper.

**Comment by yaroslava-serdiuk** [comment]
#6814

**Pull request merged**
