### PR TITLE
Fix: failed forbidden Jobs

### PR DESCRIPTION
**Pull request by reinaldo-pinto**
Adding rules needed of the Jobs on file to work.

### CODE REVIEW

**Comment by bskiba** [comment]
Thanks for the contribution. Please sign the CLA so we can merge this.

**Comment by Jeffwan** [comment]
Can you update all examples?

**Comment by mwielgus** [comment]
Please sign SLO

**Comment by mwielgus** [comment]
Friendly ping, please sign CLA.

**Comment by reinaldo-pinto** [comment]
Hello my friend, already signed in CLA. 
Thanks

**Comment by reinaldo-pinto** [comment]
Hi, @Jeffwan I already added the changes in all files. 
Thank you.

**Pull request merged**
