### PR TITLE
CA: add artifacts for dev testing of cluster-autoscaler on AKS

### PR DESCRIPTION
**Pull request by charliedmcb**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
This PR adds the required artifacts, and documentation for testing of cluster-autoscaler changes within a dev environment on an AKS cluster.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
While this is mostly meant to support the https://github.com/Azure/autoscaler repo dev environment, I think this is valuable to have upstream in the https://github.com/kubernetes/autoscaler repo for others to see the process for testing in a dev environment, and can be leveraged as a base for setting up ones own tests.

Testing:
- For testing, I setup a codespace within `azure/autoscaler`, transferred to the `main` branch of this repo, and then used the artifacts to setup a running instance of autoscaler on the aks cluster in my codespace.
- Same steps as I've documented in the README

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @charliedmcb
you have to sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check EasyCLA

/easycla

**Comment by charliedmcb** [comment]
> Hi @charliedmcb you have to sign the CLA before the PR can be reviewed. See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

Thanks! I have completed the CLA.

**Pull request merged**
