### PR TITLE
Improves unit test code coverage for azure_manager.go

### PR DESCRIPTION
**Pull request by weijiehu**
Improves unit test code coverage for azure_manager.go

/kind cleanup

/sig cloud-provider
/area provider/azure
/priority important-soon

### CODE REVIEW

**Comment by nilo19** [comment]
something goes wrong during verify, not sure what happened from the log. could you run `hack/verify-all.sh` to check?

**Comment by weijiehu** [comment]
ok, I will check it.

**Comment by weijiehu** [comment]
travis fail, seems an CI env issue:
```
$ hack/verify-all.sh -v
Skipping hack/../hack/verify-all.sh
Verifying hack/../hack/verify-boilerplate.sh
SUCCESS
Verifying hack/../hack/verify-gofmt.sh
Unable to find image 'golang:1.13.5' locally
1.13.5: Pulling from library/golang
8f0fdd3eaac0: Pulling fs layer
d918eaefd9de: Pulling fs layer
43bf3e3107f5: Pulling fs layer
27622921edb2: Pulling fs layer
f862a94ee651: Pulling fs layer
ff0de9db1ab2: Pulling fs layer
a4db81ef5640: Pulling fs layer
27622921edb2: Waiting
f862a94ee651: Waiting
ff0de9db1ab2: Waiting
a4db81ef5640: Waiting
d918eaefd9de: Verifying 
```

**Comment by nilo19** [comment]
@weijiehu you could close and reopen your pr to trigger the re-check.

**Comment by weijiehu** [comment]
sure, I am re-trigger the CI with forcing push the commit.

**Pull request merged**
