### PR TITLE
AWS Scaling from/to 0, extract GPU information

### LINKED ISSUE #321: Scaling up from 0 nodes on AWS, CA not aware of custom resources
When **scaling up from 0 nodes** on AWS, how can I make cluster-autoscaler aware of custom resources on the nodes, such as "alpha.kubernetes.io/nvidia-gpu"? 

Using kops 1.7.0, kubernetes 1.7.5, cluster-autoscaler 0.6.1, when I have 0 nodes running, starting a job with "resources: limits: alpha.kubernetes.io/nvidia-gpu: 1" results in CA inaction due to (note "Insufficient alpha.kubernetes.io/nvidia-gpu"):

```
I0909 03:36:26.255878       1 scale_up.go:50] Pod default/0dd3d1fc-3e73-90e7-84e0-f24009dc3784-08t94 is unschedulable
I0909 03:36:26.351319       1 scale_up.go:71] Upcoming 0 nodes
I0909 03:36:26.385779       1 scale_up.go:112] Scale-up predicate failed: GeneralPredicates predicate mismatch, cannot put default/0dd3d1fc-3e73-90e7-84e0-f24009dc3784-08t94 on template-node-for-nodes.uswest2.metamoto.net-7573953041833664557, reason: Insufficient alpha.kubernetes.io/nvidia-gpu
I0909 03:36:26.385809       1 scale_up.go:141] No pod can fit to %snodes.uswest2.metamoto.net
I0909 03:36:26.385819       1 scale_up.go:146] No expansion options
...
I0909 02:55:41.381017       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"2f0b2cb6-782b-f2e6-4c3c-c37f648f45b2-6fhl2", UID:"21a5fb02-94fe-11e7-beff-06c6424932c2", APIVersion:"v1", ResourceVersion:"7436", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

It looks like the "template-node-for-nodes" doesn't have the resources listed. However if I start a job without the gpu requirement, a node is spun up, and then I can start the original gpu job and it gets scheduled on the node! The node looks like this (kubectl describe nodes) (note "alpha.kubernetes.io/nvidia-gpu: 1"):

```
Name:			ip-172-31-121-22.us-west-2.compute.internal
Role:
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=g2.2xlarge
			beta.kubernetes.io/os=linux
			failure-domain.beta.kubernetes.io/region=us-west-2
			failure-domain.beta.kubernetes.io/zone=us-west-2a
			kubernetes.io/hostname=ip-172-31-121-22.us-west-2.compute.internal
			kubernetes.io/role=node
			node-role.kubernetes.io/node=
Annotations:		node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			<none>
CreationTimestamp:	Fri, 08 Sep 2017 19:57:32 -0700
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  NetworkUnavailable 	False 	Fri, 08 Sep 2017 19:57:37 -0700 	Fri, 08 Sep 2017 19:57:37 -0700 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Fri, 08 Sep 2017 20:06:43 -0700 	Fri, 08 Sep 2017 19:57:32 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Fri, 08 Sep 2017 20:06:43 -0700 	Fri, 08 Sep 2017 19:57:32 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 	Fri, 08 Sep 2017 20:06:43 -0700 	Fri, 08 Sep 2017 19:57:32 -0700 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		True 	Fri, 08 Sep 2017 20:06:43 -0700 	Fri, 08 Sep 2017 19:57:52 -0700 	KubeletReady 			kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:	172.31.121.22
  ExternalIP:	34.213.162.221
  InternalDNS:	ip-172-31-121-22.us-west-2.compute.internal
  ExternalDNS:	ec2-34-213-162-221.us-west-2.compute.amazonaws.com
  Hostname:	ip-172-31-121-22.us-west-2.compute.internal
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	1
 cpu:					8
 memory:				15399064Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	1
 cpu:					8
 memory:				15296664Ki
 pods:					110
System Info:
 Machine ID:			2118324e509d4582ae925c3ed83d8f2a
 System UUID:			EC2DF760-2914-FF5B-B89E-6B85AEF7C8C2
 Boot ID:			984a55a1-ca22-45cb-9c17-39f71e8315cb
 Kernel Version:		4.4.0-1017-aws
 OS Image:			Ubuntu 16.04.2 LTS
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.6
 Kubelet Version:		v1.7.5
 Kube-Proxy Version:		v1.7.5
PodCIDR:			100.96.3.0/24
ExternalID:			i-04de825c788bf994e
Non-terminated Pods:		(2 in total)
  Namespace			Name								CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----								------------	----------	---------------	-------------
  default			93caffb3-2868-a526-8810-2ddc0dd1140a-fv5t4			100m (1%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-proxy-ip-172-31-121-22.us-west-2.compute.internal		100m (1%)	0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  200m (2%)	0 (0%)		0 (0%)		0 (0%)
```

New nodes are also spun up correctly as long as there is already at least 1 node running. Any idea how to make the "template" for nodes list the correct resources? Thanks!

### PR DESCRIPTION
**Pull request by sethpollack**
fixes #321

### CODE REVIEW

**Comment by 7chenko** [comment]
Confirmed these changes work!

**Comment by mwielgus** [comment]
cool!

**Comment by innovia** [comment]
P2.xlarge is a GPU instance why is it set to 0?

**Comment by innovia** [comment]
Also p2.8xlarge has 4 gpus

**Comment by rushtehrani** [comment]
https://github.com/kubernetes/autoscaler/pull/352 will fix the missing GPU counts

**Comment by rushtehrani** [comment]
Also, is there a reason that new instance types only contain the prefix of the instance type name? i.e. `p2`, `g3`

**Pull request merged**
