### PR TITLE
Backport #5596 [CA] AWS - Add support for tags on AWS managed nodegroups to indicate resources into CA 1.26

### PR DESCRIPTION
**Pull request by ClareCat**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

This PR is cherry-picked, which backports https://github.com/kubernetes/autoscaler/pull/5596 into CA 1.26

#### Does this PR introduce a user-facing change?

```release-note
Allow k8s.io/cluster-autoscaler/resources/<resource>:<quantity> tags on AWS managed nodegroups (in addition to ASGs) to indicate availability of custom resources or ephemeral storage in a scale-from-zero scenario
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
#5596 merged in CA 1.28 so you have to backport it to CA 1.27 also.

**Comment by ClareCat** [comment]
1.27 backport added: https://github.com/kubernetes/autoscaler/pull/6241

**Pull request merged**
