### PR TITLE
Move command-line flags to a new file flags.go

### PR DESCRIPTION
**Pull request by jayantjain93**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Currently the flag declaration is coupled with main.go, which should only care about execution.
With this change, we're decoupling flags with main.go, to provide extensibility for cloud-providers to integrate config to execution better.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by azylinski — APPROVED** [review]
LGTM

**Comment by x13n** [comment]
Thanks for the change! Could you move the flags out of the root directory? Ultimately, flags are one mean of building autoscaler configuration (a config file would be another one, which was discussed on SIG some time ago), so ultimately I'd like to see them be used to build some kind of internal configuration object. For now, I'd just wrap them into a package not to bloat the scope of this PR too much.

**Comment by x13n** [comment]
Closing for now, please reopen if you still plan to work on this.

/close

**Pull request closed without merging**
