### PR TITLE
cherry-pick least-nodes expander from #6792 into 1.28

### PR DESCRIPTION
**Pull request by com6056**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Cherry-picks https://github.com/kubernetes/autoscaler/pull/6792 into the 1.28 release.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Added a new `least-nodes` expander
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by com6056** [comment]
@Shubham82 anything blocking this, https://github.com/kubernetes/autoscaler/pull/7136, and https://github.com/kubernetes/autoscaler/pull/7137 from being merged? Or will it be merged right before the release?

**Comment by Shubham82** [comment]
> @Shubham82 anything blocking this, #7136, and #7137 from being merged? Or will it be merged right before the release?

Hi @com6056, To merge PRs, it needs approval (`/approve` label) from the approver.

**Comment by Shubham82** [comment]
cc @BigDarkClown @x13n 
Could you please approve these PRs So that they can merge?

Thanks!

**Pull request merged**
