### PR TITLE
Fix expectedToRegister to respect instances with nil status

### PR DESCRIPTION
**Pull request by yarinm**
Fix for https://github.com/kubernetes/autoscaler/issues/6524

### CODE REVIEW

**Comment by x13n** [comment]
Thanks!

/approve

**Comment by Shubham82** [comment]
@yarinm
you have to sign the CLA, to merge the PR.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check EasyCLA

/easycla

**Comment by yarinm** [comment]
@Shubham82 I'm waiting for the legal department on the firm I'm working for this, I hope to get the necessary approvals in the new few days

**Comment by yarinm** [comment]
@Shubham82 We've signed the CLA, can you please merge the PR?

**Comment by tallaxes** [comment]
Shouldn't this be cherry-picked into 1.28 and 1.29?

**Comment by Shubham82** [comment]
@tallaxes, I think we can fix this in the previous supported releases.
Let's wait for other members' opinions.

**Comment by Shubham82** [comment]
@tallaxes I will open PRs to backport this fix into CA 1.28 and CA 1.29.

**Comment by Shubham82** [comment]
JFI: I have raised the following PR:
For CA 1.28 #6892
For CA 1.29 #6893

**Pull request merged**
