### PR TITLE
Rollback OOM tests

### PR DESCRIPTION
**Pull request by jbartosik**
Tests I added in #2952 are failing when running on prow because pods are stuck pending. Roll back the change

### CODE REVIEW

**Comment by jbartosik** [comment]
Pods are stuck pending ([full log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-full/1245355492188884993)):

```
I0401 14:53:31.684] STEP: Running OOMing RC hamster with 3 replicas
I0401 14:53:31.685] STEP: Creating deployment hamster in namespace vertical-pod-autoscaling-9358
I0401 14:53:31.736] I0401 14:53:31.736067   40825 runners.go:184] Created deployment with name: hamster, namespace: vertical-pod-autoscaling-9358, replica count: 3
I0401 14:53:41.787] I0401 14:53:41.787024   40825 runners.go:184] hamster Pods: 3 out of 3 created, 0 running, 3 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
(...)
I0401 14:55:41.795] I0401 14:55:41.794842   40825 runners.go:184] hamster Pods: 3 out of 3 created, 0 running, 3 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0401 14:55:41.833] I0401 14:55:41.833269   40825 runners.go:184] Pod hamster-575796747d-9hhnb	bootstrap-e2e-minion-group-6cb1	Pending	<nil>
I0401 14:55:41.834] I0401 14:55:41.833455   40825 runners.go:184] Pod hamster-575796747d-bt7nb	bootstrap-e2e-minion-group-zrl5	Pending	<nil>
I0401 14:55:41.834] I0401 14:55:41.833469   40825 runners.go:184] Pod hamster-575796747d-txsrr	bootstrap-e2e-minion-group-zrl5	Pending	<nil>
I0401 14:55:41.834] Apr  1 14:55:41.833: FAIL: Unexpected error:
I0401 14:55:41.834]     <*errors.errorString | 0xc000aea200>: {
I0401 14:55:41.835]         s: "Only 0 pods started out of 3",
I0401 14:55:41.835]     }
I0401 14:55:41.835]     Only 0 pods started out of 3
I0401 14:55:41.835] occurred
```

**Comment by krzysied** [comment]
Do we know why it is not working?

**Comment by jbartosik** [comment]
@krzysied 
> Do we know why it is not working?

Not yet. We don't log info about pods that didn't start. I'll add the log. And then recreate the issue to see what's the prolem

**Comment by krzysied** [comment]
```
E0401 14:53:33.130294    1379 remote_image.go:113] PullImage "gcr.io/jbartosik-gke-dev/stress:0.10" from image service failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jbartosik-gke-dev/stress, repository does not exist or may require 'docker login': denied: Permission denied for "0.10" from request "/v2/jbartosik-gke-dev/stress/manifests/0.10".
E0401 14:53:33.130421    1379 kuberuntime_manager.go:801] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jbartosik-gke-dev/stress, repository does not exist or may require 'docker login': denied: Permission denied for "0.10" from request "/v2/jbartosik-gke-dev/stress/manifests/0.10".
E0401 14:53:33.130472    1379 pod_workers.go:191] Error syncing pod d55872ad-a17c-4c1c-a9fb-68c4ada6da1e ("hamster-575796747d-9hhnb_vertical-pod-autoscaling-9358(d55872ad-a17c-4c1c-a9fb-68c4ada6da1e)"), skipping: failed to "StartContainer" for "hamster" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jbartosik-gke-dev/stress, repository does not exist or may require 'docker login': denied: Permission denied for \"0.10\" from request \"/v2/jbartosik-gke-dev/stress/manifests/0.10\"."
```

**Comment by jbartosik** [comment]
> ```
> E0401 14:53:33.130294    1379 remote_image.go:113] PullImage "gcr.io/jbartosik-gke-dev/stress:0.10" from image service failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jbartosik-gke-dev/stress, repository does not exist or may require 'docker login': denied: Permission denied for "0.10" from request "/v2/jbartosik-gke-dev/stress/manifests/0.10".
> E0401 14:53:33.130421    1379 kuberuntime_manager.go:801] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jbartosik-gke-dev/stress, repository does not exist or may require 'docker login': denied: Permission denied for "0.10" from request "/v2/jbartosik-gke-dev/stress/manifests/0.10".
> E0401 14:53:33.130472    1379 pod_workers.go:191] Error syncing pod d55872ad-a17c-4c1c-a9fb-68c4ada6da1e ("hamster-575796747d-9hhnb_vertical-pod-autoscaling-9358(d55872ad-a17c-4c1c-a9fb-68c4ada6da1e)"), skipping: failed to "StartContainer" for "hamster" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/jbartosik-gke-dev/stress, repository does not exist or may require 'docker login': denied: Permission denied for \"0.10\" from request \"/v2/jbartosik-gke-dev/stress/manifests/0.10\"."
> ```
> 
> This seems like an issue...

Thank you. So we're logging but logs appear later than I expected :)

**Comment by krzysied** [comment]
Actually this is from kubelet log: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-full/1245355492188884993/artifacts/bootstrap-e2e-minion-group-6cb1/kubelet.log

We have logs for each node. If there is problem with pod it's good to check scheduler log and then kubelet log from the node the pod was assigned to.

**Pull request merged**
