### PR TITLE
Regenerate azure static sku list for 1.30

### PR DESCRIPTION
**Pull request by rakechill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Regenerates the static sku list that acts as a fallback mechanism for dynamic listing

#### Special notes for your reviewer:
I compared against the output for `az vm --list-skus -o json`. The memory updates + deprecated types are accurate.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rakechill** [comment]
accidentally had master as the base branch at first. updated to 1.30 release branch

**Comment by rakechill** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/87990209/7112/#/?version=2)
> 
> * ✅ login: k8s-ci-robot / name: Kubernetes Prow Robot  ([ce1913e](https://github.com/kubernetes/autoscaler/commit/ce1913e5f05d670ea8c30b45e6a6aed6e62e9818), [f83dde0](https://github.com/kubernetes/autoscaler/commit/f83dde072ab652664f3ac55704e34ae861fe44db), [55a18a3](https://github.com/kubernetes/autoscaler/commit/55a18a301ee939a04980dd50a07064eda46aa537), [bf7bbda](https://github.com/kubernetes/autoscaler/commit/bf7bbda1ffa7ae3f9597999513a1b79270988fe8), [9d69082](https://github.com/kubernetes/autoscaler/commit/9d69082864f9a8efbeac3223d6068319a6b08277), [6e3217d](https://github.com/kubernetes/autoscaler/commit/6e3217da104884bdfd9d0d60453be9e060f7dae5), [6b838f5](https://github.com/kubernetes/autoscaler/commit/6b838f528ed291aed447f2b6195a83644def01f8), [a304cf0](https://github.com/kubernetes/autoscaler/commit/a304cf0cacceb6377153e80b91c81402467692f2), [0ed4b01](https://github.com/kubernetes/autoscaler/commit/0ed4b0151b29cda2d22046e771fd7008ad35bcf6), [71fd226](https://github.com/kubernetes/autoscaler/commit/71fd2261ef94577849102022c8ecbdfa02f91893), [2c2660a](https://github.com/kubernetes/autoscaler/commit/2c2660a28cc842a74bb39e4810a901f0ba572939), [a2840cd](https://github.com/kubernetes/autoscaler/commit/a2840cd98906ce8dbdf258f60ef055996bee294a), [1d8645c](https://github.com/kubernetes/autoscaler/commit/1d8645c0501d81fdb22e0d1ea802d9249c73820c), [4d3a2b8](https://github.com/kubernetes/autoscaler/commit/4d3a2b8e8178f96c0120e83c587aeaa3b1e49c3d), [16fb610](https://github.com/kubernetes/autoscaler/commit/16fb610b4a39e3f52b923b9731c175b1b36c7c27), [a0fce3c](https://github.com/kubernetes/autoscaler/commit/a0fce3ce1c7961911ec1f77fcf4c894b0eb18080), [a86bb30](https://github.com/kubernetes/autoscaler/commit/a86bb304646de7c394d4c8a0a16625bc33100e17), [a928d75](https://github.com/kubernetes/autoscaler/commit/a928d756d2dc27d00d78f5f6095c45073d8b7c76), [7d1f87f](https://github.com/kubernetes/autoscaler/commit/7d1f87fcfd64228ad81acb847960e4a58eb265cc), [4b7085c](https://github.com/kubernetes/autoscaler/commit/4b7085c2731b6956ba3ce439cbcbbcec77b06c09))
> * ✅ login: aleksandra-malinowska / name: Aleksandra Malinowska  ([b100791](https://github.com/kubernetes/autoscaler/commit/b1007913b0071245998b9a59a901c375931ef3de), [c74f2df](https://github.com/kubernetes/autoscaler/commit/c74f2df3d61c3fd88a3808c3ef9a608936abd5f5), [a6ce449](https://github.com/kubernetes/autoscaler/commit/a6ce449e5fdfd8f1629480342f00bec4f25c1703), [12374e6](https://github.com/kubernetes/autoscaler/commit/12374e6c786f27c470b31daf19b0e06b6a961fcd), [d9eecae](https://github.com/kubernetes/autoscaler/commit/d9eecaef41c8a757f362c28c8ad49f1ba1808269), [fbcdf07](https://github.com/kubernetes/autoscaler/commit/fbcdf0705e091c99bc30606afb4fe0b7ca00ab1c), [b2334d9](https://github.com/kubernetes/autoscaler/commit/b2334d901225f81ab513a0aedb80eb6909f3fe6f), [c19aac1](https://github.com/kubernetes/autoscaler/commit/c19aac12ca5b27ac877eacb398b715e56fce2154))
> * ✅ login: towca / name: Kuba Tużnik  ([c4f7524](https://github.com/kubernetes/autoscaler/commit/c4f7524043f050fc93bee0939566b3dc4edc8d8f), [f652e25](https://github.com/kubernetes/autoscaler/commit/f652e253c841818086649e7e27b55cd9408f4c4d))
> * ✅ login: Shubham82 / name: Shubham  ([2708de3](https://github.com/kubernetes/autoscaler/commit/2708de3bea10617920df746349a450b144753010))
> * ✅ login: apricote / name: Julian Tölle  ([f23d5b7](https://github.com/kubernetes/autoscaler/commit/f23d5b7c0ad575ec75f028eff4c33c8bb0e8b6e0), [3a26603](https://github.com/kubernetes/autoscaler/commit/3a26603300f28eee6a020dc7a661d7ba622def38))
> * ✅ login: kmsarabu  ([a51b870](https://github.com/kubernetes/autoscaler/commit/a51b8707355ddbd923c548b3ea2e32ad2af85996))
> * ✅ login: yaroslava-serdiuk / name: Yaroslava Serdiuk  ([8171e34](https://github.com/kubernetes/autoscaler/commit/8171e34a8429034b91ad38d0149daecf764b85bc), [0a0adb7](https://github.com/kubernetes/autoscaler/commit/0a0adb758f919dcd6ceacc05322993531c4d78aa), [5cf4771](https://github.com/kubernetes/autoscaler/commit/5cf477183ec7d6ade5ed63cf07e6cbca7504264c), [9367938](https://github.com/kubernetes/autoscaler/commit/93679382f13eda30c24c63da97ba859f3751f8aa))
> * ✅ login: gjtempleton / name: Guy Templeton  ([343373a](https://github.com/kubernetes/autoscaler/commit/343373ab93846a902871e1efe4f6b1bcf7418dbd))
> * ✅ login: BigDarkClown / name: Bartek Wróblewski  ([00a09b7](https://github.com/kubernetes/autoscaler/commit/00a09b7c6e1199dba5553f270a4e192e3e99c205))
> * ✅ login: rakechill / name: Rachel Gregory  ([7e4b145](https://github.com/kubernetes/autoscaler/commit/7e4b145b81a02d9cce6d6e98afc5796cd374ddf4))
> * ✅ login: comtalyst / name: Robin D.  ([dc88846](https://github.com/kubernetes/autoscaler/commit/dc88846a9a28a28d93841faa612fef5c67240a5b), [7aaa034](https://github.com/kubernetes/autoscaler/commit/7aaa034f976b48ac618fb3f4dfb105df9b23dd62), [f0dccb8](https://github.com/kubernetes/autoscaler/commit/f0dccb8df3092a503e7b84b678ec25ff929bd317))
> * ✅ login: x13n / name: Daniel Kłobuszewski  ([b7a28b2](https://github.com/kubernetes/autoscaler/commit/b7a28b2ff357c35f7b576d746c98a2bcbf2dff93))
> * ✅ login: kisieland  ([e0dd21a](https://github.com/kubernetes/autoscaler/commit/e0dd21ab3debd29cf3b21ac653c049eb7f5d4e24))
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/87990209/7112/#/?version=2) - login: @k8s-infra-cherrypick-robot . The commit ([79027cd](https://github.com/kubernetes/autoscaler/commit/79027cd696137e3b08ddb6fe448636d6cd942b30)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/87990209/7112/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

bummer... since I accidentally had master as my base branch when I created the PR, easyCLA ran on all of the commits that were different between my branch (based off of 1.30) and master. One of these was a cherry-commit which I don't have permissions to run...

**Comment by tallaxes** [comment]
> bummer... since I accidentally had master as my base branch when I created the PR, easyCLA ran on all of the commits that were different between my branch (based off of 1.30) and master. One of these was a cherry-commit which I don't have permissions to run...

Fixed

**Pull request merged**
