### PR TITLE
Fix for VPA e2e vendor update

### PR DESCRIPTION
**Pull request by bskiba**
Currently e2e tests are failing with
go: inconsistent vendoring in /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/e2e

### CODE REVIEW

**Comment by krzysied** [comment]
I'm wondering why presubmit tests didn't catch it?
https://github.com/kubernetes/autoscaler/blob/master/hack/for-go-proj.sh#L68 sh

**Comment by bskiba** [comment]
Depends on which go version Travis is using.

**Comment by bskiba** [comment]
Hm, it's using 1.14 so it should have caught it...

**Pull request merged**
