### PR TITLE
Fix Markdown link to k8s-node-drainer

### PR DESCRIPTION
**Pull request by TBBle**

### CODE REVIEW

**Comment by TBBle** [comment]
Dagnabbit. I forgot about the CNCF CLA. Chasing it up on my end.

**Comment by TBBle** [comment]
/assign @TBBle

So I don't forget to come back when the CCLA is signed.

**Comment by TBBle** [comment]
I'll follow-up when the CCLA is signed, to avoid churn on the issue.

**Comment by Jeffwan** [comment]
You need a CLA and rebase the change. Thanks @TBBle

**Comment by Jeffwan** [comment]
@TBBle Did you get a chance to update it?

**Comment by TBBle** [comment]
Looks like I'm still having CLA issues.

**Comment by Jeffwan** [comment]
Are you willing to figure out the CLA issue? If you feel like signing CLA is too verbose, I can help make this change.

**Comment by mwielgus** [comment]
@TBBle Please sign the CLA. Otherwise we won't be able to merge this PR and I will have to close it.

**Comment by TBBle** [comment]
I've signed it. However, (on another PR) it seems the bot is not picking up the signature. I was trying to get it resolved there first.

**Comment by TBBle** [comment]
I signed it

**Comment by TBBle** [comment]
I've raised a [support ticket](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-2351) to try and get the CLA issue resolved.

**Comment by mwielgus** [comment]
Closing for now. Please reopen once you get CLA sorted out.

**Comment by TBBle** [comment]
I signed it. I can't reopen it (I don't see a button...) but that should be much easier.

**Comment by TBBle** [comment]
Ah, after all that, it was fixed in #3492 in the meantime. Oh well, at least the CLA is signed now.

**Pull request closed without merging**
