### PR TITLE
Register packet provider in all builder

### PR DESCRIPTION
**Pull request by sbs2001**
This adds packet provider in the Available cloud provider list.

### CODE REVIEW

**Comment by sbs2001** [comment]
any idea on why the bot added the test label, but never ran the tests ?

**Comment by jayantjain93** [comment]
Maintainer needs to add okay-to-test or approve for the tests to run as first time contributor

**Comment by sbs2001** [comment]
@jayantjain93   tests are passing. What else is missing ?

**Comment by jayantjain93** [comment]
you need a maintainer to approve the changes.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
