### PR TITLE
fix(cluster-autoscaler-chart): if secretKeyRefNameOverride is true, d…

### PR DESCRIPTION
**Pull request by jonwraymond**
…on't create secret

Don't create secret if `secretKeyRefNameOverride` is used

/kind bug 

#### What this PR does / why we need it:

Don't create secret if `secretKeyRefNameOverride` is used in the helm chart for cluster autoscaler.

Fixes #

#### Special notes for your reviewer:

Clean up so no extra secret is created unnecessarily.

#### Does this PR introduce a user-facing change?
```None

```

### CODE REVIEW

**Comment by Shubham82** [comment]
@jonwraymond, Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check EasyCLA

/easycla

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
