### PR TITLE
Split Verification & Test in seperate stage in Travis

### PR DESCRIPTION
**Pull request by asifdxtreme**

### CODE REVIEW

**Comment by mwielgus** [comment]
This PR causes some scary compilation problems. Please fix.

**Comment by asifdxtreme** [comment]
Preview
image

**Comment by asifdxtreme** [comment]
@mwielgus yes there was some problem in the way travis was trigerring the calls, now it is fixed and the CI is green, please review the changes

**Comment by mwielgus** [comment]
Please squash commits to 1 or 2.  
5 (with some of them sharing the same name) is a bit too much.

**Comment by asifdxtreme** [comment]
@mwielgus Thanks for the suggestion, I have rebased all my commits into 1

**Comment by asifdxtreme** [comment]
@mwielgus Can you please help me to merge this PR

**Pull request merged**
