### PR TITLE
Merge pull request #3570 from towca/jtuznik/scale-down-after-delete-fix

### PR DESCRIPTION
**Pull request by ryaneorth**
Remove ScaleDownNodeDeleted status since we no longer delete nodes synchronously

### CODE REVIEW

**Comment by ryaneorth** [comment]
Cherry picking changes from #3570  into 1.19

**Comment by MaciekPytel** [comment]
It seems the test failure is in clusterapi and it's completely unrelated to the actual change. The same seems to be the case for https://github.com/kubernetes/autoscaler/pull/3598. 

Tagging Cluster API provider owners for help. @frobware @enxebre @elmiko @hardikdr @detiber @ncdc

**Comment by ncdc** [comment]
@benmoss

**Comment by elmiko** [comment]
@MaciekPytel thanks for highlighting that, i've taken a quick look at the test feels and it seems like we might have some sort of race condition there. i'll keep poking around.

**Comment by ryaneorth** [comment]
@MaciekPytel - can we merge this and #3598 since the failing tests are unrelated to the change?

**Comment by elmiko** [comment]
i'm not quite sure how yet, but this change (and #3598) are responsible for breaking the capi tests. granted, this could be an error in the capi implementation, but when i run the capi unit tests from master i see no issues:

```
$ stress ./clusterapi.test -test.run=TestControllerNodeGroups -test.cpu=10                                                                                     
24 runs so far, 0 failures                                                                                                                                     
48 runs so far, 0 failures                                                                                                                                     
74 runs so far, 0 failures                                                                                                                                     
100 runs so far, 0 failures                                                                                                                                    
124 runs so far, 0 failures                                                                                                                                    
152 runs so far, 0 failures                                                                                                                                    
176 runs so far, 0 failures                                                                                                                                    
200 runs so far, 0 failures                                                                                                                                    
228 runs so far, 0 failures                                                                                                                                    
252 runs so far, 0 failures                                                                                                                                    
280 runs so far, 0 failures                                                                                                                                    
304 runs so far, 0 failures                                                                                                                                    
332 runs so far, 0 failures                                                                                                                                    
358 runs so far, 0 failures                                                                                                                                    
384 runs so far, 0 failures                                                                                                                                    
408 runs so far, 0 failures                                                                                                                                    
```

but when i switch to this branch, i immediately get errors:

```
$ stress ./clusterapi.test -test.run=TestControllerNodeGroups -test.cpu=10      

/tmp/go-stress-20201013T160931-966456074
I1013 16:09:31.702318 2330419 clusterapi_controller.go:334] Using version "v1alpha3" for API group "cluster.x-k8s.io"
I1013 16:09:31.703114 2330419 clusterapi_controller.go:411] Resource "machinedeployments" available
--- FAIL: TestControllerNodeGroups (0.11s)
    clusterapi_controller_test.go:1023: expected 0, got 6
I1013 16:09:31.813386 2330419 clusterapi_controller.go:334] Using version "v1alpha3" for API group "cluster.x-k8s.io"
I1013 16:09:31.813404 2330419 clusterapi_controller.go:411] Resource "machinedeployments" available
I1013 16:09:31.917005 2330419 clusterapi_controller.go:334] Using version "v1alpha3" for API group "cluster.x-k8s.io"
I1013 16:09:31.917031 2330419 clusterapi_controller.go:411] Resource "machinedeployments" available
I1013 16:09:32.020654 2330419 clusterapi_controller.go:334] Using version "v1alpha3" for API group "cluster.x-k8s.io"
I1013 16:09:32.020686 2330419 clusterapi_controller.go:411] Resource "machinedeployments" available
I1013 16:09:32.122008 2330419 clusterapi_controller.go:334] Using version "v1alpha3" for API group "cluster.x-k8s.io"
I1013 16:09:32.122030 2330419 clusterapi_controller.go:411] Resource "machinedeployments" available
I1013 16:09:32.222599 2330419 clusterapi_controller.go:334] Using version "v1alpha3" for API group "cluster.x-k8s.io"
I1013 16:09:32.222622 2330419 clusterapi_controller.go:411] Resource "machinedeployments" available
I1013 16:09:32.326754 2330419 clusterapi_controller.go:334] Using version "v1alpha3" for API group "cluster.x-k8s.io"
I1013 16:09:32.326833 2330419 clusterapi_controller.go:411] Resource "machinedeployments" available
FAIL


ERROR: exit status 1
```

**Comment by elmiko** [comment]
just to make sure i didn't miss anything, i also ran the tests against the head of the release-1.19 branch

```
$ stress ./clusterapi.test -test.run=TestControllerNodeGroups -test.cpu=10
24 runs so far, 0 failures
52 runs so far, 0 failures
76 runs so far, 0 failures
104 runs so far, 0 failures
132 runs so far, 0 failures
160 runs so far, 0 failures
185 runs so far, 0 failures
212 runs so far, 0 failures
240 runs so far, 0 failures
264 runs so far, 0 failures
292 runs so far, 0 failures
316 runs so far, 0 failures
344 runs so far, 0 failures
368 runs so far, 0 failures
395 runs so far, 0 failures
420 runs so far, 0 failures
```

**Comment by ryaneorth** [comment]
Thanks @elmiko ! I also don't see any reason why this change would cause these tests to fail.

**Comment by elmiko** [comment]
@ryaneorth i'm not sure exactly why it's causing the failure, i can probably do a little more digging tomorrow or perhaps on tuesday.

**Comment by ryaneorth** [comment]
thanks! I'll also try to dig in a bit

**Comment by elmiko** [comment]
ok, figured this out. i _thought_ it sounded familiar in the beginning but it didn't occur to me until i noticed the backports.

we need to cherry pick #3441 as well to ensure that those tests work in 1.19. i'm not sure about the failures in 1.18, but it might be needed there as well since we backported the unstructured changes to the cluster-api provider.

**Comment by ryaneorth** [comment]
Great find @elmiko ! I've submitted two new PRs for backporting #3441 to 1.18 and 1.19:

#3612
#3613

**Comment by ryaneorth** [comment]
CLA signed

**Comment by ryaneorth** [comment]
CLA signed

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
