### PR TITLE
docs(rancher): clarify single RKE2 target

### LINKED ISSUE #7148: Clarification of CA Rancher Provider capabilities
**Which component are you using?**: 

**CA Rancher Provider**

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

The documentation for the [Rancher Provider](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/rancher/README.md) states, emphasis mine:

> This cluster autoscaler for Rancher scales nodes in *clusters* which use RKE2 provisioning (Rancher v2.6+). It uses a combination of the Rancher API and the underlying cluster-api types of RKE2.

> The cluster-autoscaler can be run inside the RKE2 cluster, on the *Rancher server cluster* or on a completely separate machine. To run it outside the RKE2 cluster, make sure to provide a kubeconfig with --kubeconfig.

My reading of this is that CA can be deployed to a Rancher server in order to scale RKE2 *clusters* that Rancher creates. But the example `cloud-config`  implies that only a single RKE2 cluster can be targeted for scaling using `clusterName` and `clusterNamespace`

```yaml
# rancher server credentials
url: https://rancher.example.org
token: <rancher token>
# name and namespace of the clusters.provisioning.cattle.io resource on the
# rancher server
clusterName: my-cluster
clusterNamespace: fleet-default
# optional, will be auto-discovered if not specified
#clusterAPIVersion: v1alpha4
```
There is no mention of any autodiscovery capabilities or configuration for the Rancher Provider, even though it seems to share some similarities to the CAPI Provider.
 
**Describe the solution you'd like.**:

- Clarification in the documentation stating that either
  a. The Rancher Provider can only scale a single cluster
  b. The Rancher Provider can scale multiple *clusters*
    - Documentation on how this is achieved.
- More specificity in the example `cloud-config`. For example `clusterName: rancher-server-cluster` or `clusterName: rke2-cluster`. 

**Describe any alternative solutions you've considered.**:

**Additional context.**:

### PR DESCRIPTION
**Pull request by ctrox**
Clarify that a cluster-autoscaler instance can target a single RKE2 cluster.

#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

Fixes #7148

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks @ctrox
/lgtm

**Comment by Shubham82** [comment]
cc @feiskyer
Need your approval to merge this PR.

PTAL!

**Review by vadasambar — APPROVED** [review]

**Comment by vadasambar** [comment]
@gjtempleton we might need your approval here

**Comment by Shubham82** [comment]
cc @gjtempleton,
Need your approval to merge this PR, PTAL.

Thanks!

**Review by feiskyer — COMMENTED** [review]
/approve

**Pull request merged**
