### PR TITLE
Cherry pick of #1071: Upgrade AKS API to 2018-03-31

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #1071: Upgrade AKS API to 2018-03-31 to CA release-1.3

### CODE REVIEW

**Comment by feiskyer** [comment]
ping @aleksandra-malinowska @MaciekPytel

**Comment by feiskyer** [comment]
ping @MaciekPytel @aleksandra-malinowska Any updates?

**Comment by feiskyer** [comment]
ping @MaciekPytel @aleksandra-malinowska

**Comment by aleksandra-malinowska** [comment]
Yes, we used go1.0 for 1.3. 

/lgtm

**Pull request merged**
