### PR TITLE
Magnum Provider: nodegroup name is unique

### PR DESCRIPTION
**Pull request by dioguerra**
#### Which component this PR applies to?

magnum cluster-autoscaler

#### What type of PR is this?
/feature

#### What this PR does / why we need it:
This was originally a PR to 'fix' something that didnt need to be fixed. Further testing showed that the cluster I had was not configured properly, so I droped one of my commits and will only contribute to update the magnum gophercloud src code.

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @tghartland

**Comment by tghartland** [comment]
Hi @dioguerra!

Is there a specific bit of work in gophercloud that is linked to this, or just keeping up to date?
Looks like it's to version v1.0.0, based on the changelog file.

I had a go doing the update myself (I had a [tool](https://github.com/tghartland/gophercloud-vendorer) for this), and the code that I get is identical to yours.
My diff also removed the `.travis.yml` and `.zuul.yaml` files as these no longer exist in the gophercloud repo, but those are just extra files.

The diff as a whole looks ok. Have you tried building and running in a cluster?

**Comment by x13n** [comment]
Should this be merged or closed?

**Comment by mwielgus** [comment]
@tghartland - ping, should we merge it or not?

**Comment by tghartland** [comment]
I was waiting to hear back from @dioguerra if he'd tested this running in a cluster - from the original description it doesn't sound like this is strictly necessary so I'm not opposed to closing.

**Comment by mwielgus** [comment]
Closing then, feel free to reopen if needed.

**Pull request closed without merging**
