### PR TITLE
Update go used to build VPA to 1.19.5

### PR DESCRIPTION
**Pull request by jbartosik**
/kind cleanup

For #5455

### CODE REVIEW

**Comment by voelzmo** [comment]
If we're going to specify the builder images like this, should we include a step to ensure we're using the latest go image version in https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md, regardless of why we're creating a new release?

**Comment by jbartosik** [comment]
> If we're going to specify the builder images like this, should we include a step to ensure we're using the latest go image version in https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md, regardless of why we're creating a new release?

Yes, this sounds like a good idea.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
