### PR TITLE
CA: add NodeInfo to Rule.Drainable interface

### PR DESCRIPTION
**Pull request by towca**

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks, @towca for this PR.
/kind feature

/lgtm

**Comment by Shubham82** [comment]
@towca, I think we can backport these changes into supported CA releases. Your thoughts on this?

**Comment by towca** [comment]
@Shubham82 I'm not sure there's reason to, on its own the change shouldn't really do anything. It only allows the drainability rules to access the nodeInfo for the potentially drained node, but none of the in-tree rules currently do that. Am I missing something here?

**Comment by Shubham82** [comment]
> Am I missing something here?

@towca, No, you are right but I just wondering if we can add the node Information(for drainability rules) of the drained node for the previous release. If this sounds not good, then we can skip this.

Thanks!

**Comment by towca** [comment]
I think there's no need to unless we have a bugfix to backport that would require it. Thanks for being vigilant about backporting though!

**Comment by Shubham82** [comment]
I agree with you, It makes sense.
Thanks @towca

**Pull request merged**
