### PR TITLE
build for azure e2e tests with only azure provider

### PR DESCRIPTION
**Pull request by nojnhuh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR adjusts builds for cluster-autoscaler in Azure e2e tests to only build with the `azure` provider. This should reduce build times and give slightly more overall test coverage for building for specific providers.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
/lgtm

@nojnhuh thank you! I'm not sure if the 1.27 cherry-pick command works any longer (if it does go ahead and proactively close it as the 1.27 support window is closed.

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve

**Comment by nojnhuh** [comment]
test is green!

/hold cancel

**Pull request merged**
