### PR TITLE
OCI OKE autoscaller requires Updated Set of permissions. 

### PR DESCRIPTION
**Pull request by JanisOrlovs**
OCI OKE auto scaler requires an updated set of permissions. 

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

This PR changes the default permissions needed to run OCI OKE auto scaler examples.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
cc: @jlamillan since this is about OCI and not core CA

@JanisOrlovs Unfortunately we cannot accept any PR unless you sign the CLA.

**Comment by JanisOrlovs** [comment]
> cc: @jlamillan since this is about OCI and not core CA
> 
> @JanisOrlovs Unfortunately we cannot accept any PR unless you sign the CLA.

Hello,

Signed CLA

**Review by jlamillan — APPROVED** [review]
Looks good to me.

**Comment by Shubham82** [comment]
as @jlamillan approved the changes, giving LGTM.
/lgtm

**Pull request merged**
