### PR TITLE
[cherry-pick] Add ASG MixedInstancesPolicy Support 1.12

### PR DESCRIPTION
**Pull request by danigrmartinez**
Related to 1.14 release cherrypick PR https://github.com/kubernetes/autoscaler/pull/2013

This is a cherrypick of the two PR. Code and documentation from @drewhemm
#1886
#1983

### CODE REVIEW

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!

**Comment by losipiuk** [comment]
@danigrmartinez for this one tests are failing. Please fix :)

**Comment by danigrmartinez** [comment]
Closing this because aws sdk version is not compratible with MixedInstancePolicy support

**Pull request closed without merging**
