### PR TITLE
cherry pick #6020- Adding support to s390x arch

### PR DESCRIPTION
**Pull request by skorati**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR can help build s390x auto scalar image

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

The PR against master for adding s390x support https://github.com/kubernetes/autoscaler/pull/6020

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @skorati 
Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check CLA,

/easycla

**Comment by skorati** [comment]
@Shubham82 Could you please review the PR, the CLA is approved now.

**Comment by Shubham82** [comment]
Thanks, @skorati 
/lgtm

**Comment by Saripalli-lavanya** [comment]
Hi @mwielgus, Could you please help us review this PR? 

Thank you :).

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
