### PR TITLE
Sets max/min size for ASG to desired capacity when processes suspended

### LINKED ISSUE #5591: Cluster Autoscaler gracefully handles ASG launches being suspended
**Which component are you using?**:
Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Yes.

Scenario: Set up multiple nodegroups on EKS. A common scenario is creating one ASG per AZ, so let's say we have 3 nodegroups all in different AZs. If I'm seeing workloads having issue in one of the AZs, I could call [suspend-processes](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/suspend-processes.html) on that ASG to avoid scaling up in the impacted AZ. As pods become unschedulable, CAS will scale up one of my ASGs. However, it could pick the ASG with processes suspended to scale, and those instances won't come up until processes are resumed, and it could pick it multiple times. I don't know if CAS will eventually pick another ASG to scale, but in my testing, it definitely doesn't happen within a short amount of time. While you could remove the ASG from CAS (removing ASG tags or whatever), it would be ideal for CAS to just handle the scenario gracefully.

**Describe the solution you'd like.**:

When CAS chooses an ASG to scale, it should discard ASGs with launches suspended. `SuspendedProcesses` processes is returned in the `DescribeAutoScalingGroups` call, so we can tell if it's able to launch instances or not.

**Describe any alternative solutions you've considered.**:

The alternative would be the current state: expect users to remove the ASG from CAS in this scenario.

**Additional context.**:

Currently looking at the code base and may update as my understanding of CAS improves.

### PR DESCRIPTION
**Pull request by mmerkes**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When using the AWS cloud provider, CAS does not take into account whether or not the ASG can actually scale up or down. If you call [suspend-processes](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/suspend-processes.html) on the ASG, you can disable launching or terminating instances, and when that happens, CAS may trigger a scaling action (and do some continually) when ASG will never actually launch or terminate instances.

In this PR, I made a change to set the `MinSize` to the desired size if terminate is suspended for an ASG and `MaxSize` to the desired size if launch is suspended for an ASG. This results in CAS ignoring the ASG when choosing who to scale. While this is a little indirect, it provides a simple solution to the problem.

#### Which issue(s) this PR fixes:

Fixes #5591

#### Special notes for your reviewer:

I did deploy this change to an EKS 1.24 cluster and verified that it worked as expected.

I started with 2 ASGs, one with all processes suspended and the other one untouched and verified that only the one ASG overrode the min/max sizes:

```
I0315 18:28:10.064281       1 auto_scaling_groups.go:514] Setting min size to desired size for eks-ng-ee55ae76-1cc36661-4ed9-07f9-f199-699fc0224ce0 due to suspended Terminate process
I0315 18:28:10.064300       1 auto_scaling_groups.go:525] Setting max size to desired size for eks-ng-ee55ae76-1cc36661-4ed9-07f9-f199-699fc0224ce0 due to suspended Launch process
I0315 18:28:10.064314       1 auto_scaling_groups.go:161] Registering ASG eks-ng-ee55ae76-1cc36661-4ed9-07f9-f199-699fc0224ce0
I0315 18:28:10.064324       1 auto_scaling_groups.go:161] Registering ASG eks-second-58c36ddd-ab39-ea43-4f02-7ed9233931c9
```

Also, verified that the ASG cache gets regenerated regularly, as expected.

Then, I scaled pods and verified that it results in the suspended processes ASG to get ignored:

```
I0315 18:32:52.774186       1 scale_up.go:231] Skipping node group eks-ng-ee55ae76-1cc36661-4ed9-07f9-f199-699fc0224ce0 - max size reached
```

Then, I cleared the suspended processes, scaled up pods again and verified that the ASG goes back into circulation and was eventually picked for scaling.

#### Does this PR introduce a user-facing change?

```release-note
Fixed AWS cloudprovider to treat nodegroups as unscalable if relevant processes are suspended in the underlying Auto Scaling Group.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None

### CODE REVIEW

**Comment by x13n** [comment]
/assign

I think using min/max for this is not the best approach, because:
- These nodes will still be used by CA simulations and only then filtered out as infeasible for scaling, which wastes resources.
- If a node crashes, CA may still trigger a scale up when there are pending pods, since the current size will suddenly become lower than the desired size.

Alternatively, returning `nil` from `NodeGroupForNode` ([here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#LL109C37-L109C37)) will prevent CA from considering the node to be a part of an autoscaled node group at all, which I think is what you want.

**Comment by x13n** [comment]
Btw, this is why it works: https://github.com/kubernetes/autoscaler/blob/57bd2bca97ac80ceb0fe92f604f01a7b0afa4f9c/cluster-autoscaler/core/utils/utils.go#L71

**Comment by mmerkes** [comment]
@x13n Tx for taking a look and providing more context.

> These nodes will still be used by CA simulations and only then filtered out as infeasible for scaling, which wastes resources.

While that's true, it's an improvement over the current behavior as the result will be better. I didn't filter out the impacted ASGs because you could suspend `Launch` and not `Terminate`, or visa-versa, though if you suspend both, it would probably make sense to remove.

> If a node crashes, CA may still trigger a scale up when there are pending pods, since the current size will suddenly become lower than the desired size.

That's true, though it's a race condition of a race condition, and given that the cache refreshes every 1 minute, CA won't ever guarantee that it's making the right decision 100% of the time.

> Alternatively, returning nil from NodeGroupForNode ([here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#LL109C37-L109C37)) will prevent CA from considering the node to be a part of an autoscaled node group at all, which I think is what you want.

Tx for the suggestion. I'll check this out. That will handle the node crashing case, but will that stop it from scaling the ASG?

**Comment by x13n** [comment]
> While that's true, it's an improvement over the current behavior as the result will be better. I didn't filter out the impacted ASGs because you could suspend `Launch` and not `Terminate`, or visa-versa, though if you suspend both, it would probably make sense to remove.
 
Ah, good point, I actually didn't understand what suspend-process in AWS really does. :sweat_smile:  If you can disable VM creation/termination separately, then overriding min/max separately makes more sense. It still feels a bit hacky - ideally, suspending `Launch` would remove the node group from scale up logic completely, while suspending `Terminate` would remove the node group from scale down. Both could be alternatively achieved by implementing `NodeGroupListProcessor` and `ScaleDownNodeProcessor`, respectively. Cloud provider specific processors are not easily introduce-able when we have a shared binary for all cloud providers. I'd be interesting on aws owners' thoughts - @gjtempleton @drmorr0 
 
> Tx for the suggestion. I'll check this out. That will handle the node crashing case, but will that stop it from scaling the ASG based on pods scaling up or scaling down?

It would work well if one wanted to disable scaling completely - CA would consider the entire node group as not autoscaled. (You'd also need to filter it out from `NodeGroups()` call too.) Since you want to separately control `Launch` and `Terminate`, I admit it is not the way to go.

**Comment by x13n** [comment]
This doesn't seem to be worked on, please reopen if needed.

/close

**Pull request closed without merging**
