### PR TITLE
Add ability to the VPA admission-controller to reload it's certificate

### LINKED ISSUE #6272: VPA admission controller certificate is not reloaded
**Which component are you using?**: vertical-pod-autoscaler

**What version of the component are you using?**: 0.13.0

Component version: 0.13.0

**What k8s version are you using (`kubectl version`)?**: 1.24

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: When using cert-manager to generate the secret containing TLS certs for the VPA admission controller, updates to the secret should trigger a reload so that the VPA admission controller is still available.

**What happened instead?**: When using cert-manager to generate the secret containing TLS certs for the VPA admission controller, updates to the secret result in the VPA admission controller reporting a bad certificate.

**How to reproduce it (as minimally and precisely as possible)**: See above

**Anything else we need to know?**:

Re-filing this as a +1 to https://github.com/kubernetes/autoscaler/issues/3458.
I see that https://github.com/kubernetes/autoscaler/pull/3462 was opened but eventually closed.

### PR DESCRIPTION
**Pull request by Nuckal777**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds the ability for the admission-controller to reload it's certificate on changes to the certificate file. This is useful when provisioning certificates with cert-manager.

#### Which issue(s) this PR fixes:

Fixes #6272.

#### Special notes for your reviewer:

This is based on #3462. I tried to implement the feedback already given there.

#### Does this PR introduce a user-facing change?

```release-note
Added `reload-cert` flag to the VPA admission-controller, which will reload the certificates it use, when they change.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None.

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @Nuckal777
you have to sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check EasyCLA

/easycla

**Comment by Nuckal777** [comment]
Hey, @Shubham82 the commits I added to #3462 after rebasing are [covered by the CLA](https://github.com/kubernetes/autoscaler/pull/6653#issuecomment-2018535516). The commits from @surajnarwade were covered in #3462. I don't know if that is sufficient.

**Comment by Shubham82** [comment]
@ Nuckal777, it is due to the commits you added that do not belong to this repository. (means you rebased on commits that are not merged in kubernetes/autoscaler repo)
We always work or merge PR on the latest commits https://github.com/kubernetes/autoscaler.

I think you have to delete those commits and then add those changes in the code yourself.

**Comment by Shubham82** [comment]
see, the commits you added showed the following message:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.


https://github.com/kubernetes/autoscaler/commit/9623817d581154f3f1981ab28a89f5569b59d049
https://github.com/kubernetes/autoscaler/commit/e40e828ae692cebe34743c35cf7cf7c9d6f2a2ba

**Comment by Nuckal777** [comment]
Closing in favour of #6665.

**Pull request closed without merging**
