### PR TITLE
Only render ServiceMonitor annotations if not empty

### PR DESCRIPTION
**Pull request by Kellen275**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR applies the same logic used in other `templates/` to the annotations of the ServiceMonitor.

While this is good general cleanup, this also has a side-effect of improving [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) integration. Without this, if you leave the annotations default (empty) and deploy with ArgoCD, it will *always* detect a noop diff
Screenshot from 2024-07-19 08-10-17

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by Kellen275** [comment]
Hi @Shubham82 , is there anything remaining for this PR?

**Comment by Shubham82** [comment]
@Kellen275, To merge this PR, needs approval (`/approve` label) from the approver.

**Comment by Shubham82** [comment]
cc @gjtempleton
PTAL!

**Comment by Shubham82** [comment]
@Kellen275, please resolve the merge conflict.

**Comment by jackfrancis** [comment]
/lgtm

/hold

we'll get this in the queue, sorry in advance for needing to rebase + rev the chart version once again

**Comment by jackfrancis** [comment]
This is ready for merge! Could you kindly:

1) rebase
2) set new chart version to 9.43.0
3) squash commits

thank you!

**Comment by gjtempleton** [comment]
Thanks!
/approve

**Pull request merged**
