### PR TITLE
Fix aws ProviderID pattern to match with the kubernetes version.

### PR DESCRIPTION
**Pull request by gbergere**
Fix this issue : https://github.com/kubernetes/autoscaler/issues/16

### CODE REVIEW

**Comment by gbergere** [comment]
I accepted the Contributor License Agreement (CLA).

**Comment by MaciekPytel** [comment]
@andrewsykim Can you take a look?

**Comment by andrewsykim** [comment]
@gbergere what version of kubernetes are you running? I'm running v.1.6.1 and I see the AZ when I see the node spec when I run:
```
$ kubectl get no ip-172-20-15-186.ec2.internal -o yaml
```

**Comment by gbergere** [comment]
Can you see it in the field `spec.ProviderID` ? I don't and I'm running on 1.6.1... If you look in the issue I've found in the kubernetes repository than the providerID is formed without the AZ...

**Comment by andrewsykim** [comment]
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl get no ip-172-20-15-186.ec2.internal -o yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2017-04-24T17:50:15Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: c3.2xlarge
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1c
    kubernetes.io/hostname: ip-172-20-15-186.ec2.internal
  name: ip-172-20-15-186.ec2.internal
  resourceVersion: "1096052"
  selfLink: /api/v1/nodesip-172-20-15-186.ec2.internal
  uid: 791be038-2916-11e7-ad6b-0a717cdbf8ba
spec:
  externalID: i-0c57bea5b2c57c2c6
  providerID: aws:///us-east-1c/REDACTED
```

**Comment by gbergere** [comment]
Oww... Mine is 1.6.0 server side... How did you create your cluster ?
kubeadm for me.

**Comment by andrewsykim** [comment]
That cluster is in-house

**Comment by gbergere** [comment]
Ok, I'll have a try with 1.6.1 then 
But I'm surprised regarding the code of kubernetes as you can see in the issue I've opened : https://github.com/kubernetes/autoscaler/issues/16

**Comment by andrewsykim** [comment]
The `updateCloudProviderFromMachineInfo` function you mentioned in the issue is only called when you don't pass in a cloud provider flag. You should check your apiserver/controller-manager flags for `--cloud-provider=aws` https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L292-L299

**Comment by gbergere** [comment]
@andrewsykim no clue why but today my new node (from scale up) poped with the correct format `aws:///eu-west-1b/REDACTED`. I have no clue why as all looks exactly the same version but at least looks like it's fixed... Except my first node the master which keep poping with aws:////REDACTED while it's exactly the same and `--cloud-provider=aws` have actually always been defined in my config...

Thx

**Pull request closed without merging**
