### PR TITLE
Main VPA README update. Fix grammar and add versions compatibility

### PR DESCRIPTION
**Pull request by aleksrosz**
Add compatibility for 0.9, 0.10 and 0.11 VPA version.
Fix grammar

#### Which component this PR applies to?

VPA

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Update old main README for VPA
Add Compability for 0.9, 0.10 and 0.11 VPA version.
Fix gramma

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jbartosik** [comment]
Thank you,
can you please add explanation (comment on the PR is enough) why each version of VPA requires that version of K8s? 

(basically explanation where numbers came from)

**Comment by aleksrosz** [comment]
Change:

| VPA version     | Kubernetes version |
|-----------------|--------------------|
| 0.11            | 1.22+              |
| 0.10            | 1.22+              |
| 0.9             | 1.16+              |

Why?
In K8S 1.22 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122 
"The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22." ... migrated to "apiextensions.k8s.io/v1 ".

In vpa-release-0.10 added [vpa-v1-crd-gen.yaml](https://github.com/kubernetes/autoscaler/blob/vpa-release-0.10/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml) which uses apiVersion: apiextensions.k8s.io/v1. 

https://github.com/kubernetes/autoscaler/blob/vpa-release-0.10/vertical-pod-autoscaler/hack/vpa-process-yamls.sh uses "vpa-v1-crd-gen" to install VPA


Version 0.10 and 0.11 is compatible. I tested both versions on K8S 1.22. 

@jbartosik

**Review by jbartosik — COMMENTED** [review]
I merged #5050 which updated the compatibility table, please rebase

**Comment by aleksrosz** [comment]
I have to create another PR.

**Pull request closed without merging**
