### PR TITLE
OCI: Fixing scale from zero if the nodeSelector of workload contains 'node.kubernetes.io/instance-type'

### PR DESCRIPTION
**Pull request by robert-heinzmann-logmein**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Currently if workload contains a `nodeSelector` such as 

```
        "nodeSelector": {
          "node.kubernetes.io/instance-type": "VM.Standard.E4.Flex"
        },
```

then scale from zero does not work as `shape.Name` is not initialized during the templateNode creation.

#### Special notes for your reviewer:

This should be backported / cherry picked for all supported OKE versions such as 1.30 (upcoming), 1.29, 1.28

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @robert-heinzmann-logmein, you have to sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check EasyCLA

/easycla

**Comment by Shubham82** [comment]
It looks good to me.
cc @jlamillan PTAL, (as he is the owner of OCI clouder provider)

**Review by jlamillan — APPROVED** [review]
Thanks for the fix!

/lgtm
/approve

**Pull request merged**
