### PR TITLE
Re-use results for similar pods in FilterOutSchedulable

### PR DESCRIPTION
**Pull request by MaciekPytel**
This should help performance problems in FilterOutSchedulable if there are thousands of pending pods, provided they were created by a smaller set of controllers.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
This conflicts with #231, but it should be pretty simple to migrate - just replace CreatorRef() call with ControllerRef() and get UID out of result.

**Comment by MaciekPytel** [comment]
Functional testing done:
- Run 2 simple deployments, confirmed FilterOutSchedulable run predicates for exactly one pod in each deployment
- Run the same 2 deployments together with a few pods not managed by controllers and an rc with some pods created by rc and some (with slightly different spec and manually added created-by annotation) adopted. Predicates were run once for each deployment, once for pods created by rc, once for adopted pod and once for each pod not owned by any controller.

**Comment by crimsonfaith91** [comment]
@MaciekPytel I closed #231 to prevent duplication of work. According to @DirectXMan12 at slack, someone will look at it this week.

**Pull request merged**
