### PR TITLE
Bump k/k dependencies to v1.25.0 together with go.mod go version.

### PR DESCRIPTION
**Pull request by olagacek**
#### Which component this PR applies to?

Bump k/k dependencies to v1.25.0 together with bumping go.mod go version to 1.19.

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Bumps k/k dependencies to v1.25.0 together with bumping go.mod go version to 1.19.

### CODE REVIEW

**Comment by mwielgus** [comment]
Do we also want to lint everything in the same commit?

**Comment by mwielgus** [comment]
Did you check with @jbartosik that he is ok with bumping stuff in VPA?

**Comment by mwielgus** [comment]
/hold 
(to get my questions answered)

**Comment by mwielgus** [comment]
Not necessarily, just wanted to make sure that you want to cover both deps, go, linitng and vpa in the PR.

**Comment by olagacek** [comment]
> Not necessarily, just wanted to make sure that you want to cover both deps, go, linitng and vpa in the PR.

My main purpose was to bump dependencies and as it turned out other things were required to make it work and pass the tests and verifications.

**Review by jbartosik — APPROVED** [review]
VPA part LGTM

**Comment by olagacek** [comment]
> Did you check with @jbartosik that he is ok with bumping stuff in VPA?

Yes, done.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
