### PR TITLE
chore: backport latest VMs pool and HasInstance() implementations, for 1.30

### PR DESCRIPTION
**Pull request by comtalyst**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
These differences have effectively disabled cherry-pick automation in these areas. Upcoming changes (e.g., more VMs pool implementation, cloud-provider-azure integration rework, more fixes that need to be done in all versions) will be agonizing experiences, not to mention the past ones.
This PR will amend some of those differences, which is mostly VMs pool and HasInstance() implementations. They cannot be cherry-picked in normal means easily due to conflict with Azure defork operations, which have to resolve these conflicts at some point anyway.

#### Which issue(s) this PR fixes:

- https://github.com/Azure/AKS/issues/4286
- https://github.com/kubernetes/autoscaler/issues/4456

#### Special notes for your reviewer:

Original `HasInstance()` implementation PR: https://github.com/kubernetes/autoscaler/pull/6956
Differences visualization I used as a reference, with some labels: https://github.com/comtalyst/autoscaler/pull/3/files

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by tallaxes — APPROVED** [review]

**Comment by towca** [comment]
Could you remove the vendor changes from the PR? We've removed the vendor dir from CA altogether, see #4878.

**Comment by comtalyst** [comment]
@towca I thought that is effective beginning 1.31 (master). Still seeing #7046 and similar.
Also, `test-and-verify` didn't pass after removing vendor changes.

**Comment by towca** [comment]
Ahh my bad, indeed vendor is still there on 1.30. Sorry for the confusion.

/approve
/lgtm

**Pull request merged**
