### PR TITLE
CA: Before we perform go test, synchronizing go modules

### LINKED ISSUE #6664: cannot find module providing package k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1beta1: import lookup disabled by -mod=vendor
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

latest / master

**What environment is this in?**:

docker

**What did you expect to happen?**:

`make test-in-docker` <-- should PASS

**What happened instead?**:

```
$ make test-in-docker 
rm -f cluster-autoscaler-amd64
docker build --network=default -t autoscaling-builder ../builder
Sending build context to Docker daemon  4.608kB
Step 1/10 : FROM golang:1.22.1
 ---> e49d53614208
Step 2/10 : LABEL maintainer="Marcin Wielgus <mwielgus@google.com>"
 ---> Using cache
 ---> c6955c4b8456
Step 3/10 : ENV GOPATH /gopath/
 ---> Using cache
 ---> d8a2a4e31934
Step 4/10 : ENV PATH $GOPATH/bin:$PATH
 ---> Using cache
 ---> 7f4bf158d234
Step 5/10 : ENV GO111MODULE auto
 ---> Using cache
 ---> 2bd4683f0565
Step 6/10 : RUN apt-get update && apt-get --yes install libseccomp-dev
 ---> Using cache
 ---> d6cf4519bb49
Step 7/10 : RUN go version
 ---> Using cache
 ---> 69e5b67990c2
Step 8/10 : RUN go install github.com/tools/godep@latest
 ---> Using cache
 ---> 8c1fd4d3dcdc
Step 9/10 : RUN godep version
 ---> Using cache
 ---> 67c22827409b
Step 10/10 : CMD ["/bin/bash"]
 ---> Using cache
 ---> 7695991a0993
Successfully built 7695991a0993
Successfully tagged autoscaling-builder:latest
docker run  -v `pwd`:/cluster-autoscaler/:Z autoscaling-builder:latest bash -c 'cd /cluster-autoscaler && go test -race ./... '
processors/provreq/provisioning_request_injector.go:25:2: cannot find module providing package k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/autoscaling.x-k8s.io/v1beta1: import lookup disabled by -mod=vendor
        (Go version in go.mod is at least 1.14 and vendor directory exists.)
provisioningrequest/provreqclient/client.go:28:2: cannot find module providing package k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/client/clientset/versioned: import lookup disabled by -mod=vendor
        (Go version in go.mod is at least 1.14 and vendor directory exists.)
provisioningrequest/provreqclient/testutils.go:28:2: cannot find module providing package k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/client/clientset/versioned/fake: import lookup disabled by -mod=vendor
        (Go version in go.mod is at least 1.14 and vendor directory exists.)
provisioningrequest/provreqclient/client.go:29:2: cannot find module providing package k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/client/informers/externalversions: import lookup disabled by -mod=vendor
        (Go version in go.mod is at least 1.14 and vendor directory exists.)
provisioningrequest/provreqclient/client.go:30:2: cannot find module providing package k8s.io/autoscaler/cluster-autoscaler/apis/provisioningrequest/client/listers/autoscaling.x-k8s.io/v1beta1: import lookup disabled by -mod=vendor
        (Go version in go.mod is at least 1.14 and vendor directory exists.)
make: *** [Makefile:112: test-in-docker] Error 1
```

**Anything else we need to know?**:

This bug was most likely introduced in: https://github.com/kubernetes/autoscaler/pull/6315

I suspect some replace directive is missing in go.mod

/assign @tenzen-y 
/cc @x13n

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Before we perform the `go test` and `go vet`, it seems that we need to synchronize the go modules.

#### Which issue(s) this PR fixes:

Fixes #6664

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@azylinski @x13n Could you check this if this would work well on your local?
/assign @azylinski @x13n

**Comment by x13n** [comment]
Thanks, the Makefile change works for me. What's up with all the other file removals though?

**Comment by tenzen-y** [comment]
> Thanks, the Makefile change works for me. What's up with all the other file removals though?

@x13n Thank you for the checks. After I performed `go mod vendor,` these files were removed. 
So, I guess that someone forgot to sync the vendor directory in previous PRs.

**Comment by tenzen-y** [comment]
@x13n Could you check in your local double-check with `cd cluster-autoscaler && go mod vendor` to see if those files are not needed?

**Comment by x13n** [comment]
Yup, I'm getting the same results, these files get removed. Let's merge it like this.

/lgtm
/approve

**Comment by tenzen-y** [comment]
> Yup, I'm getting the same results, these files get removed. Let's merge it like this.
> 
> /lgtm /approve

Thank you!

**Pull request merged**
