### PR TITLE
refactor: upstream Azure managed instance cache refactor for 1.28

### PR DESCRIPTION
**Pull request by comtalyst**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
"Refactor" as a part of fork-upstream (managed-selfhosted) realignment. Should not have any breaking changes.
This codebases realignment will simplify the logistics between the two, cutting a significant portion of maintenance cost.
This PR specifically focus on instance caching.

There will be a separate effort focusing on improve code quality, rather than realigning codebase.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Most changes are merely refactor. Also include small fixes to refresh instance cache in more cases that should be required. Also include support for currently managed-exclusive flags (e.g., `EnableDetailedCSEMessage`).

There are similar PRs out on master and other version release branches as well. Should be near identical.

#### Does this PR introduce a user-facing change?

```release-note
- Azure: fix some cases where instance cache is outdated but not getting refreshes
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Bryce-Soghigian** [comment]
Testing approval

**Comment by tallaxes** [comment]
@Bryce-Soghigian, @comtalyst Looks like OWNERS is branch-specific, so need to propagate the change to all active branches

**Pull request merged**
