### PR TITLE
Improve performance of the Azure cloud provider

### PR DESCRIPTION
**Pull request by DavidLangworthy**
Previously, the cloud provider called Get to obtain the status for each node pool.  When running with a large number of node pools, e.g. 10+, these will cause Azure to throttle, not only the autoscaler, but all services operating under the same identity.

This commit replaces the Get call for each node pool with a List call which obtains the status for all the node pools at once.  The frequency of these calls is set with the vmssSizeRefreshPeriod constant.

### CODE REVIEW

**Comment by DavidLangworthy** [comment]
@feiskyer I have updated the expected values and am passing all tests but one.  This is TestDeleteNodes.  It overwrites the FakeStore.  How should I deal with this?  Also, are the expected values changes alright?

**Comment by mboersma** [comment]
@feiskyer tests are passing now, PTAL when time permits.

**Comment by feiskyer** [comment]
@DavidLangworthy would you like to cherry pick to stable branches?

**Comment by DavidLangworthy** [comment]
@feiskyer Yes, I would like this in 1.16 and 1.15.  Should I just reissue this PR against those branches?

**Pull request merged**
