### PR TITLE
Cloudprovider hetzner

### PR DESCRIPTION
**Pull request by LKaemmerling**
Resubmit of #3640

Hello everyone,

I'm from the Hetzner Cloud Team and i'm happy to resubmit PR #3640 with the work of @Fgruntjes. 
My collegues and i will maintain this implementation in the future. We see a high
demand from our customers for an integration into the Kubernetes Autoscaler. 

So we want to thank @Fgruntjes again for his work on the initial implementation. 

We will continue to improve the implementation and also support it.

cc @fhofherr

### CODE REVIEW

**Comment by fhofherr** [comment]
cla signed

**Comment by LKaemmerling** [comment]
Hey @team, this MR is from our side basically ready. The bot says I should assign it with:

/assign @aleksandra-malinowska

**Comment by mwielgus** [comment]
Please remove the people outside of K8S org from the owners file and squash the commits to 1-2. Then we should be good to go.

**Comment by mwielgus** [comment]
And fix the boilerplate so that the verify scripts pass.

**Comment by LKaemmerling** [comment]
@mwielgus should be ready (2 commits)

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by blindpirate** [comment]
Hi @LKaemmerling Thanks for the contribution, we're a Hetzner cloud user and we've run into some crashes with hetzner autoscaler, I wonder if there's repo in hetzner organization to report this issue?

**Comment by jawabuu** [comment]
@LKaemmerling @mwielgus 
I'm testing out this autoscaler and it seems no kubernetes events are emitted nor nodes annotated on scaledown.
Is this expected?

**Comment by jawabuu** [comment]
From docs

```
Whenever Cluster Autoscaler adds or removes nodes it will create events describing this action. It will also create events for some serious errors. Below is the non-exhaustive list of events emitted by CA (new events may be added in future):
 on kube-system/cluster-autoscaler-status config map:
ScaledUpGroup - CA increased the size of node group, gives both old and new group size.
ScaleDownEmpty - CA removed a node with no pods running on it (except system pods found on all nodes).
ScaleDown - CA decided to remove a node with some pods running on it. Event includes names of all pods that will be rescheduled to drain the node.
on nodes:
ScaleDown - CA is scaling down the node. Multiple ScaleDown events may be recorded on the node, describing status of scale-down operation.
ScaleDownFailed - CA tried to remove the node, but failed. The event includes error message.
```

**Pull request merged**
