### PR TITLE
Stop waiting for upcoming nodes from unhealthy node groups

### PR DESCRIPTION
**Pull request by mvisonneau**
This is an attempt to solve a long going issue, preventing CA from failing over healthy node groups when a scale-up occurred onto a non-healthy one. This is particularly painful whilst working with spot based ASGs which are very prone to these kinds of disruptions.

References in #1795 and #1133

if people want to easily try it out, I published a docker release: `docker.io/mvisonneau/cluster-autoscaler:1.14.2-fix_scale_up_unavail_node_groups`

it seems to work perfectly fine for my use case :

```
Events:
  Type     Reason            Age                    From                Message
  ----     ------            ----                   ----                -------
  Normal   TriggeredScaleUp  52m (x7 over 54m)      cluster-autoscaler  pod triggered scale-up: [{sb1-in-k8s-worker-spot-r5.2xlarge-b 0->1 (max: 20)}]
  Warning  FailedScheduling  4m10s (x195 over 60m)  default-scheduler   0/9 nodes are available: 6 Insufficient cpu, 9 Insufficient memory.
  Normal   TriggeredScaleUp  52s                    cluster-autoscaler  pod triggered scale-up: [{sb1-in-k8s-worker-spot-m5.4xlarge-b 0->1 (max: 20)}]
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
I don't think this solves the issue. A single failed scale-up won't make a NodeGroup unhealthy, it will likely take multiple retries before it gets there. And just because a NodeGroup is unhealthy doesn't mean a node that is already being created will fail. 

There is already plenty of logic to deal with this scenario. I think the problem here is that AWS cloudprovider implementation doesn't use it. I've put some details in https://github.com/kubernetes/autoscaler/issues/1996#issuecomment-490422582.

**Comment by mvisonneau** [comment]
Indeed @MaciekPytel, I did eventually end up with this issue :( I'll try to have a closer look following your comments.

**Comment by Jeffwan** [comment]
> There is already plenty of logic to deal with this scenario. I think the problem here is that AWS cloudprovider implementation doesn't use it. I've put some details in [#1996 (comment)](https://github.com/kubernetes/autoscaler/issues/1996#issuecomment-490422582).

Hi @MaciekPytel Anywhere I can check for the logic you mentioned? I'd love to add to AWS cloudprovider side.

**Comment by MaciekPytel** [comment]
The implementation is already in progress in https://github.com/kubernetes/autoscaler/pull/2008 - let's continue discussion there.

**Pull request closed without merging**
