### PR TITLE
[Azure] Update vendor/module versions for 1.29

### PR DESCRIPTION
**Pull request by rakechill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Updates module versions for Azure-related dependencies. Only **skewer** needed to be updated.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rakechill** [comment]
@towca can you take a look at this PR? It updates `go.mod` to incorporate latest version of an Azure dependency: `skewer`

**Review by feiskyer — APPROVED** [review]
/approve

**Pull request merged**
