### PR TITLE
[CA-1.19] CAPI backports for autoscaling workload clusters

### PR DESCRIPTION
**Pull request by benmoss**
Backports the recent work @detiber did to enable running the autoscaler against a different cluster than the one it is running in.

cc @elmiko

### CODE REVIEW

**Review by detiber — COMMENTED** [review]
main: 3eb90c19d0cf90b756c3e08e32c6495b91e0aeed

**Comment by benmoss** [comment]
I think the three directory additions are correct:

```
$ diff -q vendor/k8s.io/client-go/discovery/cached/memory/ /tmp/ca-update-vendor.LoV7/kubernetes/vendor/k8s.io/client-go/discovery/cached/memory/
Only in /tmp/ca-update-vendor.LoV7/kubernetes/vendor/k8s.io/client-go/discovery/cached/memory/: memcache_test.go

$ diff -q vendor/k8s.io/client-go/restmapper /tmp/ca-update-vendor.LoV7/kubernetes/staging/src/k8s.io/client-go/restmapper
Only in /tmp/ca-update-vendor.LoV7/kubernetes/staging/src/k8s.io/client-go/restmapper: category_expansion_test.go
Only in /tmp/ca-update-vendor.LoV7/kubernetes/staging/src/k8s.io/client-go/restmapper: discovery_test.go
Only in /tmp/ca-update-vendor.LoV7/kubernetes/staging/src/k8s.io/client-go/restmapper: shortcut_test.go

$ diff -q vendor/k8s.io/client-go/scale/fake/ /tmp/ca-update-vendor.LoV7/kubernetes/staging/src/k8s.io/client-go/scale/fake/
```

**Comment by detiber** [comment]
/lgtm

Thanks for tackling this @benmoss

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
