### PR TITLE
[cluster-autoscaler-release-1.30] backport Azure e2e tests

### PR DESCRIPTION
**Pull request by nojnhuh**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

This PR backports the Azure e2e tests added by #6969 and related PRs to the master branch.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nojnhuh** [comment]
https://github.com/kubernetes/test-infra/pull/33361 will enable the job to run (correctly) here. Let's merge that before this one so we can iterate here if needed.

**Review by tallaxes — APPROVED** [review]

**Comment by nojnhuh** [comment]
e2e job passed.
/hold cancel

@tallaxes Do you know the recommended way to fix the dependency error the unit test job is throwing? Based on this it looks like the release branches of cluster-autoscaler may not be fully module-aware:
```shell
git diff upstream/cluster-autoscaler-release-1.30 upstream/master -- hack/for-go-proj.sh
```

```diff
diff --git a/hack/for-go-proj.sh b/hack/for-go-proj.sh
index ec55ef23d..f44f997c4 100755
--- a/hack/for-go-proj.sh
+++ b/hack/for-go-proj.sh
@@ -19,7 +19,7 @@ set -o pipefail
 set -o nounset

 CONTRIB_ROOT="$(dirname ${BASH_SOURCE})/.."
-PROJECT_NAMES=(addon-resizer cluster-autoscaler vertical-pod-autoscaler)
+PROJECT_NAMES=(addon-resizer vertical-pod-autoscaler)

 if [[ $# -ne 1 ]]; then
   echo "missing subcommand: [build|install|test]"
@@ -43,12 +43,7 @@ esac

 for project_name in ${PROJECT_NAMES[*]}; do
   (
-    if [[ $project_name == cluster-autoscaler ]];then
-      export GO111MODULE=off
-    else
-      export GO111MODULE=auto
-    fi
-
+    export GO111MODULE=auto
     project=${CONTRIB_ROOT}/${project_name}
     echo "${CMD}ing ${project}"
     cd "${project}"
@@ -68,6 +63,10 @@ for project_name in ${PROJECT_NAMES[*]}; do
 done;

 if [ "${CMD}" = "build" ] || [ "${CMD}" == "test" ]; then
-  cd ${CONTRIB_ROOT}/vertical-pod-autoscaler/e2e
+  pushd ${CONTRIB_ROOT}/vertical-pod-autoscaler/e2e
   go test -mod vendor -run=None ./...
+  popd
+  pushd ${CONTRIB_ROOT}/cluster-autoscaler/
+  go test ./...
+  popd
 fi
```

**Comment by nojnhuh** [comment]
CI checks are passing now and I cleaned up the history here.

/hold cancel

**Review by rakechill — APPROVED** [review]

**Review by Bryce-Soghigian — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
