### PR TITLE
Return provider interface

### PR DESCRIPTION
**Pull request by bskiba**
Adresses https://github.com/kubernetes/autoscaler/pull/2968/files#r396542312

### CODE REVIEW

**Comment by krzysied** [comment]
/lgtm
/approve

Thanks! :)

**Comment by bskiba** [comment]
Weird, says travis did not pass but it did already: https://travis-ci.org/github/kubernetes/autoscaler/builds/666399034?utm_source=github_status&utm_medium=notification

**Comment by bskiba** [comment]
Restarted build to see if it will help

**Pull request merged**
