### PR TITLE
Update README.md to include VPA 1.2.0 release

### PR DESCRIPTION
**Pull request by raywainman**
#7098

/kind documentation

Tested in `1.27.14-gke.1059002` which is currently the lowest version available in GKE.

### CODE REVIEW

**Comment by Shubham82** [comment]
@raywainman,  you have to update the VPA current version(1.2.0) in the following line also:
`The current default version is Vertical Pod Autoscaler 1.1.2`

**Comment by Shubham82** [comment]
Thanks @raywainman 
/lgtm

**Comment by Shubham82** [comment]
cc @voelzmo @kwiesmueller
Could you please approve this PR?

Thanks!

**Review by kwiesmueller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
