### PR TITLE
add TargetCPUPercentile to VerticalPodAutoscalerSpec

### LINKED ISSUE #4293: Make the target configurable
**Which component are you using?**: Recommender

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

The target is based on the percentile 90th. It is a good assumption, but sometimes there are some workloads we can be more aggressive about: `P85`, `P80`, ...

[Harness](https://docs.harness.io/article/ikxjmkqi03-recommendations) for instance has 2 standard profiles:
- Cost Optimized: for cpu it uses the `P50*1.15` (which is roughly equivalent to the `P65` in my own tests)
- Performance Optimized: uses the `P95`

**Describe the solution you'd like.**:

The `VerticalPodAutoscaler` should allow to configure the percentile value used for the target (`P90` being the default) in the `ContainerResourcePolicy`:

```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       my-app
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "prometheus"
      targetCPUPercentile: 0.80
...
```

This would have the effect of changing the value set in the recommender [initialization](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L102).

The `RecommendedContainerResources` should display multiple percentiles, and not juste the `lowerBound`, `target` and `upperBound`. It could always display all the percentiles from 65 to 95, or display the few values that a field in the spec would list: `calculatedCPUPercentiles: [0.8, 0.85]`. Then the recommendation would look like:

```
...
  recommendation:
    containerRecommendations:
    - containerName: my-rec-container
      lowerBound:
        cpu: 25m
        memory: 262144k
      target:
        cpu: 200m
        memory: 262144k
      p80:
        cpu: 100m
        memory: 262144k
      p85:
        cpu: 150m
        memory: 262144k
      upperBound:
        cpu: 7931m
        memory: 8291500k
...
```

Based on this recommendation, the SRE could decide to switch to either the `P80` or the `P85`, depending on the workload profile (performance or cost optimized).

**Describe any alternative solutions you've considered.**:

Use harness, or develop our own recommendation engine based on prometheus queries.

**Additional context.**:

### PR DESCRIPTION
**Pull request by matthyx**
#### Which component this PR applies to?
vertical-pod-autoscaler

#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #4293

#### Does this PR introduce a user-facing change?

```release-note
add TargetCPUPercentile to VerticalPodAutoscalerSpec to override default per VPA
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
@jbartosik I am adding a field to the CRD... do I need a KEP or something?

**Comment by jbartosik** [comment]
> @jbartosik I am adding a field to the CRD... do I need a KEP or something?

Yes :)

To change API we need a KEP first. Since the VPA API is in our repo we're doing a little lighter process.

Our KEPs are in [vertical-pod-autoscaler/enhancements](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements). So far we have one submitted (and implemented) KEP and [one more in review](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/3919-customized-recommender-vpa).

Writing a KEP is a bit of work so it might be a good idea to talk first.


A few things I think the KEP should address (probably worth discussing before writing the KEP):

1. I'd like to understand what use case(s) this intends to address.
2. "Target percentile" looks to me like it exposes an implementation detail of current VPA algorithm. I'd rather not expose implementation details in API for two reasons:
  - To be able to improve implementation in the future,
  - We now support alternative recommenders ([KEP](https://github.com/kubernetes/autoscaler/tree/23902caec6670ac8ebe939845ff36af8b5689045/vertical-pod-autoscaler/enhancements/3919-customized-recommender-vpa)) so any fields we add to the API should make sense for other recommenders too

**Review by jbartosik — CHANGES_REQUESTED** [review]
I remembered one more thing to consider when writing the KEP.

There are some other ideas for changes to VPA algorithm[1] we should take a look at them to make sure the API change we'll make will fit with any other changes we will implement in the future.


[1]
* https://github.com/kubernetes/autoscaler/issues/4583
* https://github.com/kubernetes/autoscaler/issues/4293
* https://github.com/kubernetes/autoscaler/issues/4230
* https://github.com/kubernetes/autoscaler/issues/4135
* https://github.com/kubernetes/autoscaler/issues/3986
* https://github.com/kubernetes/autoscaler/issues/3975
* https://github.com/kubernetes/autoscaler/issues/3766

**Comment by matthyx** [comment]
@jbartosik thanks for taking the time to discuss this :)
I work with @vsevel and this PR is the first step of an implementation for #4293
The higher level goal is to have workload profiles (normal, cost optimized, high performance, ...) that use a different CPU percentile to compute the CPU recommendations.

I agree that leaking implementation details might not be the best solution for the future evolutions, we based our analysis on [a feature of Harness](https://docs.harness.io/article/ikxjmkqi03-recommendations).

Actually, if [your KEP merges](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/3919-customized-recommender-vpa), we could implement this use case with different recommenders...

**Comment by jan-kantert** [comment]
We are interested in this as well. It would also be useful to have this for memory. A few services (i.e. prometheus) spike on memory on startup but generally do not need that much memory during runtime. Currently, we are over-reserving memory at factor 2 or 3 for some services.

**Comment by jbartosik** [comment]
Sorry for slow reply.

I thought about this and talked this over. I see two ways forward with this (and similar requests for tuning VPA):

1. Using [customized recommenders](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/3919-customized-recommender-vpa):
  1.1 Add flags that allow tuning VPA parameters like this PR does
  1.2 Add a flag that allows VPA to run under a different name than "" and "default"
  1.3 Add instructions for running two VPA recommender instances in one cluster, under different names
  1.4 Now you can run two VPA recommender instances in a cluster - "default" / "" and "lower cpu", each VPA object can specify which one to use
  1.5 Profit
2. Extending VPA API - this one is not so straight forward. We'd need to define some autoscaling profiles, add [enhancement](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements), extend API, use them in the default recommender to change percentiles we use.

@matthyx  @jan-kantert  what do you think?

**Comment by matthyx** [comment]
> @matthyx @jan-kantert what do you think?

I'd say go for 1 !
If you agree I can work on it, if you provide some structure: do we need a KEP, separate issues, ...

**Comment by matthyx** [comment]
Superceded by #4799

**Pull request closed without merging**
