### PR TITLE
vpa-{updater,recommender}: Add support for leader election

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR adds support for leader election in vpa-updater and vpa-recommender.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/autoscaler/issues/6846

#### Special notes for your reviewer:
This PR is strongly inspired by how leader election is built for the cluster-autoscaler.

#### Does this PR introduce a user-facing change?

```release-note
vpa-updater and vpa-recommender do now support leader election.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
/assign @voelzmo @raywainman 
Could you have a look please.

**Comment by adrianmoisey** [comment]
I build and tested this locally, and it all works as expected. Very nice, this is something I've also been wanting.

**Comment by voelzmo** [comment]
/lgtm

Thanks! Great catch of taking care of the `/health-check` endpoint for the passive replicas!
I think it is also important that the recommender gets killed and re-created when it loses leadership, so we don't end up in a situation where oudated in-memory aggregations are taken into account. The way it is implemented here, we should always end up using a fresh initialization from history.

**Pull request merged**
