### PR TITLE
port from PR 2551; shard prometheus history queries by day

### LINKED ISSUE #2543: vpa-recommender: Prometheus history provider doesn't work with large Prometheus/Kubernetes deployments
Whilst working on a fix for #2508 I ran into another issue whilst testing the VPA recommender with the Prometheus history provider. On startup the history provider queries Prometheus for historical container CPU usage over 8 days. We run a fairly large cluster and this results in a non trivial amount of cardinality and large amount of data, which Prometheus sensibly rejects due to the query returning too much data:

```
1172 cluster_feeder.go:209] Cannot get cluster history: cannot get usage history: cannot get timeseries for cpu: retrying GetTimeseries unsuccessful: tried 10 times, last error: bad HTTP status: 400 Bad Request. Response text: {"status":"error","errorType":"bad_data","error":"exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)"}
```

Even if this limit wasn't present, a query of this magnitude can easily OOMKill a large enough Prometheus instance.

**What can we do to fix it?**

Given we already retrieve a list of pods/labels using Prometheus, we can use that to split up and shard the queries to retrieve and load a subset of data at a time. Alternatively, we could change the history provider so that instead of all data being retrieved in one go on startup, we could dynamically load historical data for each VPA object we observe added to the cluster. 

Separately, I think we should also switch to using the Prometheus client library rather than writing HTTP calls and marshalling to custom types. This will let us build up valid queries programmatically (rather than `fmt.Sprintf`) and use the built in Prometheus types. This isn't strictly related to the above, so I'm happy to raise a separate issue/PR if you think this would be a good idea.

What do you think? cc @bskiba

### PR DESCRIPTION
**Pull request by yashbhutwala**
Now that #3122 is merged, this is another follow-up PR from #2551  

Resolves #2543

### CODE REVIEW

**Comment by estahn** [comment]
@yashbhutwala Have you had a chance to review @bskiba comments?

**Review by povilasv — COMMENTED** [review]
I feel like this shouldn't live in VPA repo. 

There are proxies that do this for you also cache results and do other nice things. No need to reimplement this as a client library in VPA ;) 

Example:
https://thanos.io/components/query-frontend.md/
https://cortexmetrics.io/docs/configuration/prometheus-frontend/

**Comment by cliles** [comment]
> I feel like this shouldn't live in VPA repo.
> 
> There are proxies that do this for you also cache results and do other nice things. No need to reimplement this as a client library in VPA ;)
> 
> Example:
> https://thanos.io/components/query-frontend.md/
> https://cortexmetrics.io/docs/configuration/prometheus-frontend/

In the current state the prometheus integration is not feature rich and has multiple issues when deployed in a large environment. I would hope that by introducing additional features we could solve some of the outstanding issues without adding another later of infrastructure. 

If the intent is that the VPA should work out of the box then this feature seems useful as it makes the client more intelligent and resilient.

**Comment by povilasv** [comment]
> > I feel like this shouldn't live in VPA repo.
> > There are proxies that do this for you also cache results and do other nice things. No need to reimplement this as a client library in VPA ;)
> > Example:
> > https://thanos.io/components/query-frontend.md/
> > https://cortexmetrics.io/docs/configuration/prometheus-frontend/
> 
> In the current state the prometheus integration is not feature rich and has multiple issues when deployed in a large environment. I would hope that by introducing additional features we could solve some of the outstanding issues without adding another later of infrastructure.
> 
> If the intent is that the VPA should work out of the box then this feature seems useful as it makes the client more intelligent and resilient.

Why more resilient? I think less resilient, u split the query to multiple queries, means more of them can fail as they hit back-end. 
On large environments u should definitely add some caching proxy like I mentioned above.

I feel having thick custom made client in here is not a right place

**Comment by mwielgus** [comment]
Closing due to inactivity. Feel free to reopen if/once needed.

**Pull request closed without merging**
