### PR TITLE
Switch VPA OOM E2E tests from custom image to upstream image

### LINKED ISSUE #4546: VPA e2e tests should use images from official repos
VPA e2e OOM tests are using image `gcr.io/jbartosik-gke-dev/stress:0.10` ([v1](https://github.com/kubernetes/autoscaler/blob/259c1acdeed58047980a772343af60ab6b695225/vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go#L65), [v1beta2](https://github.com/kubernetes/autoscaler/blob/259c1acdeed58047980a772343af60ab6b695225/vertical-pod-autoscaler/e2e/v1beta2/autoscaling_utils.go#L65)), we should move the image from my dev project (it already caused problems in the past).

Steps:
* Build the image and put it in an official repo,
* Change tests to use the new image.

### PR DESCRIPTION
**Pull request by jbartosik**
Fixes #4546

### CODE REVIEW

**Comment by jbartosik** [comment]
I ran modified e2e and they pass

**Comment by jbartosik** [comment]
@kgolab please take a look

**Comment by kgolab** [comment]
Thanks, LGTM.

**Pull request merged**
