### PR TITLE
Update documentation: AWS now supports ARNs for autoscaling groups

### LINKED ISSUE #234: Update documentation: AWS now supports ARNs for autoscaling groups
In the past, AWS did not support ARNs for autoscaling groups.

> Unfortunately AWS does not support ARNs for autoscaling groups yet so you must use "*" as the resource. More information here.
>
> ###### Reference: [autoscaler/cluster-autoscaler/cloudprovider/aws/README.md](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#permissions)

Now, however, AWS seems to have started supporting ARNs for the Autoscale group.

> ### Auto Scaling Resources
>
> For actions that support resource-level permissions, you can control the Auto Scaling group or launch configuration that users are allowed to access.
>
> To specify an Auto Scaling group, you must specify its Amazon Resource Name (ARN) as follows:
>
> ```
> "Resource": "arn:aws:autoscaling:region:123456789012:autoScalingGroup:uuid:autoScalingGroupName/asg-name"
> ```
>
> ###### Reference: [Controlling Access to Your Auto Scaling Resources - Auto Scaling Resources](https://docs.aws.amazon.com/autoscaling/latest/userguide/control-access-using-iam.html#policy-auto-scaling-resources)

Documentation of this repository is also likely to require updates. Shall we?

### PR DESCRIPTION
**Pull request by simnalamburt**
Closes #234

### CODE REVIEW

**Comment by simnalamburt** [comment]
I'll sign it. Please stand by.

**Comment by mwielgus** [comment]
Still not signed.

**Comment by rickard-von-essen** [comment]
Ping @simnalamburt CLA?

@mwielgus Maybe this can be merged without a CLA since the change is "trivial"?

**Comment by MaciekPytel** [comment]
@rickard-von-essen Unfortunately we can't merge any PR without CLA.

**Comment by simnalamburt** [comment]
Sorry for the delay. Yes this PR is indeed a extra small trivial patch, but I editted this code in my workplace so I need my company [Devsisters Corp.](https://github.com/devsisters/) to sign the CNCF CLA.

My company is quite positive to sign the CLA so it will be done in a few days. I'm very greatful for your patience, and sorry for the confusion.

(By the way, we do have contributed to Kubernetes before twice, so I wonder why it requires the CLA now https://github.com/kubernetes/kubernetes/pull/2414 https://github.com/kubernetes/kubernetes/pull/2415)

**Comment by MaciekPytel** [comment]
It looks like you contributed back when k8s was owned by Google. I think there were legal changes when it was donated to CNCF. But I'm an engineer, not a lawyer, so the real answer is I don't know.

**Comment by simnalamburt** [comment]
Currently my company's Head of Legal is reviewing the CLA. It'll be done in a few days. Thanks!

**Comment by simnalamburt** [comment]
We have signed the CLA and I re-pushed the PR with changed email address. Thanks!

**Pull request merged**
