### PR TITLE
Updates Golang version to 1.23

### PR DESCRIPTION
**Pull request by retornam**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Upgrades the Golang version to 1.23 to pickup updates to packages in the standard library as well as security fixes
Also updates the packages
k8s.io/kubernetes to  v1.27.16 ( missed in a prior commit)
sigs.k8s.io/cloud-provider-azure  to v1.27.21

#### Which issue(s) this PR fixes:

Fixes  NONE

#### Does this PR introduce a user-facing change?

NONE
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NONE

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@retornam why are we doing this only into the 1.27 release branch?

**Comment by retornam** [comment]
> @retornam why are we doing this only into the 1.27 release branch?

I'll update the main branch as well. This is to resolve some Golang vulns

**Comment by retornam** [comment]
@jackfrancis  https://github.com/kubernetes/autoscaler/pull/7318  should take care of the main branch as well

**Comment by retornam** [comment]
@gjtempleton can this be reviewed please. Thanks

**Comment by Shubham82** [comment]
@retornam, we only support the last three releases from the latest release. The latest release is CA v1.31 and so the supported releases are CA 1.28-1.30.

**Comment by Shubham82** [comment]
IMO we don't update the Golang version, Cluster Autoscaler uses the same go version that is used by embedded Kubernetes code.  For example, CA 1.27 will use the same go version as Kubernetes 1.27.

**Comment by retornam** [comment]
> IMO we can't update the Golang version here, Cluster Autoscaler uses the same go version that is used by embedded Kubernetes code. For example, CA 1.27 will use the same go version as Kubernetes 1.27.

@Shubham82  But there have been cases where old releases were upgraded for security related fixes to Golang, this is one of those cases.

**Comment by Shubham82** [comment]
@retornam, this will create a compatibility issue with k8s, also there will be no patch release for CA 1.27, see this issue:#7315

@gjtempleton @MaciekPytel WDYT?

**Comment by jackfrancis** [comment]
> IMO we can't update the Golang version here, Cluster Autoscaler uses the same go version that is used by embedded Kubernetes code. For example, CA 1.27 will use the same go version as Kubernetes 1.27.

This is the key for me as well.

https://github.com/kubernetes/kubernetes/blob/release-1.27/go.mod#L9

I don't see how we can cut 1) a new version that is already past the support window 2) with a version of golang that is 3 versions newer than the version of k/k at the equivalent release

**Comment by Shubham82** [comment]
> I don't see how we can cut 1) a new version that is already past the support window 2) with a version of golang that is 3 versions newer than the version of k/k at the equivalent release

IMO we can't do that.

cc @MaciekPytel @gjtempleton your thoughts on this?

Thanks!

**Pull request closed without merging**
