### PR TITLE
chore: defork labels and taints

### PR DESCRIPTION
**Pull request by charliedmcb**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This is part of the deforking effort for Azure.

There are certain adjustments to the labels/taints process that make sense for consideration when constructing the node, and should be ported in for better accuracy. 

This also, has some non-functional elements at the moment based on:
```
	inputLabels := map[string]string{}
	inputTaints := ""
```
These are inputs that'll be allowed as Azure specific settings within the future to allow for additional, more accurate expectations of labels/taints.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

```
	inputLabels := map[string]string{}
	inputTaints := ""
```
And the associated code are non-functional at the moment, but there will be a change coming down the line to make it functional. At the moment its just stubs to get the code in place, and should still work by taking the other still functional paths. 

#### Does this PR introduce a user-facing change?

```release-note
- Azure: certain scale from zero scenarios around labels will be more accurate
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by comtalyst** [comment]
Main changes lgtm. Is there anything in azure_template_test.go as well?

**Comment by charliedmcb** [comment]
> Main changes lgtm. Is there anything in azure_template_test.go as well?

Ok, with the change to passing in
> inputLabels := map[string]string{}
inputTaints := ""

instead of having them within the function, this should be all the fork changes for both:
- azure_scale_set.go
- azure_scale_set_test.go

I'm going to look at adding some more testing though if easily possibly

**Pull request merged**
