### PR TITLE
Bump default VPA version to 0.13.0

### PR DESCRIPTION
**Pull request by jbartosik**
#5355

This is for the master branch, #5462 is for the release branch

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @jbartosik , just want to confirm can we merge this once the VPA 0.13.0 will officially release or should we do that before.
Because this changes reflect on master branch.

If we can do it before then please tell me i will give it LGTM.

Thanks

**Comment by Shubham82** [comment]
Thanks @kgolab for looking at this.
I think yes, it should be part of vpa 0.13.0 release not the vpa 0.12.0. Please see the following link for vpa 0.12 release branch:
https://github.com/kubernetes/autoscaler/tree/vpa-release-0.12/vertical-pod-autoscaler/deploy

Also it will merge after vpa 0.12.0 branch cut. Here is PR for it: #5231 as the part of the PR #4799

**Comment by Shubham82** [comment]
I already opened a PR for it. Please find the same here: https://github.com/kubernetes/autoscaler/pull/5469

I will update it for master branch also, once vpa 0.13.0 will officially release or as per @jbartosik comments(when to do?) on this.

**Comment by jbartosik** [comment]
> Should we also change recommender-deployment-low.yaml and high files?

Done. I'll also update release instructions

**Pull request merged**
