### PR TITLE
Use ComponentConfig in Addon Resizer

### PR DESCRIPTION
**Pull request by kawych**

### CODE REVIEW

**Comment by kawych** [comment]
@piosz PTAL
@roberthbailey PTAL

**Comment by piosz** [comment]
@MaciekPytel please take a look or delegate.

**Comment by MaciekPytel** [comment]
@piosz @kawych: @mwielgus said he'll review this next week

**Comment by mwielgus** [comment]
How was it tested?

**Comment by kawych** [comment]
I've run it manually using this deployment: https://github.com/kawych/autoscaler/blob/component_config/addon-resizer/deployments/test.yaml
I've also checked what happens if the configuration is incomplete (e.g. base cpu and cpu per node undefined) or undefined. I've checked the values logged by pod nanny.

**Pull request merged**
