### PR TITLE
cluster-autoscaler: support evict DaemonSet pods in scale down

### PR DESCRIPTION
**Pull request by oif**
## Background

Currently CA scale down ignore DaemonSet controlled pods, but in a production cluster, this may result in those pods killed not graceful. may lose data, etc.
And currently, kubelet will not handle with Pods graceful shutdown will be shutting down. And also cloud providers may(there is no restriction) kill node directly.

## Aim to

Handle with DaemonSets graceful shutdown while scaling down

ref #1578

### CODE REVIEW

**Comment by joekohlsdorf** [comment]
I believe having this as a global setting is not good enough. Eviction might be necessary for some DaemonSets but not others, for example a log forwarder should be the last pod to go.

Instead of the proposed change I propose to evict DaemonSet pods if the `cluster-autoscaler.kubernetes.io/safe-to-evict` annotation is present.

**Comment by oif** [comment]
@joekohlsdorf 

Maybe use `cluster-autoscaler.kubernetes.io/safe-to-evict=false` is more suitable for this once enabled daemonset eviction in my mind.

This PR keep pending for a long time :(

**Pull request closed without merging**
