### PR TITLE
[CA]: hetzner cloud firewall feature

### LINKED ISSUE #4008: Cloudprovider Hetzner firewall feature
**Which component are you using?**: 

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: 

cluster-autoscaler for Hetzner currently doesn't provide firewall support for node-pools. 

**Describe the solution you'd like.**: 

cluster-autoscaler for Hetzner cloudprovider should have environment variable with Firewall ID, that will be applied to hosts running within node-pool

### PR DESCRIPTION
**Pull request by sergeyshevch**
Resolve #4008 

Adding support for hcloud firewall feature.
Upgrading hcloud client lib to 1.28.0

### CODE REVIEW

**Comment by sergeyshevch** [comment]
Most of changes in this PR just moved here from https://github.com/hetznercloud/hcloud-go last release. For using firewall feature of client lib we need to get newer version that was on autoscaler repo. So if it needed i can move it to another PR

**Comment by sergeyshevch** [comment]
@Jeffwan github also suggested you as a reviewer. Can you take a look?

**Comment by sergeyshevch** [comment]
@Jeffwan @aleksandra-malinowska Can someone of you look into this PR? I currently stopping works with Hetzner cloud and i guess it wil be good to review and merge this PR

**Comment by fgbreel** [comment]
Hello, I'm pretty much interested in this feature too because computers created by the `cluster-autoscaler` currently have no firewall assigned to them in Hetzner.

Thank you!

**Comment by AzSiAz** [comment]
@fgbreel Until this is merged you can use label feature of hetzner firewall, to have them automatically applied 😄

**Comment by fgbreel** [comment]
@AzSiAz Thanks for the tip, I will check that out!

**Comment by sergeyshevch** [comment]
@fgbreel I currently don't have an actual cluster setup on hetzner. I can rebase this PR but it was not reviewed by any contributor after a few pings. 

If you are interested in this please ping someone on k8s slack for review. 
I will rebase this PR in a few days

**Comment by fgbreel** [comment]
Thanks @sergeyshevch for the update. Will do it as soon I manage to find some time for it.

At the moment I'm using the labels to assign the firewall, targeting instances containing the `hcloud/node-group` label it as recommended by @AzSiAz and seems to work well.

**Comment by sergeyshevch** [comment]
@fgbreel @AzSiAz Sorry for delay. I rebased and updated this PR and will push it in k8s slack to continue the process

**Comment by sergeyshevch** [comment]
@LKaemmerling @Fgruntjes Looks like you wrote most of the code in this provider. Maybe it will be a good idea to add you to the OWNERS file?

**Comment by LKaemmerling** [comment]
Hey @sergeyshevch,

thank you for the ping and the great MR! We (Hetzner Cloud) maintain the parts already, and of course, it would be good if we were added to the Owners file. (The best would be me and @samcday).

I just reviewed your changes and they look fine from my side. So this is basically my 

/approve

**Review by LKaemmerling — APPROVED** [review]

**Comment by sergeyshevch** [comment]
@LKaemmerling Thanks for the review! I guess it will be good to add OWNERS file in separate PR

**Comment by sergeyshevch** [comment]
@LKaemmerling I cannot add you to OWNERS file because you are not in Kubernetes organization

**Comment by emrahcetiner** [comment]
any updates on this? @LKaemmerling

**Comment by sergeyshevch** [comment]
@emrahcetiner we need approve from @aleksandra-malinowska

**Review by mwielgus — APPROVED** [review]
/approve
/lgtm

**Comment by efpe** [comment]
When will this be released? Is there anything we can do to speed up the process?

**Pull request merged**
