### PR TITLE
Taint empty nodes to be deleted

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Mark empty nodes to be deleted with the same taint that is used for node drain.

### CODE REVIEW

**Comment by markine** [comment]
@mwielgus When can we expect this patch to end up in the 0.6.x release branch? I'm debugging v0.6.0 for a race between an empty node being terminated and the k8s scheduler placing new pods on the node as it is going down. The empty vs non-empty node drain code paths are distinct. The lack of a taint on the empty node during that process causes unexpected loss of one-shot job pods.

**Comment by mwielgus** [comment]
@markine Yes. Please file an issue to add it to 0.6 release so we don't forget.

**Comment by markine** [comment]
@mwielgus Thank you!

**Pull request merged**
