### PR TITLE
add required api resources to hetzner cluster-autoscaler example

### PR DESCRIPTION
**Pull request by gris-gris**
Hello, this is a little fix for ClusterRole of hetzner cluster-autoscaler example

### CODE REVIEW

**Comment by guyguy333** [comment]
@gris-gris Is it supposed to fix this error ?

> reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource

**Comment by gris-gris** [comment]
> @gris-gris Is it supposed to fix this error ?
> 
> > reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource

It fix issue with access denial when using autoscaler

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by mcristina422** [comment]
This is an issue across many providers, I just hit the same with the AWS manifest

**Pull request merged**
