### PR TITLE
Hetzner public IPv4 and IPv6 configuration

### PR DESCRIPTION
**Pull request by glehmann**
#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

It lets us use hetzner's new primary IP feature to disable the public IPv4/IPv6 addresses on the nodes

#### Does this PR introduce a user-facing change?

```release-note
Added Hetzner public IPv4 and IPv6 configuration.
```

### CODE REVIEW

**Comment by gjtempleton** [comment]
Tagging in @LKaemmerling based on comments in #3838

@LKaemmerling Are you or someone else from Hetzner able to give this a review?

**Review by LKaemmerling — APPROVED** [review]

**Comment by LKaemmerling** [comment]
This looks fine from my point of view :)

**Comment by gjtempleton** [comment]
One more request from me actually @LKaemmerling, is there any chance we could get an OWNERS file set up for the Hetzner cloudprovider in another PR? 

It doesn't even need to be member of the k8s org, we can comment out those who aren't members as with the Civo provider: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/civo/OWNERS. It'll make it easier for us to get reviews of CloudProvider specific code going forward.

**Comment by LKaemmerling** [comment]
@gjtempleton of course i will create a PR :)

**Review by feiskyer — APPROVED** [review]

**Pull request merged**
