### PR TITLE
update owners list for cluster autoscaler azure

### PR DESCRIPTION
**Pull request by gandhipr**
#### Which component this PR applies to?
cluster-autoscaler

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Updates owners list in azure-cluster autoscaler

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
     NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by marwanad** [comment]
😭 end of an era.

You can move me to `emeritus_approvers` list instead of removing.

Also, happy to sponsor the sig membership.

**Comment by gandhipr** [comment]
Sure, Marwan.
I wasn’t aware of that type of list.

**Comment by gandhipr** [comment]
Membership request - https://github.com/kubernetes/org/issues/3668

**Comment by gandhipr** [comment]
Do we have more pre-requisites before merging this PR in?

**Pull request merged**
