### PR TITLE
Upgrade aws-sdk-go to v1.28.14

### LINKED ISSUE #2829: Cluster-autoscaler does not work with VPC-Endpoint (AWS/EKS)
We do have a quite locked-down network in AWS (no internet-connectivity at all). Access to AWS services only via VPC endpoints and on-premise systems via DirectConnect. At the same time we would like to use IAM roles.

Kubernetes: 1.14
Cluster-Autoscaler: 1.14.7

When using cluster-autoscaler it cannot fetch credentials via STS using the IAM role. To my understanding the issue is caused by cluster-autoscaler not using the regional STS endpoint (https://sts.eu-central-1.amazonaws.com) but instead the global (https://sts.amazonaws.com). With VPC-Endpoints it is not possible to replace the global enpoint.

With github.com/aws/aws-sdk-go v1.25.18 
(see https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md) configuration of regional STS endpoints was introduced by setting env AWS_STS_REGIONAL_ENDPOINTS=regional

I tried setting the region as env AWS_REGION and AWS_STS_REGIONAL_ENDPOINTS but still the global endpoint is used. 

After looking at the 1.14 branch for cluster-autoscaler, it looks like v1.23.22 is used (see
https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.14/cluster-autoscaler/vendor/github.com/aws/aws-sdk-go/CHANGELOG.md)

I also checked the other cluster-autoscaler branches:
- 1.14 github.com/aws/aws-sdk-go v1.23.22
- 1.15 github.com/aws/aws-sdk-go v1.16.26
- 1.16 github.com/aws/aws-sdk-go v1.23.12
- 1.17 github.com/aws/aws-sdk-go v1.23.18
- master github.com/aws/aws-sdk-go v1.28.2

So I would assume that supporting such a use case would be possible by upgrading the aws-sdk-go version to >= v1.25.18 - let me know if I can be of help.

logs:
E0213 16:05:54.390164       1 aws_manager.go:259] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp 54.239.29.25:443: i/o timeout
F0213 16:05:54.390200       1 aws_cloud_provider.go:330] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp 54.239.29.25:443: i/o timeout

Attached you can find the kubernetes deployment yaml.
[deployment.txt](https://github.com/kubernetes/autoscaler/files/4199558/deployment.txt)

### PR DESCRIPTION
**Pull request by Jeffwan**
Resolve #2829 

1. ~The reason I delete `github.com/google/go-querystring` in go.mod-extra~
```
Operating in /tmp/ca-update-vendor.HPnf
Sending logs to: /tmp/ca-update-vendor.HPnf/ca-update-vendor.log
Updating vendor against git@github.com:kubernetes/kubernetes.git:v1.16.8
Cloning git@github.com:kubernetes/kubernetes.git into /tmp/ca-update-vendor.HPnf/kubernetes
Extra dependency github.com/google/go-querystring already used by k8s in >= version v1.0.0
Extra dependencies found in one of go.mod-extra files
Fix errors and rerun script:
 ./hack/update-vendor.sh -d/tmp/ca-update-vendor.HPnf -fgit@github.com:kubernetes/kubernetes.git -rv1.16.8
```

As we change to use 1.16.0-beta2, go-querystring needs to be imported separately.

2. Another commit is to fix broken `update-vendor.sh`, it has invalid command
https://github.com/kubernetes/autoscaler/blob/66383d0c3b2725075cfbb6625e4fb37636f87a5e/cluster-autoscaler/hack/update-vendor.sh#L188

https://github.com/kubernetes/autoscaler/blob/66383d0c3b2725075cfbb6625e4fb37636f87a5e/cluster-autoscaler/hack/update-vendor.sh#L192

Check difference between 1.16 and 1.17
https://www.diffchecker.com/ziUDo49S

3. I use ` ./hack/update-vendor.sh -rv1.16.8` to update dependencies.

### CODE REVIEW

**Comment by Jeffwan** [comment]
@mwielgus @jaypipes 

I used latest 1.16.x release version and that's the reason it brings many unrelated changes. To minimize the changes, I change back to previous version 1.16.0-beta2. PR only has AWS changes now.

**Comment by offzale** [comment]
Many thanks for the work, looking forward to this to get support on regional STS endpoints and IAM Roles for Service Accounts with the SDK update

**Comment by DzmitrySudnik** [comment]
When do you guys plan to release 1.16 with that fix in?

**Comment by Issif** [comment]
1.17 is coming for EKS, I guess the same issue will happen.

**Pull request merged**
