### PR TITLE
update huaweicloud sdk

### PR DESCRIPTION
**Pull request by wangshiqi308**
#### Which component this PR applies to?
cluster-autoscaler

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Huaweicloud SDK haven't been updated for 17 month, this PR is used to update Huaweicloud SDK in order to keep the version consistent
#### Which issue(s) this PR fixes:

N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Which version of SDK is used by this PR?

**Comment by RainbowMango** [comment]
@wangshiqi308 by the way, we had to copy the SDK file before because the go module was not enabled(see https://github.com/kubernetes/autoscaler/issues/3146), but now I think we can add the SDK in the go.mod file now.

I'm ok if you want to do it by following PR. looking forward you feedback.

**Comment by wangshiqi308** [comment]
This PR use the latest SDK version, and have already been tested. I will create another PR later on, I can put it in the go mod in the next PR

**Comment by RainbowMango** [comment]
I guess the added SDK version is `github.com/huaweicloud/huaweicloud-sdk-go-v3 v0.0.78` according to https://github.com/kubernetes/autoscaler/pull/4722, @wangshiqi308 can you confirm it?

**Pull request merged**
