### PR TITLE
[CA][HELM]fix not being able to set args without value

### LINKED ISSUE #4297: [Helmchart][Cluster-autoscaler]
**Which component are you using?**:

cluster autoscaler helmchart
**What version of the component are you using?**:

Component version: latest helm chart, 9.10.5

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"archive", BuildDate:"2021-07-16T17:16:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Cluster-API

**What did you expect to happen?**:

The helm chart allows me to set `--clusterapi-cloud-config-authoritative`
**What happened instead?**:

The helm chart doesnt allow to specify args without values, thus the autoscaler fails
```
invalid argument "" for "--clusterapi-cloud-config-authoritative" flag: parse error
```

**How to reproduce it (as minimally and precisely as possible)**:
set 
```
  extraArgs:
    clusterapi-cloud-config-authoritative: 

```
and run helm install 
**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by MaxRink**
This fixes #4297

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
thanks for fixing this!
/lgtm

**Comment by gjtempleton** [comment]
Hey, thanks for the PR!

This looks good, but you'll need to [bump the chart version here](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/Chart.yaml#L20) as well to allow a new version to be published.

**Comment by MaxRink** [comment]
Ive did a bit more testing and found an edge-case:
if you set an value to `false`, that false will now also not get templated.
I also know no easy way around this, as the check for emptyness explicitly considers false to be empty ( https://helm.sh/docs/chart_template_guide/function_list/#default )

**Comment by gjtempleton** [comment]
Unfortunately, there are a fair few boolean flags, [as you can see here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca), so we'll need to find a workaround for that edge cae.

**Comment by MaxRink** [comment]
```
            {{- if not (kindIs "invalid" $value) }}
            - --{{ $key | mustRegexFind "^[^_]+" }}={{ $value }}
            {{- else }}
            - --{{ $key | mustRegexFind "^[^_]+" }}
            {{- end }}
```
seems to work, ive tried with
```
extraArgs:
  clusterapi-cloud-config-authoritative:
  a: "False"
  b: true
  c: false
```
and got
```
          command:
            - ./cluster-autoscaler
            - --cloud-provider=clusterapi
            - --namespace=vsphere-tstsa1-bn
            - --a=False
            - --b=true
            - --c=false
            - --clusterapi-cloud-config-authoritative
            - --logtostderr=true
            - --stderrthreshold=info
            - --v=4
```

**Comment by gjtempleton** [comment]
Thanks for the fix. I've just merged #4276, so you'll need to bump the chart version again, unfortunately, but once that's done, this looks good to go to me!

**Comment by MaxRink** [comment]
@gjtempleton done :)

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by gjtempleton** [comment]
Thanks!
/approve

**Pull request merged**
