### PR TITLE
Add EC2 instance type p5.48xlarge

### PR DESCRIPTION
**Pull request by ricardov1**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Enables the use of p5.48xlarge instances in node groups

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gjtempleton** [comment]
Thanks, are you wanting to cherry-pick this any further back given the versions currently supported by EKS?
/approve
/lgtm

**Comment by ricardov1** [comment]
hey @gjtempleton, good point. yes that would make sense too. which versions would that be? I can't find any docs on the versions supported by EKS

**Comment by gjtempleton** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

**Comment by gjtempleton** [comment]
I wouldn't raise it as far back as 1.23 with it still being in extended support, I think we may only be cutting releases as far back as 1.25 this time round.

**Comment by ricardov1** [comment]
@gjtempleton awesome, thanks! I've opened PRs for 1.25, 1.26 and 1.27
https://github.com/kubernetes/autoscaler/pull/6286
https://github.com/kubernetes/autoscaler/pull/6287
https://github.com/kubernetes/autoscaler/pull/6285

**Pull request merged**
