### PR TITLE
Adding app.kubernetes.io/version label to cluster-autoscaler.labels

### PR DESCRIPTION
**Pull request by psimms-r7**
#### What this PR does / why we need it:

Adding app.kubernetes.io/version label to cluster-autoscaler.labels
In order to track versions

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @psimms-r7
Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by Shubham82** [comment]
@psimms-r7 Please sign the CLA so that this PR will merge.

**Comment by Shubham82** [comment]
Hi @psimms-r7  please signs the CLA

**Comment by Shubham82** [comment]
@psimms-r7  are you working on this PR?

**Comment by gjtempleton** [comment]
Going to close for now given lack of response and signed CLA. #6012 is also addressing this and in a more mergeable state.
/close

**Pull request closed without merging**
