### PR TITLE
cluster-autoscaler Azure: update cloud-provider-azure to v1.28.0

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR updates the cloud-provider-azure dependency to use the latest, v1.28.0 release.

Ref:

- https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.28.0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
Pinging @BigDarkClown @feiskyer @x13n for a review. In the meantime I am performing manual tests of various Azure scenarios (CAPZ, AKS).

Thank you!

**Comment by jackfrancis** [comment]
O.K., tested these changes out thusly:

Produced and hosted an image built from this commit:

```sh
$ git status
On branch cloud-provider-azure-v1.28.0
Your branch is up to date with 'origin/cloud-provider-azure-v1.28.0'.

nothing to commit, working tree clean
$ TAG=f8103a4c9 make build
rm -f cluster-autoscaler-amd64
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cluster-autoscaler-amd64 --ldflags "-s"
$ REGISTRY=docker.io/jackfrancis TAG=f8103a4c9 make make-image
docker build --pull \
		-t docker.io/jackfrancis/cluster-autoscaler-amd64:f8103a4c9 \
		-f Dockerfile.amd64 .
[+] Building 2.1s (7/7) FINISHED                                                                                                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile.amd64                                                                                                                                                         0.0s
 => => transferring dockerfile: 866B                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                    0.0s
 => [internal] load metadata for gcr.io/distroless/static:nonroot-amd64                                                                                                                                            0.4s
 => [internal] load build context                                                                                                                                                                                  1.7s
 => => transferring context: 159.45MB                                                                                                                                                                              1.7s
 => [1/3] FROM gcr.io/distroless/static:nonroot-amd64@sha256:1b4dbd7d38a0fd4bbaf5216a21a615d07b56747a96d3c650689cbb7fdc412b49                                                                                      0.0s
 => CACHED [2/3] COPY cluster-autoscaler-amd64 /cluster-autoscaler                                                                                                                                                 0.0s
 => exporting to image                                                                                                                                                                                             0.0s
 => => exporting layers                                                                                                                                                                                            0.0s
 => => writing image sha256:3de27f3f6d904bf48da408cca496d73219e7deb3f1f68d003f56de1e04d9de18                                                                                                                       0.0s
 => => naming to docker.io/jackfrancis/cluster-autoscaler-amd64:f8103a4c9                                                                                                                                          0.0s

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
Image f8103a4c9-amd64 completed
$ REGISTRY=docker.io/jackfrancis TAG=f8103a4c9 make push-image
./push_image.sh docker.io/jackfrancis/cluster-autoscaler-amd64:f8103a4c9
About to push image docker.io/jackfrancis/cluster-autoscaler-amd64:f8103a4c9
Are you sure? [y/N] y
Error response from daemon: manifest for jackfrancis/cluster-autoscaler-amd64:f8103a4c9 not found: manifest unknown: manifest unknown
The push refers to repository [docker.io/jackfrancis/cluster-autoscaler-amd64]
9eda9f83110c: Pushed 
4cb10dd2545b: Mounted from jackfrancis/azure-cloud-node-manager 
d2d7ec0f6756: Mounted from jackfrancis/azure-cloud-node-manager 
1a73b54f556b: Mounted from jackfrancis/azure-cloud-node-manager 
e624a5370eca: Mounted from jackfrancis/azure-cloud-node-manager 
d52f02c6501c: Mounted from jackfrancis/azure-cloud-node-manager 
ff5700ec5418: Mounted from jackfrancis/azure-cloud-node-manager 
7bea6b893187: Pushed 
6fbdf253bbc2: Mounted from jackfrancis/azure-cloud-node-manager 
e023e0e48e6e: Pushed 
f8103a4c9: digest: sha256:1502bb5a7775364d9d6362ea366559242fac3ff4a6e5e16da9c9719e55624454 size: 2402
```

For the AKS test, I built a `v1.25.11` cluster (w/ the AKS built-in autoscaler disabled) and then installed the custom built autoscaler using the helm chart:

```sh
$ helm install cluster-autoscaler cluster-autoscaler --repo https://kubernetes.github.io/autoscaler --set cloudProvider=azure --set autoscalingGroups[0].name=aks-nodepool2-10855719-vmss,autoscalingGroups[0].maxSize=100,autoscalingGroups[0].minSize=0 --set azureClientID=$TEST_AZURE_SP_ID --set azureClientSecret=$TEST_AZURE_SP_PW --set azureSubscriptionID=$TEST_AZURE_SUB_ID --set azureTenantID=$TEST_AZURE_TENANT_ID --set azureClusterName=francis-aks-test --set azureResourceGroup=MC_francis-aks-test_francis-aks-test_eastus --set azureVMType=vmss --set image.repository=docker.io/jackfrancis/cluster-autoscaler-amd64 --set image.tag=f8103a4c9
```

Validated scale out and in, and scale to and from zero with no problems on the AKS cluster.

Next, I validated CAPZ (Cluster API cluster-autoscaler provider) from a test branch I'm maintaining. Relevant test source:

- https://github.com/jackfrancis/cluster-api-provider-azure/blob/cluster-autoscaler-e2e/test/e2e/cluster_autoscaler.go

I manually updated the helm config so it would use the custom-built bits:

```sh
diff --git a/test/e2e/cluster_autoscaler.go b/test/e2e/cluster_autoscaler.go
index e3405dd4b..a637ad6d5 100644
--- a/test/e2e/cluster_autoscaler.go
+++ b/test/e2e/cluster_autoscaler.go
@@ -88,6 +88,8 @@ func InstallClusterAutoscaler(ctx context.Context, inputGetter func() ClusterAut
                                fmt.Sprintf("autoDiscovery.clusterName=%s", input.ClusterName),
                                fmt.Sprintf("clusterAPIKubeconfigSecret=%s-kubeconfig", input.ClusterName),
                                "clusterAPIMode=kubeconfig-incluster",
+                               "image.repository=docker.io/jackfrancis/cluster-autoscaler-amd64",
+                               "image.tag=f8103a4c9",
                        },
                        StringValues: []string{
                                "extraArgs.scan-interval=1m",
```

Confirmed my Cluster API mgmt cluster was using the right image during the test:

```sh
$ k get deployment/cluster-autoscaler-azure-cluster-autoscaler -o yaml | grep 'image:'
        image: docker.io/jackfrancis/cluster-autoscaler-amd64:f8103a4c9
```

CAS test scenarios passed:

```sh
  Sep 22 11:37:57.647: INFO: Helm command: /Users/jackfrancis/go/src/sigs.k8s.io/cluster-api-provider-azure/hack/tools/bin/helm upgrade cluster-autoscaler-capz-e2e-ylbxft-ha cluster-autoscaler --install --kubeconfig /Users/jackfrancis/.kube/config --create-namespace --namespace capz-e2e-ylbxft --repo https://kubernetes.github.io/autoscaler --set-string extraArgs.scan-interval=1m --set extraArgs.balance-similar-node-groups=true --set cloudProvider=clusterapi --set autoDiscovery.clusterName=capz-e2e-ylbxft-ha --set clusterAPIKubeconfigSecret=capz-e2e-ylbxft-ha-kubeconfig --set clusterAPIMode=kubeconfig-incluster --set image.repository=docker.io/jackfrancis/cluster-autoscaler-amd64 --set image.tag=f8103a4c9
  Sep 22 11:37:59.464: INFO: Helm install output: Release "cluster-autoscaler-capz-e2e-ylbxft-ha" does not exist. Installing it now.
  NAME: cluster-autoscaler-capz-e2e-ylbxft-ha
  LAST DEPLOYED: Fri Sep 22 11:37:58 2023
  NAMESPACE: capz-e2e-ylbxft
  STATUS: deployed
  REVISION: 1
  TEST SUITE: None
  NOTES:
  To verify that cluster-autoscaler has started, run:

    kubectl --namespace=capz-e2e-ylbxft get pods -l "app.kubernetes.io/name=clusterapi-cluster-autoscaler,app.kubernetes.io/instance=cluster-autoscaler-capz-e2e-ylbxft-ha"

  Sep 22 11:37:59.465: INFO: Listing deployments in namespace capz-e2e-ylbxft with label app.kubernetes.io/name=clusterapi-cluster-autoscaler
  Sep 22 11:38:09.476: INFO: Listing deployments in namespace capz-e2e-ylbxft with label app.kubernetes.io/name=clusterapi-cluster-autoscaler
  STEP: Scaling out via cluster-autoscaler @ 09/22/23 11:38:09.48
  STEP: Creating a Kubernetes client to the workload cluster @ 09/22/23 11:38:09.48
  STEP: Calculating how many pod replicas we need to scale out to maximum @ 09/22/23 11:38:09.499
  STEP: creating an HTTP deployment with 770 replicas @ 09/22/23 11:38:09.505
  STEP: Verifying that all cluster-autoscaler-enabled MachineDeployments have scaled out @ 09/22/23 11:38:09.641
  STEP: Deleting deployment in order to delete pod replicas @ 09/22/23 11:41:29.797
  STEP: Verifying that all cluster-autoscaler-enabled MachineDeployments have scaled in @ 09/22/23 11:41:30.279
  STEP: PASSED! @ 09/22/23 11:41:30.279
```

@BigDarkClown @feiskyer @x13n let me know if there's more info I can provide to aid a review. Thanks!

**Comment by jackfrancis** [comment]
cc @tallaxes @gandhipr

**Comment by jackfrancis** [comment]
@BigDarkClown @x13n you may ignore I was looking at the wrong OWNERS file :)

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
