### PR TITLE
Adjust path for volume ssl-certs (up)

### PR DESCRIPTION
**Pull request by marcelobrake**

### CODE REVIEW

**Comment by Jeffwan** [comment]
@marcelobrake Did you get a chance to see the README.md? Debian and Amazon linux2 setting is different, you need to change it by yourself. Most users are still on AL2.

**Comment by mwielgus** [comment]
Inactivity warning - CLA not signed. No response for @Jeffwan comment for 2 months.

**Comment by mwielgus** [comment]
Closing due to inactivity and not signed CLA. Feel free to reopen if needed.

**Pull request closed without merging**
