### PR TITLE
Vertical Pod Autoscaler release 0.9.1

### PR DESCRIPTION
**Pull request by jbartosik**
To include #3729

### CODE REVIEW

**Comment by jbartosik** [comment]
@bskiba please take a look

**Comment by jbartosik** [comment]
There is one more change I think I might want to have in the release. Putting on hold until I check

**Comment by jbartosik** [comment]
I would like to get #3744 in (and cherry pick it into this branch) before cutting the next release

**Comment by jbartosik** [comment]
#3744 merged, now I want to cherry pick it into the 0.9 branch (#3748) and then cancel the hold

**Comment by jbartosik** [comment]
#3748 merged

/hold cancel

**Comment by johanneswuerbach** [comment]
It looks like this release never went out, should it already be pushed?

**Pull request merged**
