### PR TITLE
[CA-1.18] #2983 cherry-pick: ClusterAPI Provider: Provide fake proivder IDs for failed Machines

### PR DESCRIPTION
**Pull request by detiber**
his PR proposes to backport #2983 to the `cluster-autoscaler-release-1.18` branch.

From the original PR:
> Some ClusterAPI implementations will mark a Machine as failed if there is a problem creating the instance on the cloud provider. In this case, these instances weren't being considered as bad and the autoscaler considered them to be `comingUp`. With this patch in, after the `maxNodeProvisionTime` is reached, the autoscaler marks the nodegroup as unhealthy, scales it down (removing the unhealthy machine), and then tries to scale up an alternate group, matching the behaviour seen with the AWS provider once that was patched

### CODE REVIEW

**Comment by detiber** [comment]
/hold
will likely need to be rebased after #3171

**Comment by detiber** [comment]
Currently includes the commit from #3171

**Comment by detiber** [comment]
/hold cancel
canceling hold, since #3171 has merged.

**Comment by elmiko** [comment]
thanks Jason!

/approve

**Pull request merged**
