### PR TITLE
Delete unused err  returns

### PR DESCRIPTION
**Pull request by peaaceChoi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Delete unused err returns
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by grosser — APPROVED** [review]
nice find :D

**Comment by peaaceChoi** [comment]
@grosser  thank you :)

**Comment by peaaceChoi** [comment]
Hello, Any chances for review?

**Comment by grosser** [comment]
need to either hunt ppl down in slack or find someone with merge power :(

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
