### PR TITLE
CA - AWS - Instance List Update 29-10-21 - 1.19 release branch

### LINKED ISSUE #4427: Support c6i.* AWS EC2 instance type
**Which component are you using?**:
Need to add new [c6i.* instance types](https://aws.amazon.com/blogs/aws/new-amazon-ec2-c6i-instances-powered-by-the-latest-generation-intel-xeon-scalable-processors/) to AWS EC2 instance types list so CA is able to scale them.

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

**Describe the solution you'd like.**:

**Describe any alternative solutions you've considered.**:

**Additional context.**:
Similar PR #4379 #4380 #4381 #4382

### PR DESCRIPTION
**Pull request by sturman**
Fix #4427

### CODE REVIEW

**Comment by gjtempleton** [comment]
Thanks, before I approve this one, would you mind squashing the commits down to one please?

(I'm also slightly confused as to why my previous PR to this release branch was apparently missing so many instance types, but that's not an issue for this PR.)

**Comment by sturman** [comment]
Hi @gjtempleton. I've just squashed commits. Please review. Thanks

**Review by feiskyer — APPROVED** [review]

**Review by jaypipes — APPROVED** [review]
:+1:

**Pull request merged**
