### PR TITLE
Add g4dn instance type for AWS

### PR DESCRIPTION
**Pull request by Luke035**
Just added newly created AWS g4dn EC2 instances type on EC2 catalog

### CODE REVIEW

**Comment by Luke035** [comment]
CLA just signed, waiting for approval

**Comment by seh** [comment]
Is this a full regeneration, per the suggestion in #2376?

**Comment by Jeffwan** [comment]
Even #2249 is done, we need a static list. Thanks. I will merge this one. 

/lgtm
/approve

**Comment by seh** [comment]
It's strange, though, that now we have the "g4dn" part of the family, but none of the rest of the "g4" family.

**Comment by Jeffwan** [comment]
@seh yeah. At the beginning, aws give name `g4` but eventually change to `g4dn`.

**Comment by Luke035** [comment]
I just want to add that, for the moment, g4dn are not supported in EKS (https://aws.amazon.com/it/blogs/aws/now-available-ec2-instances-g4-with-nvidia-t4-tensor-core-gpus/). Autoscaler works fine but the related EKS AMI still don't support NVIDIA T4. @Jeffwan do you know if there's any plan to support them soon?

**Comment by Luke035** [comment]
> I just want to add that, for the moment, g4dn are not supported in EKS (https://aws.amazon.com/it/blogs/aws/now-available-ec2-instances-g4-with-nvidia-t4-tensor-core-gpus/). Autoscaler works fine but the related EKS AMI still don't support NVIDIA T4. @Jeffwan do you know if there's any plan to support them soon?

Ok, never mind https://aws.amazon.com/it/about-aws/whats-new/2019/09/amazon-eks-adds-support-for-g4-instance/

**Comment by seh** [comment]
> At the beginning, aws give name `g4` but eventually change to `g4dn`.

Oh, I hadn't noticed that, but I see it reflected in [the page on the G4 family](https://aws.amazon.com/ec2/instance-types/g4/#Product_Details) now. Thank you for pointing that out.

This isn't the first instance type family to include "dn" in a few of the names. Do you happen to know what "dn" stands for?

**Comment by Luke035** [comment]
> > At the beginning, aws give name `g4` but eventually change to `g4dn`.
> 
> Oh, I hadn't noticed that, but I see it reflected in [the page on the G4 family](https://aws.amazon.com/ec2/instance-types/g4/#Product_Details) now. Thank you for pointing that out.
> 
> This isn't the first instance type family to include "dn" in a few of the names. Do you happen to know what "dn" stands for?

I think that `d` stands for disk attached (in fact if you manually launch the instance, you'll notice an additional disk attached) and `n` for network optimized. But it's just an hypothesis

**Comment by Jeffwan** [comment]
Yeah. We just release support for G4 family on EKS this Monday. p3dn is the first one with `dn` in the name. I don't even know EC2 have the `dn` in the name. looks like @Luke035 hypothsis is correct. All `dn` instances have local SSD or NVMe and better network (25 Gigbit or more).

**Pull request merged**
