### PR TITLE
VPA: Remove TLS client cert lookup logic

### PR DESCRIPTION
**Pull request by forkbomber**
Actual verification was turned off from the initial commit and is still [not enabled](../blob/6b1a97c16001a98607424568faf7239b5c364d11/vertical-pod-autoscaler/pkg/admission-controller/config.go#L79), so the whole construct does not add value.

Also depending on `requestheader-client-ca-file` by itself renders VPA incompatible with apiserver installations which does not use such certificate with VPA Admission Controller crash-looping with:
`vpa-admission-controller-X-Y:admission-controller F0214 18:15:09.448204       9 config.go:60] cannot find the ca.crt in the configmap, configMap.Data is map[string]string{"client-ca-file":"...skipped..."}`

In addition to the above it worth noting that `requestheader-client-ca-file` appears to be just a wrong place to look for _possible_ apiserver client certificate (I don't think there is any).

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @schylek

**Comment by mwielgus** [comment]
Doesn't compile. Please fix.

**Comment by forkbomber** [comment]
@mwielgus, thanks, cleaned up unused imports.

**Comment by mwielgus** [comment]
@tkulczynski - I believe you are the one who implemented this. Could you please take a look at the PR? Is this code needed?

**Comment by schylek** [comment]
cc: @jbartosik

**Comment by jbartosik** [comment]
I'll take a look later today.

**Comment by jbartosik** [comment]
/lgtm
looks like dead code to me

**Comment by bskiba** [comment]
Thanks @joachim! 
/approve

**Pull request merged**
