### PR TITLE
Switch leader election mechanism to use lease objects

### PR DESCRIPTION
**Pull request by krmayankk**
fixes https://github.com/kubernetes/autoscaler/issues/944

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
/lgtm
/approve
/hold

This change requires another PR, to fix [RBACs for Cluster Autoscaler](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/rbac/cluster-autoscaler/cluster-autoscaler-rbac.yaml). Could you send that as well?

**Comment by krmayankk** [comment]
sure @aleksandra-malinowska working on it

**Comment by krmayankk** [comment]
@aleksandra-malinowska could you merge this since we are waiting for this PR to merge before we can move forward with the core addons change ? https://github.com/kubernetes/kubernetes/pull/77895/files

**Comment by krmayankk** [comment]
@mwielgus @MaciekPytel  @bskiba  can one of you help with this ?

**Comment by losipiuk** [comment]
@krmayankk I will merge this. And merge the RBAC PR together with update of `cluster-autoscaler.manifest` in k/k repo when we have first alpha release for 1.17 ready (as discussed with @liggitt). Please reword the commit message to "Switch leader election mechanism to use lease objects"

**Comment by krmayankk** [comment]
@losipiuk done

> @krmayankk I will merge this. And merge the RBAC PR together with update of `cluster-autoscaler.manifest` in k/k repo when we have first alpha release for 1.17 ready (as discussed with @liggitt). Please reword the commit message to "Switch leader election mechanism to use lease objects"

done

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!

**Comment by tghartland** [comment]
@krmayankk @losipiuk This is an issue with the vendored code in `vendor/k8s.io/kubernetes/pkg/client/leaderelectionconfig/config.go`, but the --help information about the default of this option is now inconsistent:
```
--leader-elect-resource-lock endpoints
The type of resource object that is used for locking during leader election.
Supported options are endpoints (default) and `configmaps`. (default "leases")
```
I can make an issue for that over in kubernetes/kubernetes.

**Comment by losipiuk** [comment]
> @krmayankk Łukasz Osipiuk This is an issue with the vendored code in `vendor/k8s.io/kubernetes/pkg/client/leaderelectionconfig/config.go`, but the --help information about the default of this option is now inconsistent:
> 
> ```
> --leader-elect-resource-lock endpoints
> The type of resource object that is used for locking during leader election.
> Supported options are endpoints (default) and `configmaps`. (default "leases")
> ```
> 

Good catch. The textual part should not specify what is the default object type used for leader eleaction. It should be cleaned up in k8s.io/kuberenetes. 

> I can make an issue for that over in kubernetes/kubernetes.

I guess one-line PR would be better. Are you fine with sending that?

**Comment by losipiuk** [comment]
Oh - I missed you created #83391 already. Thanks!

**Pull request merged**
