### PR TITLE
Drop VPA vendor directory in favor of Go modules

### PR DESCRIPTION
**Pull request by fmuyassarov**
#### What type of PR is this?
/kind cleanup
/kind deprecation

#### What this PR does / why we need it:
Drop `vertical-pod-autoscaler` vendor directory in favor of Go modules. We're started this process
from `cluster-autoscaler` in https://github.com/kubernetes/autoscaler/pull/6572.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/autoscaler/issues/4878

#### Special notes for your reviewer:
After this I will file one more PR for dropping vendor-directory in `addon-resizer` too.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x13n** [comment]
#4878 was specifically about CA. We need to check with VPA owners if this is also a desired change here.

/assign kwiesmueller

**Comment by kwiesmueller** [comment]
Personally I prefer having a vendor directory as it makes it way easier to review the actual code being patched in PRs (which is getting more and more essential in a time where supply chain attacks are on the rise).
We still need CI that checks that the checked-in vendor files match the mod file to avoid malicious vendor check-ins, but the review ergonomics become way better with a vendor dir.

/assign @raywainman @voelzmo 
Marco, Ray, what do you think?

**Comment by kwiesmueller** [comment]
Another argument from my personal experience with this discussion (I can't count anymore how many projects we had this discussion on), is that CI usually became slower and flakier (network issues) when we relied on the build process pulling the vendors every build. Not sure if we have good enough caching on GitHub.

**Pull request closed without merging**
