### PR TITLE
Remove/update spamming logs 

### PR DESCRIPTION
**Pull request by damikag**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR removes some unnecessary logs in `compare_nodegroups.go` and `filter_out_daemon_sets.go`
And also change some Warnings to v5 Info in `clusterstate.go` and `pre_filtering_processor.go`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
Some CA logs are removed and updated the level and type.

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by elmiko** [comment]
removing these logs has made debugging node balancing failures much more difficult. is there an objection to re-adding these at log level 5 or something?

cc @x13n @towca , we have been using these logs to triage issues and i am surprised to find that they have been removed.

**Comment by x13n** [comment]
I think adding back at V(5) is ok if they were useful to debug issues. What
we observed on our end was mainly spam. Would you mind creating a PR to
reintroduce them at V(5)?

**Comment by elmiko** [comment]
thanks @x13n , i've created #8266

**Pull request merged**
