### PR TITLE
Switch AdmissionReview from v1beta1 to v1

### PR DESCRIPTION
**Pull request by adriananeci**
This PR updates AdmissionReview from v1beta1 to v1. In V1, the UID field is mandatory and should be copied from the `request.uid` sent to the webhook based on https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#response

No other notable changes between AdmissionReview `v1beta1` and `v1`. AdmissionReview `v1` is available since k8s v1.16.

### CODE REVIEW

**Review by jbartosik — COMMENTED** [review]
Thank you.

I have some questions about migration:

1) Can we drop dependency on `v1beta1` admission API?
2) If I have an existing cluster, with VPA webhook created using `v1beta1` admission API and switch to VPA using `v1` admission API what will happen? Will we overwrite the existing webhook? Will we have 2 webhooks?
3) What will happen if I need to rollback VPA to an older version? So I'll switch from VPA using `v1` admission API to older VPA using `v1beta1` admission API?

**Comment by adriananeci** [comment]
> 1. Can we drop dependency on `v1beta1` admission API?

Yes, just removed `v1beta1` dependency

> 2. If I have an existing cluster, with VPA webhook created using `v1beta1` admission API and switch to VPA using `v1` admission API what will happen? Will we overwrite the existing webhook? Will we have 2 webhooks?

Tested it on a kind cluster and the old webhook will be replaced with the new one having
```
- admissionReviewVersions:
    - v1
```

> 3. What will happen if I need to rollback VPA to an older version? So I'll switch from VPA using `v1` admission API to older VPA using `v1beta1` admission API?

Everything should go smooth since the `MutatingWebhookConfiguration` will be recreated with `admissionReviewVersions` set to `v1beta1`.

Validated it on a kind cluster:
- deploy VPA using `./hack/vpa-up.sh`. 
- deploy the hamster example(`k apply -f examples/hamster.yaml`) and validate the vpa object status
```
❯ k get vpa
NAME          MODE   CPU    MEM       PROVIDED   AGE
hamster-vpa   Auto   587m   262144k   True       23m
```

- build a new admission-controller image with changes from this PR using
```
make build-in-docker-amd64 docker-build-amd64 REGISTRY=test TAG=test
```
- loaded the new image into the kind cluster using 
```
kind load docker-image test/vpa-admission-controller-amd64:test --name test-cluster
``` 
- edit the `vpa-admission-controller` deployment and swap the official image with the freshly built one
- check the `vpa-webhook-config` mutatingwebhookconfiguration object and its `admissionReviewVersions` value
```
k get mutatingwebhookconfigurations.admissionregistration.k8s.io -oyaml
```
- edit the `vpa-admission-controller` deployment and switch back to the official image(`k8s.gcr.io/autoscaling/vpa-admission-controller:0.9.2`)
- re-validate everything is working as expected(webhook config, vpa components logs, vpa object, etc)

**Review by jbartosik — COMMENTED** [review]
Thank you for the answering quickly. This PR mostly looks good to me but I have a few small requests.

Please:
- fix commit message `AdmissionReviw` misses letter 'e'  and
- squash commits,
- sync (I think with #4538 merged I think there will be a small conflict to resolve).

**Comment by adriananeci** [comment]
Rebased from master, squashed commits and fixed commit message

**Review by jbartosik — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
