### PR TITLE
allow cluster-autoscaler to downscale CAPI machines that haven't joined the cluster

### PR DESCRIPTION
**Pull request by wmgroot**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Cluster Autoscaler CAPI currently does not downscale node groups with Machines in the Provisioning status.
```
$ kubectl get machinedeployment -n capi-awscmhqa2 --context awscmhqa2 worker-private-m6a-az3        
NAME                     CLUSTER     REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE   VERSION
worker-private-m6a-az3   awscmhqa2   25         6       25        19            ScalingUp   89d   v1.24.7
```

Cluster Autoscaler correctly notices that these nodes are unnecessary and scaling this node group down is the right thing to do. However, the downscale logic for CAPI specifically has a check to ensure that in-use nodes aren't removed.
```
I0313 19:23:28.788010       1 static_autoscaler.go:712] Decreasing size of MachineDeployment/capi-awscmhqa2/worker-private-m6a-az3, expected=25 current=6 delta=-19
E0313 19:23:28.988607       1 static_autoscaler.go:444] Failed to fix node group sizes: failed to decrease MachineDeployment/capi-awscmhqa2/worker-private-m6a-az3: attempt to delete existing nodes targetSize:25 delta:-19 existingNodes: 25
```

The 6 Ready nodes are fully registered in the K8s cluster. The remaining 19 are stuck in a Provisioning state, in this case due to insufficient capacity in AWS for the m6a instance type.
```
$ kubectl get machine -n capi-awscmhqa2 --context awscmhqa2 | grep worker-private-m6a-az3   
worker-private-m6a-az3-6b8b4fbb4c-55zdl                           awscmhqa2                                                                                          Provisioning   5m25s   v1.24.7
worker-private-m6a-az3-6b8b4fbb4c-5h9xs                           awscmhqa2   ip-10-115-231-233.us-east-2.compute.internal   aws:///us-east-2c/i-0e3aa6f214307eef7   Running        3d3h    v1.24.7
worker-private-m6a-az3-6b8b4fbb4c-6jd9f                           awscmhqa2                                                                                          Provisioning   5m16s   v1.24.7
```

#### Which issue(s) this PR fixes:
Cluster Autoscaler should be able to downscale the 19 nodes that never joined the cluster in this situation. This will be possible if the DecreaseTargetSize() function for CAPI only checks against nodes that have actually registered with the cluster, instead of all Machine resources for the node group in question.

#### Does this PR introduce a user-facing change?
```release-note
Fixed an issue where Cluster Autoscaler would not scale down CAPI node groups until after Provisioning nodes had joined the cluster.
```

### CODE REVIEW

**Comment by wmgroot** [comment]
Let me adjust the commit via rebase and try that reopen command.

**Comment by elmiko** [comment]
@wmgroot i think you might need to issue the `/reopen` command, at least, that was my reading of https://prow.k8s.io/command-help?repo=kubernetes%2Fautoscaler

**Comment by wmgroot** [comment]
Thanks for the help, I think everything is in order now.

**Comment by elmiko** [comment]
i'm not sure why we stalled out here, apologies for letting this fall through. i will try to do another review this week, i can't remember if we had any pushback on this change.

**Pull request closed without merging**
