### PR TITLE
Bump VPA builder Go version

### PR DESCRIPTION
**Pull request by voelzmo**
#### Which component this PR applies to?

vertical-pod-autoscaler
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
Bump the Go version to the most recent 1.17 release, such that we can cut a new release

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by jbartosik** [comment]
Sounds good to me. Could you clarify this part, please:

> such that we can cut a new release

How does using 1.17.2 instead of 1.17.0 affect a release? (I don't plan to cut new VPA release until K8s 1.25)

**Comment by voelzmo** [comment]
> I don't plan to cut new VPA release until K8s 1.25

I wasn't sure what your release plans were, and should have asked about this, sorry.
We have some internal discussions going on, now that people discovered that the Go version on the VPA was pretty outdated (0.10.0 still used Go 1.14) for a long time, and now they're watching closely when/if we're returning to a non-EOL version.
If I understand correctly, you're going to cut a new VPA release somewhat soon after August 23rd?

**Comment by jbartosik** [comment]
> > I don't plan to cut new VPA release until K8s 1.25
> 
> I wasn't sure what your release plans were, and should have asked about this, sorry. We have some internal discussions going on, now that people discovered that the Go version on the VPA was pretty outdated (0.10.0 still used Go 1.14) for a long time, and now they're watching closely when/if we're returning to a non-EOL version. If I understand correctly, you're going to cut a new VPA release somewhat soon after August 23rd?

Yes, I want to cut a new release soon after 1.25 (so if there are no delays to the [release](https://www.kubernetes.dev/resources/release/) soon after 2022-08-23). Last time I was doing a release there was some delay (e2e started failing around the so I needed to fix them). I hope this time things go smoothly.

---

This PR is to make sure we're using up to date Go version in the next VPA version?

**Comment by voelzmo** [comment]
Ok, thanks for the explanations regarding the plans for the next release.

> This PR is to make sure we're using up to date Go version in the next VPA version?

Yes, that was the intention.

**Review by jbartosik — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
