### PR TITLE
move huaweicloud sdk to go mod

### PR DESCRIPTION
**Pull request by wangshiqi308**
#### Which component this PR applies to?
cluster-autoscaler

#### What type of PR is this?
/kind feature
/kind cleanup

#### What this PR does / why we need it:
We had to copy the SDK file before because the go module was not enabled(see https://github.com/kubernetes/autoscaler/issues/3146), but in this PR we put our SDK in the go.mod file

#### Which issue(s) this PR fixes:

N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by mwielgus** [comment]
I'm sorry but we cannot accept this PR. All cloud providers should have their dependencies vendored into their directories. The only dependencies that can be in go mod is those who already exist or those who are transitive dependencies of Kubernetes.

**Pull request closed without merging**
