### PR TITLE
CA Chart - Cleanup Chart Maintainers

### PR DESCRIPTION
**Pull request by gjtempleton**
#### Which component this PR applies to?

CA Helm Chart.

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Removes old maintainers from the Chart.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

cc: @yurrriq @sc250024 @mgoodness  please let me know if any of you actually still want to be involved in maintaining this, however figured best to remove the risk of any of you being pestered to support something you're no longer actively involved with.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks for checking. It looks like [my last commit was 5 November, 2019 in the old repo](https://github.com/helm/charts/commit/87034ca03fc4ee2e7c8f90c523df330c577b1ceb) and the history wasn't preserved here. Please feel free to remove me. :smiley:

**Review by yurrriq — APPROVED** [review]

**Comment by sc250024** [comment]
Go ahead 🫡

**Comment by x13n** [comment]
Looks like this doesn't need to hang.
/lgtm

**Pull request merged**
