### PR TITLE
Use print() function in both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

### CODE REVIEW

**Comment by cclauss** [comment]
Why does my CLA https://identity.linuxfoundation.org/users/cclauss fail the test??

**Comment by dankohn** [comment]
Please email Linux Foundation Helpdesk <helpdesk@rt.linuxfoundation.org> and they will help you resolve.

**Comment by cclauss** [comment]
I signed it

**Comment by cclauss** [comment]
I signed it

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
