### PR TITLE
update azure static sku list

### PR DESCRIPTION
**Pull request by rrangith**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This regenerates the azure static sku list after https://github.com/kubernetes/autoscaler/pull/7126 removed some instance types. Particularly the `standardLSv2Family` which is still in use. Our cluster autoscaler is currently failing to scaleup in clusters where we use Standard_L8s_V2 for example

I just ran `gen.go` from westus2 and copied over the results

#### Does this PR introduce a user-facing change?

```release-note
Regenerate Azure static SKU list
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@comtalyst can you sanity check this? It's possible the previous PR ran against a non-public Azure cloud?

/lgtm

**Comment by comtalyst** [comment]
Running it on my side (public cloud) gives me something nearly the same. We would investigate #7126 later.

/lgtm
/approve

**Comment by rrangith** [comment]
@jackfrancis @comtalyst I created some backport PRs for 1.28-1.31
https://github.com/kubernetes/autoscaler/pull/7619
https://github.com/kubernetes/autoscaler/pull/7620
https://github.com/kubernetes/autoscaler/pull/7621
https://github.com/kubernetes/autoscaler/pull/7622

**Comment by jackfrancis** [comment]
@rrangith I don't want to doubt your manual git rebase hygiene! :) But generally it's more deterministic to let the k8s-cherry-pick-bot do this work for us. Let's see if these commands yield successful PR creation outcomes:

/cherry-pick cluster-autoscaler-release-1.31
/cherry-pick cluster-autoscaler-release-1.30
/cherry-pick cluster-autoscaler-release-1.29
/cherry-pick cluster-autoscaler-release-1.28

**Pull request merged**
