### PR TITLE
Added s390x support

### PR DESCRIPTION
**Pull request by Saripalli-lavanya**
#### What type of PR is this?

This PR adds docker file for s390x arch

#### What this PR does / why we need it:

This PR can help build s390x auto scalar image
#### Which issue(s) this PR fixes:

Fixes # NA

#### Does this PR introduce a user-facing change?

None

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
None

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @Saripalli-lavanya 
Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by Shubham82** [comment]
To check CLA,

/easycla

**Comment by Saripalli-lavanya** [comment]
Thank you @spzala, CLA Completed now

**Comment by Saripalli-lavanya** [comment]
Hi@Shubham82, Could you help me take this PR review ahead, CLA has been completed, logs from my local JFR.

```
saripallilavanya@Lavanyas-MacBook-Pro cluster-autoscaler % make container
rm -f cluster-autoscaler-s390x
docker build --network=default -t autoscaling-builder ../builder
[+] Building 11.9s (3/8)                                                                                           [+] Building 12.0s (3/8)                                                                                           [+] Building 100.2s (9/9) FINISHED                                                                                 
 => [internal] load build definition from Dockerfile                                                          0.0ss
 => => transferring dockerfile: 936B                                                                          0.0ss
 => [internal] load .dockerignore                                                                             0.0ss
 => => transferring context: 2B                                                                               0.0ss
 => [internal] load metadata for docker.io/library/golang:1.20.4                                              7.0ss
 => [1/5] FROM docker.io/library/golang:1.20.4@sha256:690e4135bf2a4571a572bfd5ddfa806b1cb9c3dea0446ebadaf32  67.6ss
 => => resolve docker.io/library/golang:1.20.4@sha256:690e4135bf2a4571a572bfd5ddfa806b1cb9c3dea0446ebadaf32b  0.0ss
 => => sha256:690e4135bf2a4571a572bfd5ddfa806b1cb9c3dea0446ebadaf32bc2ea09d4f9 2.36kB / 2.36kB                0.0ss
 => => sha256:3fccedea46315261e4b6205bcffe91ece1e2aea60c23aab0f033f35461849b42 1.58kB / 1.58kB                0.0s
 => => sha256:6a90a37099af57552e523ac8cd1fb470b85dd559c2f9e8453e62dc3bf9163a49 6.99kB / 6.99kB                0.0s
 => => sha256:bd73737482dd5575526c7207872963479808d979ab2741c321706b8553918474 55.05MB / 55.05MB             19.4s
 => => sha256:6710592d62aa1338ac1c1c363dedc255659f666cc41441c7e0f735c484db10ff 15.76MB / 15.76MB             15.6s
 => => sha256:75256935197ed1bb3b994a77c01efa00349b901014448a260fafd9c3719a741d 54.58MB / 54.58MB             41.6s
 => => sha256:948a624948bad16368a8875d007bc505810d290412e61357e0e44549e775dd3c 86.03MB / 86.03MB             58.9s
 => => extracting sha256:bd73737482dd5575526c7207872963479808d979ab2741c321706b8553918474                     3.4s
 => => sha256:147e02c24f40116f23669411aa9b2a6b2f964ddce0e045d3933cc4ad19337cb3 100.15MB / 100.15MB           62.8s
 => => extracting sha256:6710592d62aa1338ac1c1c363dedc255659f666cc41441c7e0f735c484db10ff                     0.7s
 => => sha256:cd56b3199c0c96901ea545187395ab9d886e75aeb4d953f018a21c5782dc9498 156B / 156B                   44.7s
 => => extracting sha256:75256935197ed1bb3b994a77c01efa00349b901014448a260fafd9c3719a741d                     3.7s
 => => extracting sha256:948a624948bad16368a8875d007bc505810d290412e61357e0e44549e775dd3c                     4.4s
 => => extracting sha256:147e02c24f40116f23669411aa9b2a6b2f964ddce0e045d3933cc4ad19337cb3                     3.8s
 => => extracting sha256:cd56b3199c0c96901ea545187395ab9d886e75aeb4d953f018a21c5782dc9498                     0.0s
 => [2/5] RUN apt-get update && apt-get --yes install libseccomp-dev                                          6.0s
 => [3/5] RUN go version                                                                                      0.5s 
 => [4/5] RUN go get github.com/tools/godep                                                                  18.2s 
 => [5/5] RUN godep version                                                                                   0.4s 
 => exporting to image                                                                                        0.4s 
 => => exporting layers                                                                                       0.4s 
 => => writing image sha256:c4cdcd088b9deab3ffff18773449d422c5087e03d86925d1dd9777c0a3f3e061                  0.0s 
 => => naming to docker.io/library/autoscaling-builder                                                        0.0s
docker run  -v `pwd`:/gopath/src/k8s.io/autoscaler/cluster-autoscaler/:Z autoscaling-builder:latest \
                bash -c 'cd /gopath/src/k8s.io/autoscaler/cluster-autoscaler && BUILD_TAGS= LDFLAGS="-s" make build-arch-s390x'
rm -f cluster-autoscaler-s390x
CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build -o cluster-autoscaler-s390x --ldflags "-s" 
docker build --pull \
                -t staging-k8s.gcr.io/cluster-autoscaler-s390x:dev \
                -f Dockerfile.s390x .
[+] Building 5.7s (7/7) FINISHED                                                                                                     
 => [internal] load build definition from Dockerfile.s390x                                                                      0.0s
 => => transferring dockerfile: 38B                                                                                             0.0s
 => [internal] load .dockerignore                                                                                               0.0s
 => => transferring context: 2B                                                                                                 0.0s
 => [internal] load metadata for gcr.io/distroless/static:nonroot-s390x                                                         2.9s
 => [internal] load build context                                                                                               1.6s
 => => transferring context: 164.07MB                                                                                           1.6s
 => CACHED [1/3] FROM gcr.io/distroless/static:nonroot-s390x@sha256:c0e2f22015a1f262d73a340cb5bc58637b8cc9416c20b5be6a2bdc9e90  0.0s
 => [2/3] COPY cluster-autoscaler-s390x /cluster-autoscaler                                                                     0.5s
 => exporting to image                                                                                                          0.6s
 => => exporting layers                                                                                                         0.6s
 => => writing image sha256:05952014a6f4ad3cc8e58a31bb5747412dce6e5c5ce949fe4545218fac2d45a4                                    0.0s
 => => naming to staging-k8s.gcr.io/cluster-autoscaler-s390x:dev                                                                0.0s
Image dev-s390x completed
Full in-docker image dev-s390x completed
saripallilavanya@Lavanyas-MacBook-Pro cluster-autoscaler % docker image ls
REPOSITORY                                                  TAG                                              IMAGE ID       CREATED          SIZE
staging-k8s.gcr.io/cluster-autoscaler-s390x                 dev                                              05952014a6f4   2 minutes ago    166MB
autoscaling-builder                                         latest                                           c4cdcd088b9d   8 minutes ago    887MB
<none>                                                      <none>                                           2bcce1512624   11 minutes ago   167MB
```

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
