### PR TITLE
Add support for Azure virtual machine availability sets (VMAS)

### PR DESCRIPTION
**Pull request by feiskyer**
Continue of #449.

This PR adds initial support for Azure virtual machine availability sets (VMAS). Significant changes include

- Add `vmType` parameters to indicate different virtual machine types. Candidate values are 'vmss' and 'standard'
- Add agent pools implementation (standard vmType) of NodeGroup
- Add more options for scaling agent pools
- Add more fake clients and unit tests

Special notes for reviewers:

- Only one node group supported yet
- Some functions (in azure_util.go) are copied from acs-engine. They are not ventured because of various vendor problems, e.g. i18n and go template. acs-engine should be adjusted before vendoring those functions
- Azure API calls may hit requests count limits which need to be addressed in further PRs 

/cc @brendandburns @andyzhangx @jdumars

/assign @mwielgus @MaciekPytel

### CODE REVIEW

**Comment by feiskyer** [comment]
Update: Verified one node group scaling properly in following scenarios

- Cluster deployed via acs-engine without windows containers (standard vmType)
- Cluster deployed via acs-engine with windows containers (standard vmType)
- Cluster manually deployed on Azure VMSS (vmss vmType)

Also /cc @wbuchwalter (author of Kubernetes-acs-engine-autoscaler). Could you also take a look at this?

**Comment by mwielgus** [comment]
Is the Azure library also updated in the core Kuberentes?

**Comment by mwielgus** [comment]
Please fix the conflicts.

**Comment by feiskyer** [comment]
> Is the Azure library also updated in the core Kuberentes?

@mwielgus Azure library version not updated in this PR, only adding a new sub-package.

**Comment by feiskyer** [comment]
> Please fix the conflicts.

Rebased and conflicts resolved.

**Comment by feiskyer** [comment]
@mwielgus thanks

**Pull request merged**
