### PR TITLE
Remove vendor directory

### PR DESCRIPTION
**Pull request by fmuyassarov**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Drop the following vendor directories
```terminal
./addon-resizer/vendor
./vertical-pod-autoscaler/vendor
./vertical-pod-autoscaler/e2e/vendor
./cluster-autoscaler/vendor
```

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/autoscaler/issues/4878

#### Does this PR introduce a user-facing change?
NONE
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Ops, seems I missed my second commit.
/hold

**Comment by x13n** [comment]
This PR is humongous, can you scope it down just to Cluster Autoscaler?

**Comment by fmuyassarov** [comment]
> This PR is humongous, can you scope it down just to Cluster Autoscaler?

Yes I will do so. There is a second commit I had and I was not able to push it yet because I haven't fixed all the failing tests locally. Perhaps it would simply it for both me and reviewers.

**Comment by x13n** [comment]
Thanks! Btw, removing vendor is just a part of the task here - we also need to step referencing it e.g. in Makefile:

https://github.com/kubernetes/autoscaler/blob/c2b969d1c8ce0dd973d2c539b530ab619dedccd3/cluster-autoscaler/Makefile#L88-L89

**Comment by fmuyassarov** [comment]
> Thanks! Btw, removing vendor is just a part of the task here - we also need to step referencing it e.g. in Makefile:
> 
> https://github.com/kubernetes/autoscaler/blob/c2b969d1c8ce0dd973d2c539b530ab619dedccd3/cluster-autoscaler/Makefile#L88-L89

yes, that I did as part of second commit.

**Comment by x13n** [comment]
Hey @fmuyassarov , are you still working on this one?

**Comment by fmuyassarov** [comment]
> Hey @fmuyassarov , are you still working on this one?

Hi @x13n . Sorry for the radio silence here. I was busy with some other proprieties. I will have time during the week to rebase and update the PR according to the comments above.

**Comment by x13n** [comment]
Can we have a warning first? See discussion on https://github.com/kubernetes/autoscaler/issues/4878

**Comment by x13n** [comment]
Looks like this is no longer being worked on, so closing. Feel free to reopen if you have a chance to get back to this.

/close

**Pull request closed without merging**
