### PR TITLE
Cherry pick of #1071: Upgrade AKS API to 2018-03-31

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #1071: Upgrade AKS API to 2018-03-31 to CA release-1.2.

### CODE REVIEW

**Comment by feiskyer** [comment]
ping @aleksandra-malinowska @MaciekPytel

**Comment by MaciekPytel** [comment]
Why are kubernetes packages going from v1.10.1-beta.0-52 to v1.10.1-beta.0-51? There is no change in vendor, but it looks like Godeps.json is moving to an older kubernetes commit. Or is it some strange artifact of all horrible godeps hacking we do? I thought that would be limited to commit id.

**Comment by feiskyer** [comment]
Hmm, there's something wrong in kubernetes.sync. The commit ID in it is not same with Godeps version.

Let ms update kubernetes.sync instead.

**Comment by aleksandra-malinowska** [comment]
> Update: The commit ID 59e4f79d25adca76ff42542e745f49f950351e93 couldn't be found in k/k repo. So we should use the commit in kubernetes.sync instead.

This is WAI. Commit ID in Godeps.json is from the commit made when running fix_gopath.sh. kubernetes.sync should contain the actual k/k commit to which Godeps were synced.

> v1.10.1-beta.0-52 to v1.10.1-beta.0-51

Looks like fix_gopath.sh may have been run with old version of kubernetes checked out. @feiskyer, can you use the newest commit from 1.10 branch?

**Comment by feiskyer** [comment]
@aleksandra-malinowska Upgraded to latest commit of release-1.10 branch. PTAL

**Comment by feiskyer** [comment]
ping @MaciekPytel @aleksandra-malinowska

**Comment by feiskyer** [comment]
@aleksandra-malinowska Thanks you

**Pull request merged**
