### PR TITLE
cleanup clusterapi imports

### PR DESCRIPTION
**Pull request by elmiko**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

this change fixes the import order so that the goimports tool does not complain about the ordering.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks @elmiko
/lgtm

**Comment by Shubham82** [comment]
@elmiko, IMO we can cherry-pick this issue in the supported CA release.
If it seems good then I will open a PR for it
WDYT?

**Comment by elmiko** [comment]
that would be great, thanks @Shubham82 !

**Comment by Shubham82** [comment]
> that would be great, thanks @Shubham82 !

thanks, @elmiko for the confirmation. I will raise PRs for it soon.

**Comment by Shubham82** [comment]
I have raised the following PRs:
For CA 1.30 #7445
For CA 1.31 #7446

**Pull request merged**
