### PR TITLE
[Azure] Update vendor/module versions for 1.31

### PR DESCRIPTION
**Pull request by rakechill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Updates skewer module version (Azure-specific) 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Essentially the same as the [PR for 1.30](https://github.com/kubernetes/autoscaler/pull/7288), except the vendor directory was removed in 1.31, so no changes are necessary there.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rakechill** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/87990209/7289/#/?version=2)
> 
> * ✅ login: k8s-ci-robot / name: Kubernetes Prow Robot  ([8bda275](https://github.com/kubernetes/autoscaler/commit/8bda275bd3eb983b77ed002038464b2afd4bb7c1), [648cf5f](https://github.com/kubernetes/autoscaler/commit/648cf5ff7102652213a740aaf3a97bfd999932d1))
> * ✅ login: rakechill / name: Rachel Gregory  ([f0b0a76](https://github.com/kubernetes/autoscaler/commit/f0b0a76aa44488e1c977c2fb113dadd2e94edcee))
> * ✅ login: nojnhuh / name: Jon Huhn  ([3d9a36d](https://github.com/kubernetes/autoscaler/commit/3d9a36d8c99e8920f68f567cde704fcd2df2194d))
> * ✅ login: MaciekPytel  ([a178281](https://github.com/kubernetes/autoscaler/commit/a17828188989ad62d8c9e0b3e0d61938882090fc))
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/87990209/7289/#/?version=2) - login: @k8s-infra-cherrypick-robot . The commit ([2180607](https://github.com/kubernetes/autoscaler/commit/21806079ef4ba06d2560063b3f4b7734516f5591), [e5ebbf6](https://github.com/kubernetes/autoscaler/commit/e5ebbf61107a8cb208855f624c8b8ba4769fa661)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/87990209/7289/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

forgot to update the base branch 🥲

**Review by feiskyer — APPROVED** [review]
lgtm

**Pull request merged**
