### PR TITLE
Change log level of boot dist type and size defaulting in gce_price

### PR DESCRIPTION
**Pull request by damikag**
Change log level  and type of boot dist type and size defaulting in gce_price

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR updates log level  and type of boot dist type and size defaulting in gce_price
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pmendelski — APPROVED** [review]

**Comment by Shubham82** [comment]
Thanks @damikag
/lgtm

**Comment by Shubham82** [comment]
cc @x13n
PTAL!

**Pull request merged**
