### PR TITLE
feat(ovhcloud): add node group autoscaling options

### PR DESCRIPTION
**Pull request by Kafei59**
Adding the new Autoscaling Opts per node group configuration to OVHcloud provider

### CODE REVIEW

**Comment by Kafei59** [comment]
CI failed:
```
1.14: Pulling from library/golang

docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
