### PR TITLE
Cherry pick to backport support for AWS EC2 Launch Templates onto 1.3 release branch to support Launch Templates with Kubernetes 1.11

### PR DESCRIPTION
**Pull request by devkid**
This feature is included in cluster-autoscaler starting from 1.12.

### CODE REVIEW

**Comment by devkid** [comment]
As discussed in #1591.

@sethpollack, @Jeffwan

**Comment by aleksandra-malinowska** [comment]
Cherry-picking godeps update effectively replaces all dependencies from Kubernetes 1.11 with those from Kubernetes 1.12. Since Cluster Autoscaler 1.3 is intended to work with Kubernetes 1.11, this won't do. 

If this change requires newer AWS SDK, first confirm that this is in kubernetes/kubernetes dependencies on `release-1.11` branch. If it is, [update godeps using this branch](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-update-ca-dependencies-particularly-k8siokubernetes).

If it isn't, the alternatives are:
1) cherry-pick newer version to kubernetes/kubernetes `release-1.11` first, or
2) put newer version of SDK in Cluster Autoscaler's `/override` directory and update `fix_gopath.sh` to pick it up,
then update godeps as described above.

**Comment by devkid** [comment]
I did not cherry pick the Godeps dependendices, I just updated the aws sdk dependencies using `godep update github.com/aws/aws-sdk-go/...` because the old aws sdk did not know about LaunchTemplates.

Thanks for pointing that out. I will probably go with option 2 next week.

**Comment by devkid** [comment]
I started looking into this and encountered the following problems:
* when I add the whole `aws-sdk-go` package under `cluster-autoscaler/_override`, I increase the size of the whole repo by roughly 90 MiB; this seems undesirable, considering that the whole repo is only roughly 110 MiB and the other folders in `_override` are significantly smaller
* when I only add the `aws-sdk-go/service/ec2` folder, it doesn't compile because there were probably changes in that package that require a complete new `aws-sdk-go` package

Am I missing something here? Or is there no other way than to get the newer aws-sdk-go version into `k8s.io/kubernetes` first?

**Comment by aleksandra-malinowska** [comment]
> Am I missing something here? Or is there no other way than to get the newer aws-sdk-go version into k8s.io/kubernetes first?

Not really. Dependency management is definitely a sad part of this project, sorry about this :( TL;DR is that we require scheduler code, which means vendoring all of core Kubernetes, which keeps biting us in strange ways on ~every godeps update.

**Comment by mwielgus** [comment]
PR not active. Dependencies https://github.com/kubernetes/kubernetes/pull/73349 are also stuck. 

Closing. Please reopen once it will be possible to merge it.

**Comment by Jeffwan** [comment]
I will leave on eye once Micah from my team get SDK support in kubernetes upstream. Then we can easily cherry pick this change,

**Pull request closed without merging**
