### PR TITLE
[charts/cluster-autoscaler] Revert "update RBAC to only use verbs that exist for the resources"

### PR DESCRIPTION
**Pull request by MaxRink**
Reverts kubernetes/autoscaler#5927
See https://github.com/kubernetes/autoscaler/pull/5927#issuecomment-1695754325 for more details

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by Shubham82** [comment]
@MaxRink  PR  didn't merge due to a failed test case i.e. `Lint and Test Charts / Helm chart (pull_request)` which is required to pass to merge the PR.
so please address this failed test case.

**Comment by Shubham82** [comment]
On checking the failed test case the error is: `cluster-autoscaler => (version: "9.29.2", path: "charts/cluster-autoscaler") > Chart version not ok. Needs a version bump!`

You need to bump the chart version.

**Comment by gjtempleton** [comment]
Lets close this for now, we've had releases since the original change was merged in. I'm going to create a PR adding a changelog and associated PR time linting checks to ensure we update it going forward.

**Pull request closed without merging**
