### PR TITLE
Cluster Autoscaler 1.16.5

### PR DESCRIPTION
**Pull request by maximerenou50**
Update Cluster Autoscaler version to 1.16.5

### CODE REVIEW

**Comment by maximerenou50** [comment]
Hello,

Any news on that? Please let me know if I missed something to get a new release, I'm particularly interested in getting [that MR](https://github.com/kubernetes/autoscaler/pull/2851) into an official release.

Thank you

**Comment by piteur** [comment]
🙏 Waiting for that release too, as I'm facing this issue on production right now.
Thanks for your time on that @maximerenou50, perfect timing for us!

Cf: https://github.com/kubernetes/autoscaler/pull/2851#issuecomment-590392140

**Comment by MaciekPytel** [comment]
Similarly to Kubernetes we don't really have any process for triggering a new release. Building a release is a mostly manual process and we release roughly every 2 months or so. The version bump PR is generally done by a person doing the release as part of release process. 

Right now we're focusing on getting 1.18 CA in time for Kubernetes release. Changes to scheduler in 1.18 require huge changes to CA and we're racing to implement those in time. 
Given the above, the likely timeline for next round of patch releases is around the time of 1.18 release (late March) or as soon as we've managed to build 1.18.0 CA.

**Comment by maximerenou50** [comment]
Hi @MaciekPytel,
Thanks for your feedback. I haven't realized that releases were a manual process (that's unfortunate).
In that case, I don't really have a choice than to wait for a new release of 1.16 to occurs. I will close that PR then and keep an eye on the release.
Cheers

**Comment by 2ZZ** [comment]
Hi @MaciekPytel, has there been any movement on a 1.16 release now that 1.18 is out? :)
We could really do with this fix.

**Comment by MaciekPytel** [comment]
cc: @towca - I believe you were planning to prepare patch releases soon? Do you have any particular date in mind?

**Comment by towca** [comment]
I want to do it on Monday: #2988.

**Pull request closed without merging**
