### PR TITLE
Regenerate ProvisioningRequest CRD for  v1

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
#### What type of PR is this?

/kind bug
/kind api-change

#### What this PR does / why we need it:

In #7195 ProvisioningRequest API was bumped to v1, but CRD wasn't upgraded. CA 1.31 won't work without upgraded CRD.

#### Does this PR introduce a user-facing change?

```release-note
Adds CRD for ProvisioningRequest v1
```

/cc @MaciekPytel @mwielgus

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
For future reference: the same go module workarounds as in #7195 were necessary, I just didn't keep the commits this time since this is already explained in the previous PR.

**Review by mwielgus — APPROVED** [review]
/lgtm

**Pull request merged**
