### PR TITLE
[cluster-autoscaler-1.24] Update cloudprovider/aws/aws-sdk-go to 1.48.7

### PR DESCRIPTION
**Pull request by ROunofF**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Update golang to 1.19 since CI for 1.17 was broken
Update cloudprovider/aws/aws-sdk-go to 1.48.7 so we support dynamic auth token
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by ROunofF** [comment]
@mwielgus The failure doesn't look related to my change. Any idea what needs to be done? 

/retest

**Comment by gjtempleton** [comment]
https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.24/.github/workflows/ci.yaml#L17 Think you'll need to update this as well if we want this to be in a mergable state. Not sure what knock-on impacts that may have and whether it's worth doing the work given we won't be cutting another 1.24 release as it's fallen out of community support.

**Comment by ROunofF** [comment]
@gjtempleton Didn't realize the ci.yal had the go version in it. It was minimal effort... and my initial testing was done with 1.19 anyway since that's the version in the builder/Dockerfile for this branch.

/lgtm

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
