### PR TITLE
Godeps update to pull in klog

### PR DESCRIPTION
**Pull request by bskiba**
Prerequisite for #1626 

@Rajat-0

### CODE REVIEW

**Comment by bskiba** [comment]
@kgolab

**Comment by Rajat-0** [comment]
@bskiba thanks for updating deps.

**Comment by kgolab** [comment]
I was a little worried about removed files, in particular testapi but it got removed via #1353 , this also removed dependency on apis/imagepolicy.
I'm not sure why parts of apis/admission are gone but they seem unused so LGTM.

**Pull request merged**
