### PR TITLE
add containerd runtime and init for autoscaler

### PR DESCRIPTION
**Pull request by chernienkoii**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add  manager containerd, cloud-init, setting CA for differend pool and nodeSelector for deploymeynt
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @chernienkoii 
Please sign the CLA before the PR can be reviewed.
See the following document to sign the CLA: [Signing Contributor License Agreements(CLA)](https://github.com/kubernetes/autoscaler/blob/master/CONTRIBUTING.md#signing-contributor-license-agreementscla)

**Comment by chernienkoii** [comment]
Hi @Shubham82 done it!

**Comment by Shubham82** [comment]
cc @apricote
PTAL!

**Comment by kundan2707** [comment]
/retitle add containerd init adn init for autoscaler

**Review by apricote — CHANGES_REQUESTED** [review]
I do agree that the current example is very outdated and needs a refreshment, but I am not sure if we want to have another "install kubeadm" script laying around here. I would prefer to link to the upstream docs ["Creating a cluster with kubeadm"](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/) for this and only talk about the cluster-autoscaler configuration here.

**Comment by x13n** [comment]
Is this still being worked on? Closing for now, please reopen if still relevant.

/close

**Pull request closed without merging**
