### PR TITLE
Issue#4340 -- Update klog to v2 for e2e --part4

### PR DESCRIPTION
**Pull request by mallow111**
Issue: #4340
This PR is to upgrade klog to v2 in vertical-pod-autoscaler/e2e and this is the last part for upgrade, there are a lot of vendor files make the big size bigger.

### CODE REVIEW

**Review by jbartosik — COMMENTED** [review]
This is pretty big change - is it necessary to update vendor here?

**Comment by mallow111** [comment]
@jbartosik  I did 

```
go mod tidy
```
it updated the vendor automatically, also the test-to-verfiy failed, is there any other cmd that I should try in local?

**Comment by mallow111** [comment]
@jbartosik  please advise if there is any other cmd that I should run

**Comment by mallow111** [comment]
will close this one, it is a duplicate of https://github.com/kubernetes/autoscaler/pull/4536

**Pull request closed without merging**
