### PR TITLE
Backport Mutiarch addon-resizer image

### PR DESCRIPTION
**Pull request by basheer12**
Fixes: https://github.com/kubernetes/autoscaler/issues/2870

### CODE REVIEW

**Comment by bskiba** [comment]
Can you modify the commit so that it contains github user info?

**Comment by basheer12** [comment]
@bskiba sorry for the late reply, I have signed the CLA and added github user info to the commit message..

**Comment by bskiba** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
