### PR TITLE
cluster-autoscaler: fix some typos in the code

### PR DESCRIPTION
**Pull request by hectorj2f**
I found some typos while surfing across the code to understand what it does each component.

### CODE REVIEW

**Comment by Jeffwan** [comment]
I am wondering why they are not detected by spelling check scripts. Should we have a follow up task to improve vocabulary?

**Comment by hectorj2f** [comment]
@Jeffwan i don't mind having a follow up PR with changes to check these lint details

**Comment by Jeffwan** [comment]
/lgtm 

Seems people on cc list doesn't have permission to approve it.  
@losipiuk @krzysztof-jastrzebski

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
