### PR TITLE
ec2_instance_types CA cherry picks to 1.2

### PR DESCRIPTION
**Pull request by jeruane**

### CODE REVIEW

**Comment by losipiuk** [comment]
There is Travis failure. Can you look at it?

**Comment by jeruane** [comment]
looks to be related to:
https://github.com/kubernetes/autoscaler/issues/608
looks like this test is disabled on master:
https://github.com/kubernetes/autoscaler/blob/991873c2375575ef7cd5cdb6ac6009a41122e92e/cluster-autoscaler/cloudprovider/aws/aws_manager_test.go#L306

I can cherry-pick the commit to disable that test into this branch if you'd like:
https://github.com/kubernetes/autoscaler/commit/e93e25dc718f7f932b23eff381982eac15b978ac

**Comment by losipiuk** [comment]
I guess /retest does not work here.

@jeruane Thanks for checking.
It would be great if you added cherry-picking the e93e25d as part of this PR.

**Pull request merged**
