### PR TITLE
Fixes issue #4453 Removes Deprecated CAPI Annotations

### PR DESCRIPTION
**Pull request by clintonyeb**
This PR resolves the issue #4453.

It removes deprecated CAPI annotations.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
thanks @clintonyeb , this generally looks good to me. i'd like to get another review from someone in the cluster-api community.
/approve

**Comment by randomvariable** [comment]
This looks ok to me.
/lgtm

**Comment by clintonyeb** [comment]
fixes issue #4453

**Comment by clintonyeb** [comment]
Thanks everyone (@elmiko , @randomvariable ) for the quick look. I was expecting the associated issue to be closed automatically but it is still open.

**Comment by elmiko** [comment]
i closed the issue manually, thanks for the heads up =)

**Pull request merged**
