### PR TITLE
Correct apiVersion in dynamic provisionning 1.11

### PR DESCRIPTION
**Pull request by maximerihouey**
scheduling.k8s.io/v1beta -> scheduling.k8s.io/v1beta1

### CODE REVIEW

**Comment by MaciekPytel** [comment]
Unfortunately we cannot accept any PR unless you sign CLA. 

I'll merge this as soon as you do. Also: thanks for spotting this!

**Comment by maximerihouey** [comment]
I signed it

**Comment by maximerihouey** [comment]
Thank you @MaciekPytel for the explanation.

**Pull request merged**
