### PR TITLE
Cherry-pick: Fix error on node info not found for group

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by losipiuk** [comment]
Fixes observed panic (but not the root cause) for https://github.com/kubernetes/autoscaler/issues/1270

**Comment by aleksandra-malinowska** [comment]
IIRC we've recently been refactoring NewAutoscalerError to ToAutoscalerError in order to avoid re-packaging of errors. Are we sure we want to go back here?

**Comment by aleksandra-malinowska** [comment]
Can we cherry-pick #1076 instead?

**Comment by aleksandra-malinowska** [comment]
It would prevent the panic, but error message would be less useful. Sorry, I misread the original issue.

**Pull request merged**
