### PR TITLE
Allow simulator to persist changes in cluster snapshot

### PR DESCRIPTION
**Pull request by x13n**
#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

/kind cleanup
/kind feature

#### What this PR does / why we need it:

One more refactor of existing scale down code in order to make parallel scale down (https://github.com/kubernetes/autoscaler/issues/5079) possible.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This is a follow-up to https://github.com/kubernetes/autoscaler/pull/5118. Only last 2 commits should be reviewed as a part of this PR. It will be on hold until the previous one is merged.

/hold

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @MaciekPytel 
/assign @yaroslava-serdiuk

### CODE REVIEW

**Comment by x13n** [comment]
FWIW, looks like tests are failing due to https://github.com/kubernetes/autoscaler/issues/5134

**Comment by MaciekPytel** [comment]
/lgtm
/approve
Happy to see resource limits moved away to a separate file, I really hated how they were mixed up with scale-down code before.

**Pull request merged**
