### PR TITLE
Support azure vmss flex

### LINKED ISSUE #6454: cloud provider clusterapi with cloud-provider-azure AzureMachinePools using orchestrationMode=Flexible does not scale down
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.28.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.4
Server Version: v1.28.4
</pre></details>

Also using CAPZ version: 1.10.8

**What environment is this in?**:

* The CAPI/CAPZ Management cluster is running on Azure AKS.
* The workload cluster is running in Azure.
* The cluster-autoscaler is running on the Management cluster

**What did you expect to happen?**:

When cluster-autoscaler taints nodes for deletion it will delete them and scale down the `MachinePool`.

**What happened instead?**:

cluster-autoscaler can't find the Machines 

**How to reproduce it (as minimally and precisely as possible)**:

Assuming you have a running CAPZ cluster:

1. Create an AzureMachinePool with `spec.orchestrationMode` set to `Flexible`
2. Scale out a deployment that triggers cluster-autoscaler to increase the replica count of the MachinePool
3. CAPZ will create one `AzureMachinePoolMachine` resource per required node
4. Scale in a deployment that trigger cluster-autoscaler to initiate the scale-down process
5. cluster-autoscaler fails scale-down due not finding `Machine` resources

Step 5 fails due to VMSS Flex replicas are created as `AzureMachinePoolMachine` and not `Machine`.

**Anything else we need to know?**:

This commit adds the required resources, indexers and conditions in handlers to correctly remove unneeded `AzureMachinePoolMachines`: https://github.com/LiveArena/kubernetes-autoscaler/commit/b819ed9bf27722146805425ab82ea5f860c990b3

### PR DESCRIPTION
**Pull request by Daniel-Redeploy**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds support for Azure VMSS Flexible MachinePool deployments.

#### Which issue(s) this PR fixes:

Fixes #6454

#### Special notes for your reviewer:

Removes normalization of all azure resources, rather than just for Azure VMSS resources. The reason for this is that VMSS Flexible provisions VM's (`Microsoft.Compute/virtualMachines`) rather than instances as a sub-resource of the VMSS (`Microsoft.Compute/virtualMachineScaleSets`).

Should supersede #6632

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by elmiko** [comment]
i would like some time to study this as we prefer not to encode provider specific information in the clusterapi provider. this information should be discoverable through the generic mechanisms of clusterapi.

also, i would like @jackfrancis to review this as well.

please do not merge this until we have had time to review
/hold

**Comment by jackfrancis** [comment]
/assign @manishsat 

@Daniel-Redeploy what is additive in this PR on top of the original PR that introduced VMSS Flex for the Azure provider? Ref:

- https://github.com/kubernetes/autoscaler/pull/5602

cc @gandhipr

**Comment by jackfrancis** [comment]
O.K. I read through this PR changeset a bit more and it seems like the best way to describe this is "enable first class MachinePoolMachine support in clusterapi provider". Is that about right? If so, I would hope we can enable this in such a way where we don't have to reference `Azure`MachinePoolMachines (or any other provider-specific implementation) in the clusterapi provider code. Is there something that prevents such a clean separation of concerns?

**Comment by Daniel-Redeploy** [comment]
> /assign @manishsat
> 
> @Daniel-Redeploy what is additive in this PR on top of the original PR that introduced VMSS Flex for the Azure provider? Ref:
> 
> * [Adding VMSS Flex support in Azure AutoScaler #5602](https://github.com/kubernetes/autoscaler/pull/5602)
> 
> cc @gandhipr

Somehow I totally missed the VMSS Flex docs, feature and how to toggle it when I worked on this last November. I remember I found references to Flex but couldn't get the cluster autoscaler to remove instances without the code changed in this PR. In short CA found the VMSS, scaled out the instance count, but couldn't scale in since it couldn't find the individual instance.

I haven't tested if the `AZURE_ENABLE_VMSS_FLEX` env will work as expected for our scenario with mixed deployments models (MachineDeployment + VMSS Uniform + VMSS Flex). But if it does this PR should be seen as redundant.

**Comment by Daniel-Redeploy** [comment]
> O.K. I read through this PR changeset a bit more and it seems like the best way to describe this is "enable first class MachinePoolMachine support in clusterapi provider". Is that about right? If so, I would hope we can enable this in such a way where we don't have to reference `Azure`MachinePoolMachines (or any other provider-specific implementation) in the clusterapi provider code. Is there something that prevents such a clean separation of concerns?

Makes perfect sense to me and it would make the clusterapi provider flexible against more MachinePool providers than Azure. 👍

**Comment by x13n** [comment]
/assign @elmiko @jackfrancis 

Assigning - since I understand you're reviewing this one?

**Comment by jackfrancis** [comment]
@Daniel-Redeploy have you had a chance to determine if we still need to preserve anything from this PR?

**Comment by jackfrancis** [comment]
/close

@elmiko agree

@Daniel-Redeploy feel free to reopen if I'm premature here!

**Pull request closed without merging**
