### PR TITLE
VPA v1beta2 tests use v1beta2 client

### PR DESCRIPTION
**Pull request by bskiba**

### CODE REVIEW

**Comment by bskiba** [comment]
fixes #3378

**Comment by krzysied** [comment]
What about https://github.com/kubernetes/autoscaler/blob/51b767f43c24a51b89b5646574f03af47abc0643/vertical-pod-autoscaler/e2e/v1beta2/common.go#L388? It also has V1. Shouldn't it be changed?

**Comment by bskiba** [comment]
Yeah you're right. Fixed.

**Pull request merged**
