### PR TITLE
Adjustment in rbac

### PR DESCRIPTION
**Pull request by heraque**
Adjustment in rbac, errors in the cluster referring to the lack of permission in the storage tab.

### CODE REVIEW

**Comment by kevin-lindsay-1** [comment]
Testing these changes manually by editing the `clusterrole`, this PR gets rid of the errors seen in #4224.

**Comment by gjtempleton** [comment]
Thanks for the PR, can you please add these permissions to the other examples we have in the same directory?

**Comment by heraque** [comment]
> Obrigado pelo PR, você pode adicionar essas permissões aos outros exemplos que temos no mesmo diretório?

**Comment by heraque** [comment]
> > Obrigado pelo PR, você pode adicionar essas permissões aos outros exemplos que temos no mesmo diretório?

**Comment by gjtempleton** [comment]
Thanks for that, just one more request, could you please squash the commits down to a single commit?

**Review by Jeffwan — APPROVED** [review]

**Comment by gjtempleton** [comment]
/assign @gjtempleton 

Hi @heraque, have you got the time to squash these changes down to a single commit?

**Comment by gjtempleton** [comment]
Closing as #4246 has been merged, resolving this.
/close

**Pull request closed without merging**
