### PR TITLE
[cluster-autoscaler] Backport fixes for packet provider to release-1.17

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by MaciekPytel** [comment]
The tests have failed with what seems like an unrelated error in [Cluster API tests](https://travis-ci.org/github/kubernetes/autoscaler/jobs/740281910). At a glance it seems to be the same issue as https://github.com/kubernetes/autoscaler/pull/3597. @elmiko Can you take a look and possibly open cherry-pick PRs as you suggested in https://github.com/kubernetes/autoscaler/pull/3597#issuecomment-708635079?

I'm going to re-open to try and trigger a travis rerun.

**Comment by elmiko** [comment]
> @elmiko Can you take a look and possibly open cherry-pick PRs as you suggested in [#3597 (comment)](https://github.com/kubernetes/autoscaler/pull/3597#issuecomment-708635079)?

sure thing, i should be able to take a look today

**Comment by MaciekPytel** [comment]
Looks like the same test has failed again. I've already included cherry-picks of this in 1.19 and 1.18 patch releases, ideally it should also go into 1.17. I'd appreciate help fixing this, I'm happy to delay 1.17 release by a day or two if needed.

**Comment by elmiko** [comment]
@MaciekPytel i creaated this pr, https://github.com/kubernetes/autoscaler/pull/3662

looks like it shoud fix the issue
```
$ stress ./clusterapi.test -test.run='TestControllerNodeGroups$' -test.cpu=8
106 runs so far, 0 failures
226 runs so far, 0 failures
324 runs so far, 0 failures
```

**Comment by MaciekPytel** [comment]
Thanks for fixing it so quickly @elmiko.
I'm logging off now, I'll merge this PR tomorrow after #3662 is merged.

**Pull request merged**
