### PR TITLE
Update VPA dependency github.com/emicklei/go-restful/v3

### PR DESCRIPTION
**Pull request by jbartosik**
/kind cleanup

To pull in a fix for vulnerability in the dependency

#5455

### CODE REVIEW

**Comment by jbartosik** [comment]
Test error looks like an unrelated problem in CA ([test run](https://github.com/kubernetes/autoscaler/actions/runs/4113057742/jobs/7098723311)):

```
 # k8s.io/autoscaler/cluster-autoscaler/processors/nodeinfosprovider
Error: processors/nodeinfosprovider/asg_tag_resource_node_info_provider.go:38:67: not enough arguments in call to NewMixedTemplateNodeInfoProvider
	have (*time.Duration)
	want (*time.Duration, bool)
FAIL	k8s.io/autoscaler/cluster-autoscaler [build failed]
```

**Comment by jbartosik** [comment]
@mwielgus PTAL

**Comment by jbartosik** [comment]
@mwielgus PTAL

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
