### PR TITLE
Fix label indentation for the service monitor manifest

### PR DESCRIPTION
**Pull request by rdezavalia**
#### Which component this PR applies to?

cluster-autoscaler helm chart

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR fixes the service monitor manifest in the chat. Labels have wrong indentation that breaks the yaml file

#### Special notes for your reviewer:
NONE

### CODE REVIEW

**Comment by gjtempleton** [comment]
/assign @gjtempleton 
Hi, thanks for the PR.

Can I ask what error you're seeing with the current setup and with what version of components?

From my quick tests, this seems to work as expected, though we should still merge this anyway.

To get this merged you're going to need to also give the version in the chart.yml a bump.

**Comment by gjtempleton** [comment]
Hi @rdezavalia 

Have you had a chance to look at my previous questions/feedback?

**Comment by rdezavalia** [comment]
Hi @gjtempleton The error I was seeing was a wrong indentation with yamllint

` yamllint output/cluster-autoscaler/templates/servicemonitor.yaml
output/cluster-autoscaler/templates/servicemonitor.yaml
  9:7       error    wrong indentation: expected 4 but found 6  (indentation)
`

**Comment by gjtempleton** [comment]
Thanks
/lgtm
/approve

**Comment by gjtempleton** [comment]
Huh, I'll need to have a look into why the Prow bot didn't pick up that this needed a rebase as a 9.16.2 had already been published, so this failed: https://github.com/kubernetes/autoscaler/runs/5886230289?check_suite_focus=true

@rdezavalia  Could you please raise a follow-up PR to bump to 9.16.3?

**Pull request merged**
