### PR TITLE
Fix azure autodiscovery when max tags aren't specified

### LINKED ISSUE #2713: Autodiscovery with no max specified fails on Azure
Parsing the labels fails early if no maximum is specified. This would cause the autoscaler to be in a crashed loop state.

When the azure manager is created, we attempt to parse the labels from the auto discovery tags:
https://github.com/kubernetes/autoscaler/blob/d4dd4298a614623386aa4e961222683e4fd38c1e/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L245

Those labels don't contain the max/min labels because the expectation is that autoscaler will obtain those from vmss tags instead, so the logic fails here:

https://github.com/kubernetes/autoscaler/blob/d4dd4298a614623386aa4e961222683e4fd38c1e/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L569-L571

The parsing logic shouldn't attempt to parse the min/max values from the autodiscovery tags and just wait for the first refresh to populate those.

### PR DESCRIPTION
**Pull request by marwanad**
Closes #2713 

/area provider/azure

### CODE REVIEW

**Comment by nilo19** [comment]
I think the issue will be solved by setting the default `MaxSize` 1 instead of -1, and output a log if max/min label is missing. In this case, only when the user sets the wrong max/min label will the azure manager report an error. If no label is set or only one of them is set, it'll be set to the default value and the logic continues.

**Comment by marwanad** [comment]
> I think the issue will be solved by setting the default `MaxSize` 1 instead of -1, and output a warning if max/min label is missing. In this case, only when the user sets the wrong max/min label will the azure manager report an error. If no label is set or only one of them is set, it'll be set to the default value and the logic continues.

yeah, I thought about doing that but we override those values anyways in `listScalesets()` so this parsing logic seems useless. I think setting maxValue with a default 1 can be misleading.

**Comment by feiskyer** [comment]
> yeah, I thought about doing that but we override those values anyways in listScalesets() so this parsing logic seems useless. I think setting maxValue with a default 1 can be misleading.

Looks reasonable. We shouldn't have two different places to setup those options

**Comment by nilo19** [comment]
sorry don't notice the similar logic in `listScaleSets`

**Pull request merged**
