### PR TITLE
updating CA version to 1.21.0

### PR DESCRIPTION
**Pull request by jayantjain93**

### CODE REVIEW

**Comment by feiskyer** [comment]
@jayantjain93 have you updated kubernetes vendors in some commit? we should upgrade vendoring before bumping version

**Comment by jayantjain93** [comment]
@feiskyer I was going to update it after updating the version. Updating now.

**Comment by jayantjain93** [comment]
Vendor updated in #4042

**Comment by jayantjain93** [comment]
now that vendor is merged, is this a go ahead.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
