### PR TITLE
Upgrade OCI providers SDK to v65.75.2.

### LINKED ISSUE #7341: Cluster-AutoScaler: Need pick up latest versions of OCI-GO-SDK
**Which component are you using?**: Cluster AutoScaler

**Which component hosted in this repository is this a feature for?**:  [Link to repo](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/oci/vendor-internal/github.com/oracle/oci-go-sdk)

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: OCI GO SDK has released several new versions since last year's update. Several issues has been identified and addressed within the latest GO SDK but has not been picked up by the autoscaler.
 

**Describe the solution you'd like.**: Upgrade the OCI GO SDK version to [some latest version](https://github.com/oracle/oci-go-sdk/releases?page=1), at least >= 65.55.1. 

**Describe any alternative solutions you've considered.**: NA

**Additional context.**:

### PR DESCRIPTION
**Pull request by jlamillan**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Updates the vendored Oracle Cloud Infrastructure Golang SDK to the latest v65.75.2.

#### Which issue(s) this PR fixes:

Fixes #7341

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @jlamillan, the changes seem good to me, just want to confirm with you (as you are only the owner of OCI), if it's all good so can we merge this PR?


you approved this (https://github.com/kubernetes/autoscaler/pull/7385#issuecomment-2408110271) but there is no approved label so that's why it is showing this PR is not approved.

**Comment by jlamillan** [comment]
> Hi @jlamillan, the changes seem good to me, just want to confirm with you (as you are only the owner of OCI), if it's all good so can we merge this PR?
> 
> you approved this ([#7385 (comment)](https://github.com/kubernetes/autoscaler/pull/7385#issuecomment-2408110271)) but there is no approved label so that's why it is showing this PR is not approved.

Hi @Shubham82 - yes, please merge.

**Comment by Shubham82** [comment]
@jlamillan, As the owner of OCI Cloud Provider in CA, could you please give the PR an `approve` label so that it will merge?

Thanks!

**Comment by Shubham82** [comment]
cc @kgolab,
Need your approval also to merge this PR. (as you are the [owner](https://github.com/kubernetes/autoscaler/blob/master/hack/OWNERS) of the hack directory)

PTAL!

**Pull request merged**
