### PR TITLE
Note that `--provider-id` is required for self-managed kubelets

### PR DESCRIPTION
**Pull request by stuartnelson3**
Requested in https://github.com/kubernetes/autoscaler/issues/775#issuecomment-484004333

The CLA signing process looks more complicated than it's worth for this PR .. feel free to copy and paste in what I wrote.

### CODE REVIEW

**Comment by mwielgus** [comment]
If you don't want to sign CLA then I have to close this PR. Copying and submitting your stuff by someone else will have unclear legal status.

**Comment by stuartnelson3** [comment]
Alrighty. I signed the CLA. Feel free to re-open.

**Comment by MaciekPytel** [comment]
cc: @ringtail @Jeffwan since this PR is for alibaba and aws documentation

**Comment by ringtail** [comment]
Looks good~

**Pull request merged**
