### PR TITLE
Clarified instructions for helm users when using aws autodiscovery

### PR DESCRIPTION
**Pull request by brunzefb**
This is the second attempt for the PR, there was an issue with the commit email on the commit -- caused sig verification to fail.

### CODE REVIEW

**Comment by Jeffwan** [comment]
@brunzefb  can you help rebase the changes and remove "try#2" in pull request title.

**Comment by gjtempleton** [comment]
Hey @brunzefb, thanks for the PR, are you able to address @Jeffwan's requests?

I'd also question whether this change should live in the Helm chart's [readme](https://github.com/kubernetes/autoscaler/blob/master/charts/README.md) rather than in the AWS CloudProvider readme.

**Comment by brunzefb** [comment]
I can take a look at this.

**Comment by brunzefb** [comment]
@gjtempleton I have addressed @Jeffwan PR title and rebase request. 
I don't have strong feelings about it going to the cloud provider readme or the charts readme/notes or both.  What will it be to get the PR approved?

**Pull request closed without merging**
