### PR TITLE
Update godeps

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by feiskyer** [comment]
@losipiuk @MaciekPytel Which version of kubernetes has been upgraded to in the PR? kubernetes.sync hasn't been updated when doing vendor updates.

**Comment by feiskyer** [comment]
v1.13.0-beta.1 has been released, let me upgrade vendors to this version instead in my new vendor updates PR.

**Comment by losipiuk** [comment]
> Łukasz Osipiuk @MaciekPytel Which version of kubernetes has been upgraded to in the PR? kubernetes.sync hasn't been updated when doing vendor updates.

My bad.
Hard to check exactly. But it was tip of the master around the time this PR was sent out.

**Pull request merged**
