### PR TITLE
Cherry-pick #3124: Allow small tolerance on memory capacity when comparing nodegroups

### PR DESCRIPTION
**Pull request by DWSR**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Since this is in master, but no release-1.18 or release-1.17, I think we should be back porting this via those other branches as well, otherwise we will regress as people upgrade from the 1.16 release to later releases

**Comment by DWSR** [comment]
@JoelSpeed I agree. How would you like that to happen? Cherry pick from master to 1.18, from 1.18 to 1.17, etc.? Or should I simply open PRs for everything in parallel and let things become Eventually Consistent?

**Comment by JoelSpeed** [comment]
> Cherry pick from master to 1.18, from 1.18 to 1.17, etc.?

That is the normal approach I believe yes, but I'd defer to someone like @MaciekPytel who is more involved with this project for the final say. Personally, I think there would be issue having them open in parallel, if the PR for an earlier release is merged before the PR for the later release this could become very confusing (if there's a delay for instance or a particular version drops of support and is decided that the cherry-pick should not merge etc)

**Comment by MaciekPytel** [comment]
I generally agree with @JoelSpeed. However, we're planning to do patch releases on all branches soon, so in the interest of making sure this gets to all branches in time I'm ok with opening cherry-picks in parallel. I'll make sure to merge them in the right order.

**Comment by DWSR** [comment]
> I generally agree with @JoelSpeed. However, we're planning to do patch releases on all branches soon, so in the interest of making sure this gets to all branches in time I'm ok with opening cherry-picks in parallel. I'll make sure to merge them in the right order.

👍 I will open them all today

**Comment by nigelellis** [comment]
@DWSR thank you for porting this and starting the cherrypick process.   I'm running EKS on 1.17 and also need this fix.   @MaciekPytel, I checked the 1.17 cherry picks and didn't find this listed.    Is there an approximate ETA on when this would get pulled in and when the next rollup release would be for 1.17?  Thank you.

**Comment by nigelellis** [comment]
I found the cherry-pick issue that's tracking the 1.17 - tracked at https://github.com/kubernetes/autoscaler/issues/3317.  Thanks.

**Comment by MaciekPytel** [comment]
Cherry-picks to 1.18 and 1.17 were merged, so there is no reason to block this anymore.
/lgtm
/approve

**Pull request merged**
