### PR TITLE
Add new aws instance types: r5b, m5zn, d3, d3en

### PR DESCRIPTION
**Pull request by dbonfigli**
Update the aws instance types map with the recently added new instance types.

### CODE REVIEW

**Comment by mcristina422** [comment]
Can you use this tool to generate this file? https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go 

When I do I see more instances like `t4*`, `p4d.24xlarge`

**Comment by dbonfigli** [comment]
You are right, I missed that command from the doc, I updated the list with it now.

**Comment by koenvo** [comment]
> Cover #3742 too.

Thanks! I was still struggling to get the `gen.go` script working.

**Comment by aianus** [comment]
Anything left to do here besides the approval?

Would love to switch our CI cluster to m5zn

**Comment by gjtempleton** [comment]
As you say, should just be the approval from one of the AWS cloud provider owners required now.

I've just noticed that @Jeffwan is no longer at AWS, tagging in @jaypipes as well just in case.

**Comment by jaypipes** [comment]
/lgtm
/approve

thank you @aianus!

**Pull request merged**
