### PR TITLE
VPA release 0.13.0

### PR DESCRIPTION
**Pull request by jbartosik**
Increase VPA version for 0.13.0 release

#5355

### CODE REVIEW

**Comment by jbartosik** [comment]
VPA e2e tests are looking good.

**Comment by jbartosik** [comment]
/hold

I might want to merge #5275 before this

**Comment by jbartosik** [comment]
I'll try to add and follow instructions for release (#5453). All PRs I planned to be in this release merged. Now I'll wait for e2e tests to run and if they're green I'll continue with the release process

**Comment by jbartosik** [comment]
/hold cancel

All PRs I wanted in this release merged.
E2E tests run after they merged and are green: https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#Summary

@kgolab @mwielgus please take a look

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
