### PR TITLE
Add missing daemonsets and replicasets to ALI example cluster role

### PR DESCRIPTION
**Pull request by DasyDong**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it:**
The ALI examples appear to be missing the daemonsets and replicasets resource under the apps apiGroups 

**Which issue(s) this PR fixes:**
#3085

### CODE REVIEW

**Comment by Jeffwan** [comment]
/cc @ringtail 

Add Alicloud folks to help review

**Comment by ringtail** [comment]
@Jeffwan Could you help to merge this PR

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
