### PR TITLE
Add example to AWS readme if taint has value

### PR DESCRIPTION
**Pull request by afirth**
/area provider/aws
Maybe helps https://github.com/kubernetes/autoscaler/issues/2434 - TBD in the issue

### CODE REVIEW

**Comment by gjtempleton** [comment]
Thanks for the PR!

I'm not clear on how this resolves #2434 though.

**Comment by afirth** [comment]
> Thanks for the PR!
> 
> I'm not clear on how this resolves #2434 though.

As far as I could tell, all comments in that issue were a) expecting CAS to taint new nodes b) failing to specify the `Effect` or c) using a taint which is ignored by scheduler.
Basically, working as designed I think. For most/all of those comments I think seeing this doc would solve their issue

**Comment by afirth** [comment]
/remove-lifecycle stale

Not sure what's against merging this.. want me to remove the /fix?

**Comment by gjtempleton** [comment]
Yeah, let's remove the `fixes`, merge this, and confirm whether it does resolve the issue with those who had commented in the issue rather than assuming it resolves all of the user queries in there.

**Comment by afirth** [comment]
Done :)

**Comment by gjtempleton** [comment]
Thanks! And thanks for persisting with this.

/lgtm
/approve

**Pull request merged**
