### PR TITLE
Azure: Remove AKS vmType

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind deprecation
/kind documentation
/kind cleanup

#### What this PR does / why we need it:

This PR removes the obsolete, non-working implementation for manual AKS cluster integration as expressed via the `"aks"` `vmType` configuration.

Node autoscaling has long been a first class GA feature of AKS. See:

- https://docs.microsoft.com/azure/aks/autoscaler

Running the Azure cluster-autoscaler provider manually on your cluster is not a supported feature. To aid future maintainability of the project, we're removing these non-working code paths and updating documentation.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Azure: Remove AKS vmType
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gandhipr** [comment]
we plan on not removing this at the moment

**Comment by x13n** [comment]
Closing per comment from @gandhipr above. Please reopen if anything changes.

/close

**Comment by jackfrancis** [comment]
@x13n thanks, I've been doing further tests to prove that the "AKS" vmType is not a currently functioning option on an AKS cluster.

@gandhipr could you kindly re-open this PR as I would like to advocate that we begin reviewing this? thanks!

**Comment by gandhipr** [comment]
I don't have permissions for reopening a PR. Feel free to reopen if you have permissions to do so @jackfrancis .
@x13n could you please help with this?

**Comment by jackfrancis** [comment]
/reopen

(this probably won't work from me :))

**Comment by x13n** [comment]
Huh, looks like nobody can reopen if there were changes to the source branch. I see there's a new PR now, apologies for the trouble!

**Comment by jackfrancis** [comment]
@x13n No prob, TIL (well earlier this week to be exact 😀)

**Pull request closed without merging**
