### PR TITLE
Missing Policy for the k8s-cluster-autoscaler to read ASG Tags

### PR DESCRIPTION
**Pull request by RafaelMoreira1180778**
When deploying the template for the example for the `auto-discovery` of the ASG on AWS (tweaked to my needs) I noticed this error being thrown: 

`aws_cloud_provider.go:389] Failed to create AWS Manager: cannot autodiscover ASGs: AccessDenied: User: [assumed-role] is not authorized to perform: autoscaling:DescribeTags because no identity-based policy allows the autoscaling:DescribeTags action`

After adding the `autoscaling:DescribeTags` alongside all the others present in the README.file the k8s-cluster-autoscaler started being able to discover new ASG correctly.

### CODE REVIEW

**Comment by gjtempleton** [comment]
/area provider/aws

Hey, thanks for the PR, can you please follow the instructions to sign the CLA in the first comment?

**Comment by gjtempleton** [comment]
/assign @gjtempleton 

The use of autodiscovery by tags, and the requirement to add the permission for `autoscaling:DescribeTags` is already covered in the sentence immediately following the snippet you're modifying. If anything I'd rather be more explicit and provide two snippets:

1. The minimum permissions required to run the CA in AWS with a hardcoded list of ASGs
1. The minimum permissions required to run the CA in AWS with a ASG autodiscovery

**Comment by gjtempleton** [comment]
Hi @RafaelMoreira1180778, have you had a chance to address the feedback on the PR?

**Comment by mwielgus** [comment]
CLA not signed, comments not addressed, closing. Feel free to reopen once fixed.

**Pull request closed without merging**
