### PR TITLE
7437 Add logging for endpoint resolving errors

### LINKED ISSUE #7437: Cluster Autoscaler does not Log Errors for Endpoint Resolution Failures on Alibaba Cloud
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version:

Cluster Autoscaler 1.31.0

**What environment is this in?**:

Alibaba Cloud

**What did you expect to happen?**:

If there is an endpoint resolution failure due to issues like missing permissions, I expected the error to be logged clearly, allowing for quick diagnosis and troubleshooting.

**What happened instead?**:

When endpoint resolution fails due to permission issues or other errors, the errors are silently ignored, and no logs are produced. This makes it challenging to identify the root cause of scaling issues.

**How to reproduce it (as minimally and precisely as possible)**:

	1.	Deploy Cluster Autoscaler 1.31.0 on an Alibaba Cloud Kubernetes cluster.
	2.	Intentionally misconfigure permissions or restrict access to simulate an endpoint resolution failure.
	3.	Observe that no errors are logged, even though the endpoint resolution fails and scaling does not work as expected.

**Anything else we need to know?**:

Clear error logging is essential for identifying issues with permissions or other endpoint resolution failures. Adding logging for these cases would significantly improve troubleshooting efforts.

### PR DESCRIPTION
**Pull request by maximrub**
Which component this PR applies to?
cluster-autoscaler

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR improves error handling in the Cluster Autoscaler by adding logging for endpoint resolution failures on Alibaba Cloud. Currently, errors such as missing permissions are silently ignored, making it difficult to diagnose scaling issues. With this update, endpoint resolution (e.g., due to permissions) will be logged, enabling easier troubleshooting and faster resolution of configuration issues. This enhancement ensures better visibility into the cause of failures, ultimately improving reliability and supportability.

#### Which issue(s) this PR fixes:

Fixes #7437

#### Does this PR introduce a user-facing change?
no

```release-note
NONE
```

### CODE REVIEW

**Comment by Shubham82** [comment]
cc @ringtail
PTAL!

**Comment by ringtail** [comment]
cc @IrisIris pls take a look.

**Comment by maximrub** [comment]
Hi @ringtail, can someone have a look?

**Comment by ringtail** [comment]
> Hi @ringtail, can someone have a look?

ok

**Comment by IrisIris** [comment]
LGTM

**Comment by ringtail** [comment]
@maximrub @IrisIris Don't have access to merge the PR.

**Comment by maximrub** [comment]
@IrisIris do you have access or we need to ask someone?

**Comment by Shubham82** [comment]
The owners/reviewers (review alicloud PR) of alicloud provider are not members of k8s org, so they can't approve the PR. (`lgtm` AND `approve` labels are not applied)

**Comment by Shubham82** [comment]
Giving LGTM, as this @IrisIris already gave LGTM to this PR

/lgtm

cc @x13n @feiskyer PTAL!

**Comment by maximrub** [comment]
Hi @x13n can you please approve?

**Comment by x13n** [comment]
/approve

It would help to speed up reviews if we had alibaba cloud OWNER be a k8s org member.

**Pull request merged**
