### PR TITLE
VPA release 0.12.0

### PR DESCRIPTION
**Pull request by jbartosik**
#### Which component this PR applies to?

VPA 

#### What type of PR is this?

Increase VPA versions

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by jbartosik** [comment]
After merging #5111 all e2e tests are passing (summary of the [dashboard](https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#Summary) still says flaky / broken for some test suites but when you click to specific tabs you can see that tests are passing now).

I want to release this quickly because I think that VPA 0.11 doesn't work with K8s 1.25 (because of API removals).

@krzysied @mwielgus please take a look

**Comment by jbartosik** [comment]
/hold

I want to wait for:
-  #5127 to merge
- e2e run after it merges to make sure VPA is still working.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
