### PR TITLE
Remove GKE Cloud provider

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by losipiuk** [comment]
@MaciekPytel / @aleksandra-malinowska ping :)

**Comment by mwielgus** [comment]
Closing and reopening to trigger Travis rerun.

**Comment by MaciekPytel** [comment]
I don't approve this PR - I wanted to be the one to do that :(

**Comment by mwielgus** [comment]
Closing so that @MaciekPytel can do the PR.

**Comment by MaciekPytel** [comment]
/lgtm
/approve
/hold
Please merge _**after**_ you make sure nodegroupset processor is correctly handled.

**Pull request merged**
