### PR TITLE
Cluster Autoscaler 1.2.4

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Update Cluster Autoscaler version to 1.2.4

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
It isn't, see #1346

**Comment by feiskyer** [comment]
Since this is still not ready yet, could we wait a while for a critical bug fix for Azure?

**Comment by MaciekPytel** [comment]
Note that Kubernetes 1.10 (and by extension CA 1.2) will go end of life in the next few days. Ideally CA 1.2.4 should be released in time to make it into the final 1.10 release. So we don't have much time for fixes.

**Comment by spronin-aurea** [comment]
Can we move forward here to release with [#1478](https://github.com/kubernetes/autoscaler/pull/1478) please ?

**Pull request merged**
