### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by JamesClonk**
#### Which component this PR applies to?

cluster-autoscaler externalgrpc documentation

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Fixes as typo in the documentation

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @JamesClonk 
Same typo issue [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/linode/README.md) also for linode cloudprovider.

```
Log levels of intertest for the Linode provider are:

1 (flag: --v=1): basic logging at start;
2 (flag: --v=2): logging of the node group composition at every scan; 
```
Update that one also in this PR.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
