### PR TITLE
[CA-1.17] Backport clusterapi provider to cluster-autoscaler-release-1.17

### PR DESCRIPTION
**Pull request by detiber**
Backports the clusterapi provider for cluster-autoscaler to the cluster-autoscaler-release-1.17 branch.

Included are all commits that have been included/backported to the cluster-autoscaler-release-1.18 branch as of today.

### CODE REVIEW

**Comment by detiber** [comment]
/assign @elmiko 
Still WIP, haven't tested that this is functional outside of cleaning up minor conflicts with the cherry picked commits

**Comment by elmiko** [comment]
ack, thanks Jason. happy to help test when you are ready.

**Comment by detiber** [comment]
@elmiko I think this is likely ready for more testing, I believe I've sorted out all of the backport-related issues.

**Comment by elmiko** [comment]
ack, i will most likely get a chance for testing on monday

**Comment by elmiko** [comment]
hey @detiber, i did some manual testing of this PR against a 1.17.2 cluster running from CAPI/CAPD.

i tested with the following process
1. add a new machinedeployment, min size 1, max 4
2. create a workload with a selector for new machinedeployment
3. scale out workload
4. delete workload
5. delete machinedeployment

during this process i watched the autoscaler logs and the kubernetes resource creations/deletions. everything work as i expected, i saw it create new machines as demand increased and delete old machines as they became unused, it also behaved as expected when creating/deletion the machinedeployment. i tested lightly with machinesets as well, it all looked very similar.

i know this needs a rebase at this point, but i think it looks good on my end.

**Comment by detiber** [comment]
Thanks @elmiko I'm currently working on the rebase

**Comment by detiber** [comment]
@elmiko @JoelSpeed  I think this is good to go now that both the latest release has been cut and the rebase is sorted out.

**Comment by elmiko** [comment]
ack, thanks Jason. i'll give it one more test run tomorrow.

**Comment by JoelSpeed** [comment]
I've given it a scan and all looks sane to me, thanks @detiber 
/lgtm

**Comment by elmiko** [comment]
i re-ran this PR through my local test suite, everything worked as i expected. thanks again Jason!

/lgtm

**Comment by mwielgus** [comment]
Why do you need to update client-go?

**Comment by detiber** [comment]
> Why do you need to update client-go?

The updates are limited to just adding the missing packages that were previously unused, I made sure that they were updated using the same commit as the current vendored content. (k8s.io/client-go/dynamic/dynamicinformer, k8s.io/client-go/dynamic/dynamiclister, and k8s.io/client-go/dynamic/fake). Similar changes where needed when adding the cluster api provider to other branches.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
