### PR TITLE
Allow ignoring volumes in drainable check

### LINKED ISSUE #6417: Local PV will prevent node scaling down
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: v1.26.3

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.11-eks-8cb36c9
</pre></details>

**What environment is this in?**:

EKS

**What did you expect to happen?**:

Under-utilized nodes with local PV should be scaled down

**What happened instead?**:

Under-utilized nodes with local PV cannot be scaled down

**How to reproduce it (as minimally and precisely as possible)**:

If pod has local PV (provisioned by [local-volume-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/provisioner.md) in our use case) mounted
CA refuses to evict the pod because the local pv has NodeAffinity for specific node
There is no way we can bypass this restriction to scale down those under-utilized nodes

**Anything else we need to know?**:

Specifying `safe-to-evict-local-volumes` and `safe-to-evict` does no help,
because pod will eventually enter bounded PV check where it will fail

I think we should provide an option to remove some volumes before bounded PV check

### PR DESCRIPTION
**Pull request by jewelzqiu**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #6417

#### Does this PR introduce a user-facing change?

```release-note
Allow ignoring volumes in drainable check
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x13n** [comment]
/assign

Isn't it sufficient to specify `--skip-nodes-with-local-storage=false`? This should have the same effect.

**Comment by wackxu** [comment]
> /assign
> 
> Isn't it sufficient to specify `--skip-nodes-with-local-storage=false`? This should have the same effect.


I've tried it but it doesn't work, can you give me some advice?

**Comment by x13n** [comment]
What reason for not scaling down do you see? There should be a log line matching `node .* cannot be removed:`

**Pull request closed without merging**
