### PR TITLE
Update godeps

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by losipiuk** [comment]
@feiskyer  please take a look at change when I update the azure compute client version. Should the azure cloud provider still work.

**Comment by aleksandra-malinowska** [comment]
Please remove changes to addon resizer and vertical pod autoscaler vendor/

**Comment by losipiuk** [comment]
> Please remove changes to addon resizer and vertical pod autoscaler vendor/

Done - I was not aware `fix_godeps.sh` would remove vendor from other subprojects of c-a (makes sense if you give it a thought)  and I squashed updated godeps commit with `no_vendor` commits. My bad.

**Pull request merged**
