### PR TITLE
Recalculate clusterStateRegistry after adding multiple node groups

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by MaciekPytel** [comment]
Wouldn't the same issue affect balancing main created group with pre-existing similar nodegroups? Maybe we should just always recalculate after creating nodegroup? I'm not sure if any performance gain of only doing it when multiple node groups were created is worth spilling the logic all over the place anyway.

**Comment by losipiuk** [comment]
>Wouldn't the same issue affect balancing main created group with pre-existing similar nodegroups? Maybe we should just always recalculate after creating nodegroup? I'm not sure if any performance gain of only doing it when multiple node groups were created is worth spilling the logic all over the place anyway.

Definitely makes sense.
Updated.

**Comment by MaciekPytel** [comment]
/lgtm
/approve

/hold 
For any manual testing required. Feel free to cancel hold once tested.

**Comment by losipiuk** [comment]
I tested code before last change. I will risk it still work :) Adding e2e tests anyway.

**Pull request merged**
