### PR TITLE
Add a multi-dimensional pod autoscaler

### PR DESCRIPTION
**Pull request by James-QiuHaoran**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Multidimensional pod autoscaling: https://github.com/kubernetes/autoscaler/blob/master/multidimensional-pod-autoscaler/AEP.md

#### Does this PR introduce a user-facing change?

No.

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [AEP]: https://github.com/kubernetes/autoscaler/blob/master/multidimensional-pod-autoscaler/AEP.md
```

### CODE REVIEW

**Comment by mwielgus** [comment]
Can you split this PR into a chain of smaller PRs of, let's say, 500 lines max (except vendor)? In this form, it will take much much longer to get it reviewed and merged.

**Comment by James-QiuHaoran** [comment]
> Can you split this PR into a chain of smaller PRs of, let's say, 500 lines max (except vendor)? In this form, it will take much much longer to get it reviewed and merged.

Hi @mwielgus , Is it okay for us to split this PR into 4, namely one PR for each of the [MPA API, recommender, updater, admission controller]? If so, I'll do the splitting and create 1 PR at a time for review.

**Comment by mwielgus** [comment]
The smaller PR is, the better - with bigger PRs there is a risk that they will take forever to review. Hard to tell for me whether these 4  PRs will be small enough.

**Comment by James-QiuHaoran** [comment]
New PR request for MPA (with splitted commits): https://github.com/kubernetes/autoscaler/pull/5999

**Pull request closed without merging**
