### PR TITLE
Cherry pick #2545 to 1.17: Read subscription ID from instance metadata

### PR DESCRIPTION
**Pull request by fiunchinho**
Read subscription ID from instance metadata

### CODE REVIEW

**Comment by fiunchinho** [comment]
@losipiuk asked me to submit a PR cherry picking the changes from #2545

**Comment by nilo19** [comment]
Hi @fiunchinho , would you mind revising the title and the description of your PR to meet the format of a cherry-pick PR?

Ref: https://github.com/kubernetes/autoscaler/pull/2572

**Comment by feiskyer** [comment]
/retitle Cherry pick #2545 to 1.17: Read subscription ID from instance metadata

**Pull request merged**
