### PR TITLE
fix empty ProviderID in ali NodeGroupForNode

### PR DESCRIPTION
**Pull request by daimaxiaxie**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When there is a node without an ProviderID in the ali cluster, then block main loop. 
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/autoscaler/issues/6546

#### Special notes for your reviewer:

The problem occurs in ali cloudprovider.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
cc @ringtail

**Comment by Shubham82** [comment]
/lgtm
(as the above comment didn't apply the label)

**Comment by daimaxiaxie** [comment]
rebase. Please @Shubham82 re-add LGTM label, thinks.

**Pull request merged**
