### PR TITLE
increase azclients polling delays

### PR DESCRIPTION
**Pull request by marwanad**
Increase the polling delay from the client's default 5 seconds. This is to avoid GetOperation throttling cases when large operations are happening and polling for async operations is done.

The polling results for async operation is mostly informational as no azure CA operation will block on those so increasing the polling delay shouldn't have any downsides.

This required bumping the cloudprovider client version.

/area provider/azure

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

No idea why the unit test failed. Could you close and re-open to trigger it again?

**Comment by marwanad** [comment]
@feiskyer I think those errors are bubbled down from the Azure provider. I have no clue where or why this is happening but these have popped before in Azure CCM test runs:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/871/pull-cloud-provider-azure-e2e-ccm/1460589945067409408

@nilo19 any ideas?

**Comment by nilo19** [comment]
I am not sure but it could be due to the version of component-base. It's using v0.23.0-alpha.1 while the cloud provider azure is using v0.23.0 which works well.

**Comment by marwanad** [comment]
@nilo19 the 1.23-release branch is running that version with no issues:


https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.23/cluster-autoscaler/go.mod#L35-L36

**Comment by marwanad** [comment]
@feiskyer @nilo19 should we move the clients elsewhere? I was under the impression the AZ clients wont bring over any k8s dependencies but that doesn't seem to be the case when they're in the out of tree repo.

**Comment by marwanad** [comment]
This doesn't fail locally which is odd.

**Comment by marwanad** [comment]
@feiskyer I finally figured it out! 

The `klog` import wasn't playing nicely with the vendored k/k dependencies because of the way it configures component-base/logger. 

Changed everything to match the `cluster-autoscaler-release-1.23` branch which should've honestly been done in main before they created the release branch.

Should be good to go now.

**Review by feiskyer — COMMENTED** [review]
Thanks for fixed the dependency issues

/lgtm
/approve

**Pull request merged**
