### PR TITLE
change file name to ca-bundle.crt

### PR DESCRIPTION
**Pull request by VinayVanama**

### CODE REVIEW

**Comment by mwielgus** [comment]
Please sign CLA.

**Comment by bskiba** [comment]
@Jeffwan Do I understand correctly that we should not merge this PR?

**Comment by mwielgus** [comment]
@Jeffwan I take your comment as "do not merge". Closing PR. Please reopen if we misunderstood your intention.

**Comment by Jeffwan** [comment]
@bskiba Right. I think example just provide template and user needs to customize it.

**Pull request closed without merging**
